In [53]:
import pandas as pd
import numpy as np

from pathlib import Path

project_path = Path.cwd().parent

free_text_path = project_path / "data" / "raw" / "free-text.csv"

df = pd.read_csv(free_text_path)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

C:\Users\LOQ\AppData\Local\Temp\ipykernel_19032\2202318899.py:10: DtypeWarning: Columns (4: DU.key1.key1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(free_text_path)

Dataset loaded successfully!
Dataset shape: (562583, 10)

In [54]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

NumPy: 2.5.4
Pandas: 3.0.6

In [55]:
free_df = pd.read_csv("../data/raw/free-text.csv")

C:\Users\LOQ\AppData\Local\Temp\ipykernel_19032\4036018349.py:1: DtypeWarning: Columns (4: DU.key1.key1) have mixed types. Specify dtype option on import or set low_memory=False.
  free_df = pd.read_csv("../data/raw/free-text.csv")

In [56]:
print("Dataset shape:", free_df.shape)

Dataset shape: (562583, 10)

In [57]:
display(free_df.head())

,participant,session,key1,key2,DU.key1.key1,DD.key1.key2,DU.key1.key2,UD.key1.key2,UU.key1.key2,Unnamed: 9
0,p001,1,W,Shift,0.15,-0.796,0.166,-0.946,0.016,NaN
1,p001,1,Shift,e,0.962,1.148,1.255,0.186,0.293,NaN
2,p001,1,e,Space,0.107,0.172,0.252,0.065,0.145,NaN
3,p001,1,Space,b,0.08,0.200,0.280,0.120,0.200,NaN
4,p001,1,b,e,0.08,0.320,0.480,0.240,0.400,NaN

In [58]:
print("Columns:")
for i, column in enumerate(free_df.columns):
    print(i, ":", column)

Columns:
0 : participant
1 : session
2 : key1
3 : key2
4 : DU.key1.key1
5 : DD.key1.key2
6 : DU.key1.key2
7 : UD.key1.key2
8 : UU.key1.key2
9 : Unnamed: 9

In [59]:
free_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 562583 entries, 0 to 562582
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   participant    562583 non-null  str
 1   session        562583 non-null  int64
 2   key1           562583 non-null  str
 3   key2           562385 non-null  str
 4   DU.key1.key1   562583 non-null  object
 5   DD.key1.key2   562385 non-null  float64
 6   DU.key1.key2   562385 non-null  float64
 7   UD.key1.key2   562385 non-null  float64
 8   UU.key1.key2   562385 non-null  float64
 9   Unnamed: 9     13 non-null      float64
dtypes: float64(5), int64(1), object(1), str(3)
memory usage: 47.6+ MB

In [60]:
free_df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
participant,562583,99,p049,6813,NaN,NaN,NaN,NaN,NaN,NaN,NaN
session,562583.0,NaN,NaN,NaN,1.50552,0.49997,1.0,1.0,2.0,2.0,2.0
key1,562583,132,Space,93871,NaN,NaN,NaN,NaN,NaN,NaN,NaN
key2,562385,145,Space,93870,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DU.key1.key1,562583,4501,0.08,12599,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DD.key1.key2,562385.0,NaN,NaN,NaN,0.291818,5.968022,-568.083,0.12,0.174,0.272,1712.727
DU.key1.key2,562385.0,NaN,NaN,NaN,0.495465,5.49027,-7.935,0.216,0.272,0.379,1713.061
UD.key1.key2,562385.0,NaN,NaN,NaN,0.088476,5.479273,-568.162,0.019,0.081,0.173,1712.648
UU.key1.key2,562385.0,NaN,NaN,NaN,0.292115,4.635057,-10.782,0.118,0.176,0.272,1712.982
Unnamed: 9,13.0,NaN,NaN,NaN,0.210923,0.134409,0.042,0.072,0.192,0.328,0.464

In [61]:
import sys

print(sys.executable)

c:\Users\LOQ\OneDrive\Desktop\Komal_clg\5th sem\DL Lab\Project\DeepKey_DL_Project\venv_new\Scripts\python.exe

In [62]:
print("Column names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Column names:
['participant', 'session', 'key1', 'key2', 'DU.key1.key1', 'DD.key1.key2', 'DU.key1.key2', 'UD.key1.key2', 'UU.key1.key2 ', 'Unnamed: 9']

First 5 rows:

,participant,session,key1,key2,DU.key1.key1,DD.key1.key2,DU.key1.key2,UD.key1.key2,UU.key1.key2,Unnamed: 9
0,p001,1,W,Shift,0.15,-0.796,0.166,-0.946,0.016,NaN
1,p001,1,Shift,e,0.962,1.148,1.255,0.186,0.293,NaN
2,p001,1,e,Space,0.107,0.172,0.252,0.065,0.145,NaN
3,p001,1,Space,b,0.08,0.200,0.280,0.120,0.200,NaN
4,p001,1,b,e,0.08,0.320,0.480,0.240,0.400,NaN

In [63]:
print("Dataset information:")
df.info()

print("\nMissing values per column:")
print(df.isnull().sum())

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 562583 entries, 0 to 562582
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   participant    562583 non-null  str
 1   session        562583 non-null  int64
 2   key1           562583 non-null  str
 3   key2           562385 non-null  str
 4   DU.key1.key1   562583 non-null  object
 5   DD.key1.key2   562385 non-null  float64
 6   DU.key1.key2   562385 non-null  float64
 7   UD.key1.key2   562385 non-null  float64
 8   UU.key1.key2   562385 non-null  float64
 9   Unnamed: 9     13 non-null      float64
dtypes: float64(5), int64(1), object(1), str(3)
memory usage: 47.6+ MB

Missing values per column:
participant           0
session               0
key1                  0
key2                198
DU.key1.key1          0
DD.key1.key2        198
DU.key1.key2        198
UD.key1.key2        198
UU.key1.key2        198
Unnamed: 9       562570
dtype: int64

In [64]:
print("Total duplicate rows:", df.duplicated().sum())

print("\nNumerical statistics:")
display(df.describe())

Total duplicate rows: 7385

Numerical statistics:

,session,DD.key1.key2,DU.key1.key2,UD.key1.key2,UU.key1.key2,Unnamed: 9
count,562583.00000,562385.000000,562385.000000,562385.000000,562385.000000,13.000000
mean,1.50552,0.291818,0.495465,0.088476,0.292115,0.210923
std,0.49997,5.968022,5.490270,5.479273,4.635057,0.134409
min,1.00000,-568.083000,-7.935000,-568.162000,-10.782000,0.042000
25%,1.00000,0.120000,0.216000,0.019000,0.118000,0.072000
50%,2.00000,0.174000,0.272000,0.081000,0.176000,0.192000
75%,2.00000,0.272000,0.379000,0.173000,0.272000,0.328000
max,2.00000,1712.727000,1713.061000,1712.648000,1712.982000,0.464000

In [65]:
print("Unique values per column:")
print(df.nunique())

Unique values per column:
participant        99
session             2
key1              132
key2              145
DU.key1.key1     4501
DD.key1.key2     8988
DU.key1.key2     5758
UD.key1.key2     6935
UU.key1.key2     3417
Unnamed: 9         13
dtype: int64

In [66]:
fixed_text_path = project_path / "data" / "raw" / "fixed-text.csv"

fixed_df = pd.read_csv(fixed_text_path)

print("Fixed-text dataset shape:", fixed_df.shape)
print("\nColumns:")
print(fixed_df.columns.tolist())

print("\nFirst 5 rows:")
display(fixed_df.head())

print("\nDataset information:")
fixed_df.info()

Fixed-text dataset shape: (19772, 50)

Columns:
['participant', 'session', 'repetition', 'DU.v.v', 'DD.v.p', 'DU.v.p', 'UD.v.p', 'UU.v.p', 'DU.p.p', 'DD.p.w', 'DU.p.w', 'UD.p.w', 'UU.p.w', 'DU.w.w', 'DD.w.j', 'DU.w.j', 'UD.w.j', 'UU.w.j', 'DU.j.j', 'DD.j.k', 'DU.j.k', 'UD.j.k', 'UU.j.k', 'DU.k.k', 'DD.k.e', 'DU.k.e', 'UD.k.e', 'UU.k.e', 'DU.e.e', 'DD.e.u', 'DU.e.u', 'UD.e.u', 'UU.e.u', 'DU.u.u', 'DD.u.r', 'DU.u.r', 'UD.u.r', 'UU.u.r', 'DU.r.r', 'DD.r.k', 'DU.r.k', 'UD.r.k', 'UU.r.k', 'DU.k.k.1', 'DD.k.b', 'DU.k.b', 'UD.k.b', 'UU.k.b', 'DU.b.b', 'total time']

First 5 rows:

,participant,session,repetition,DU.v.v,DD.v.p,DU.v.p,UD.v.p,UU.v.p,DU.p.p,DD.p.w,...,DU.r.k,UD.r.k,UU.r.k,DU.k.k.1,DD.k.b,DU.k.b,UD.k.b,UU.k.b,DU.b.b,total time
0,p001,1,1,0.129,1.917,1.804,2.046,1.933,0.113,0.719,...,1.289,1.509,1.423,0.086,0.450,0.352,0.536,0.438,0.098,10.101
1,p001,1,2,0.112,0.192,0.096,0.304,0.208,0.096,0.448,...,0.921,1.135,1.056,0.079,0.418,0.336,0.497,0.415,0.082,5.768
2,p001,1,3,0.088,0.253,0.182,0.341,0.270,0.071,1.536,...,1.066,1.271,1.194,0.077,0.448,0.352,0.525,0.429,0.096,7.877
3,p001,1,4,0.104,0.323,0.233,0.427,0.337,0.090,0.912,...,0.927,1.129,1.063,0.066,0.418,0.330,0.484,0.396,0.088,5.443
4,p001,1,5,0.107,0.188,0.100,0.295,0.207,0.088,0.858,...,1.237,1.423,1.344,0.079,0.457,0.369,0.536,0.448,0.088,5.284

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 19772 entries, 0 to 19771
Data columns (total 50 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   participant  19772 non-null  str
 1   session      19772 non-null  int64
 2   repetition   19772 non-null  int64
 3   DU.v.v       19772 non-null  float64
 4   DD.v.p       19772 non-null  float64
 5   DU.v.p       19772 non-null  float64
 6   UD.v.p       19772 non-null  float64
 7   UU.v.p       19772 non-null  float64
 8   DU.p.p       19772 non-null  float64
 9   DD.p.w       19772 non-null  float64
 10  DU.p.w       19772 non-null  float64
 11  UD.p.w       19772 non-null  float64
 12  UU.p.w       19772 non-null  float64
 13  DU.w.w       19772 non-null  float64
 14  DD.w.j       19772 non-null  float64
 15  DU.w.j       19772 non-null  float64
 16  UD.w.j       19772 non-null  float64
 17  UU.w.j       19772 non-null  float64
 18  DU.j.j       19772 non-null  float64
 19  DD.j.k       19772 non-null  float64
 20  DU.j.k       19772 non-null  float64
 21  UD.j.k       19772 non-null  float64
 22  UU.j.k       19772 non-null  float64
 23  DU.k.k       19772 non-null  float64
 24  DD.k.e       19772 non-null  float64
 25  DU.k.e       19772 non-null  float64
 26  UD.k.e       19772 non-null  float64
 27  UU.k.e       19772 non-null  float64
 28  DU.e.e       19772 non-null  float64
 29  DD.e.u       19772 non-null  float64
 30  DU.e.u       19772 non-null  float64
 31  UD.e.u       19772 non-null  float64
 32  UU.e.u       19772 non-null  float64
 33  DU.u.u       19772 non-null  float64
 34  DD.u.r       19772 non-null  float64
 35  DU.u.r       19772 non-null  float64
 36  UD.u.r       19772 non-null  float64
 37  UU.u.r       19772 non-null  float64
 38  DU.r.r       19772 non-null  float64
 39  DD.r.k       19772 non-null  float64
 40  DU.r.k       19772 non-null  float64
 41  UD.r.k       19772 non-null  float64
 42  UU.r.k       19772 non-null  float64
 43  DU.k.k.1     19772 non-null  float64
 44  DD.k.b       19772 non-null  float64
 45  DU.k.b       19772 non-null  float64
 46  UD.k.b       19772 non-null  float64
 47  UU.k.b       19772 non-null  float64
 48  DU.b.b       19772 non-null  float64
 49  total time   19772 non-null  float64
dtypes: float64(47), int64(2), str(1)
memory usage: 7.6 MB

In [67]:
print(df.shape)
print(df.columns.tolist())

(562583, 10)
['participant', 'session', 'key1', 'key2', 'DU.key1.key1', 'DD.key1.key2', 'DU.key1.key2', 'UD.key1.key2', 'UU.key1.key2 ', 'Unnamed: 9']

In [68]:
print("Last 10 rows:")
display(df.tail(10))

print("\nUnnamed column information:")
print(df["Unnamed: 9"].value_counts(dropna=False).head(10))

print("\nMissing values in Unnamed: 9:")
print(df["Unnamed: 9"].isna().sum())

Last 10 rows:

,participant,session,key1,key2,DU.key1.key1,DD.key1.key2,DU.key1.key2,UD.key1.key2,UU.key1.key2,Unnamed: 9
562573,p100,2,Space,t,0.143,0.086,0.165,-0.057,0.022,NaN
562574,p100,2,t,h,0.079,0.084,0.184,0.005,0.105,NaN
562575,p100,2,h,e,0.1,0.052,0.159,-0.048,0.059,NaN
562576,p100,2,e,Space,0.107,0.078,0.201,-0.029,0.094,NaN
562577,p100,2,Space,s,0.123,0.114,0.238,-0.009,0.115,NaN
562578,p100,2,s,t,0.124,0.120,0.195,-0.004,0.071,NaN
562579,p100,2,t,a,0.075,0.092,0.272,0.017,0.197,NaN
562580,p100,2,a,r,0.18,0.100,0.215,-0.080,0.035,NaN
562581,p100,2,r,s,0.115,0.152,0.276,0.037,0.161,NaN
562582,p100,2,s,NaN,0.124,NaN,NaN,NaN,NaN,NaN

Unnamed column information:
Unnamed: 9
NaN      562570
0.185         1
0.042         1
0.464         1
0.072         1
0.280         1
0.345         1
0.065         1
0.331         1
0.064         1
Name: count, dtype: int64

Missing values in Unnamed: 9:
562570

In [69]:
print("Number of unique participants:")
print(df["participant"].nunique())

print("\nParticipant IDs:")
print(df["participant"].unique())

print("\nNumber of sessions:")
print(df["session"].nunique())

print("\nFirst 10 participant-session combinations:")
display(df[["participant", "session"]].head(10))

Number of unique participants:
99

Participant IDs:
<ArrowStringArray>
['p001', 'p002', 'p003', 'p004', 'p005', 'p006', 'p007', 'p008', 'p009',
 'p010', 'p011', 'p012', 'p013', 'p014', 'p015', 'p016', 'p017', 'p018',
 'p019', 'p020', 'p021', 'p022', 'p023', 'p024', 'p025', 'p026', 'p027',
 'p028', 'p029', 'p030', 'p031', 'p032', 'p033', 'p034', 'p035', 'p036',
 'p037', 'p038', 'p039', 'p040', 'p041', 'p042', 'p043', 'p044', 'p045',
 'p046', 'p047', 'p048', 'p049', 'p050', 'p051', 'p052', 'p053', 'p054',
 'p055', 'p056', 'p057', 'p058', 'p059', 'p060', 'p061', 'p062', 'p063',
 'p064', 'p065', 'p066', 'p067', 'p068', 'p069', 'p070', 'p071', 'p072',
 'p073', 'p074', 'p075', 'p076', 'p077', 'p078', 'p079', 'p080', 'p081',
 'p082', 'p083', 'p084', 'p085', 'p086', 'p087', 'p088', 'p089', 'p090',
 'p091', 'p092', 'p093', 'p094', 'p095', 'p097', 'p098', 'p099', 'p100']
Length: 99, dtype: str

Number of sessions:
2

First 10 participant-session combinations:

  participant  session
0        p001        1
1        p001        1
2        p001        1
3        p001        1
4        p001        1
5        p001        1
6        p001        1
7        p001        1
8        p001        1
9        p001        1

In [70]:
participant_counts = df["participant"].value_counts()

print("Records per participant:")
display(participant_counts)

print("\nSummary statistics:")
display(participant_counts.describe())

Records per participant:

participant
p049    6813
p005    6706
p073    6647
p045    6549
p012    6533
        ...
p094    5159
p095    5074
p032    5031
p010    4986
p004    4738
Name: count, Length: 99, dtype: int64

Summary statistics:

count      99.000000
mean     5682.656566
std       385.411023
min      4738.000000
25%      5437.000000
50%      5655.000000
75%      5943.500000
max      6813.000000
Name: count, dtype: float64

In [71]:
print(df.dtypes)

participant          str
session            int64
key1                 str
key2                 str
DU.key1.key1      object
DD.key1.key2     float64
DU.key1.key2     float64
UD.key1.key2     float64
UU.key1.key2     float64
Unnamed: 9       float64
dtype: object

In [72]:
print("Numerical columns:")
display(df.select_dtypes(include="number").head())

print("\nNon-numerical columns:")
display(df.select_dtypes(exclude="number").head())

Numerical columns:

,session,DD.key1.key2,DU.key1.key2,UD.key1.key2,UU.key1.key2,Unnamed: 9
0,1,-0.796,0.166,-0.946,0.016,NaN
1,1,1.148,1.255,0.186,0.293,NaN
2,1,0.172,0.252,0.065,0.145,NaN
3,1,0.200,0.280,0.120,0.200,NaN
4,1,0.320,0.480,0.240,0.400,NaN

Non-numerical columns:

  participant   key1   key2 DU.key1.key1
0        p001      W  Shift         0.15
1        p001  Shift      e        0.962
2        p001      e  Space        0.107
3        p001  Space      b         0.08
4        p001      b      e         0.08

In [73]:
timing_columns = [
    "DU.key1.key1",
    "DD.key1.key2",
    "DU.key1.key2",
    "UD.key1.key2",
    "UU.key1.key2 "
]

print("Timing feature statistics:")
display(df[timing_columns].describe())

Timing feature statistics:

        DD.key1.key2   DU.key1.key2   UD.key1.key2  UU.key1.key2
count  562385.000000  562385.000000  562385.000000  562385.000000
mean        0.291818       0.495465       0.088476       0.292115
std         5.968022       5.490270       5.479273       4.635057
min      -568.083000      -7.935000    -568.162000     -10.782000
25%         0.120000       0.216000       0.019000       0.118000
50%         0.174000       0.272000       0.081000       0.176000
75%         0.272000       0.379000       0.173000       0.272000
max      1712.727000    1713.061000    1712.648000    1712.982000

In [74]:
print("Non-missing values in Unnamed: 9:")

display(
    df.loc[
        df["Unnamed: 9"].notna(),
        ["participant", "session", "key1", "key2", "Unnamed: 9"]
    ]
)

Non-missing values in Unnamed: 9:

,participant,session,key1,key2,Unnamed: 9
23481,p005,1,2,",0.087,1.088,1.183,1.001,1.096,\np005,1,",0.185
169381,p031,1,Backspace,",0.081,0.761,0.896,0.68,0.815,\np031,1,",0.042
177980,p033,1,e,",0.088,0.2,0.28,0.112,0.192\np033,1,",0.464
181842,p033,2,t,",0.079,0.184,0.263,0.105,0.184,\np033,2,",0.072
204716,p037,2,Backspace,",0.134,0.281,0.502,0.147,0.368,\np037,2,",0.280
205245,p037,2,Backspace,",0.166,0.569,0.726,0.403,0.56,\np037,2,",0.345
306776,p055,1,Backspace,",0.123,0.785,0.87,0.662,0.747,\np055,1,",0.065
319078,p057,1,y,",0.137,0.304,0.49,0.167,0.353,\np057,1,",0.331
491603,p087,1,Backspace,",0.096,6.082,6.177,5.986,6.081,\np087,1,",0.064
491610,p087,1,Shift,",0.472,1.76,1.888,1.288,1.416,\np087,1,",0.120
491613,p087,1,Backspace,",0.096,0.8,0.896,0.704,0.8,\np087,1,",0.192
552060,p099,1,Shift,",0.0,0.06,0.229,0.06,0.229,\np099,1,",0.254
552098,p099,1,Shift,",0.0,0.033,0.192,0.033,0.192,\np099,1,",0.328

In [75]:
print("Number of unique participants:")
print(df["participant"].nunique())

print("\nParticipant IDs:")
print(df["participant"].unique())

print("\nNumber of unique session labels:")
print(df["session"].nunique())

print("\nNumber of unique participant-session combinations:")
print(df[["participant", "session"]].drop_duplicates().shape[0])

Number of unique participants:
99

Participant IDs:

<ArrowStringArray>
['p001', 'p002', 'p003', 'p004', 'p005', 'p006', 'p007', 'p008', 'p009',
 'p010', 'p011', 'p012', 'p013', 'p014', 'p015', 'p016', 'p017', 'p018',
 'p019', 'p020', 'p021', 'p022', 'p023', 'p024', 'p025', 'p026', 'p027',
 'p028', 'p029', 'p030', 'p031', 'p032', 'p033', 'p034', 'p035', 'p036',
 'p037', 'p038', 'p039', 'p040', 'p041', 'p042', 'p043', 'p044', 'p045',
 'p046', 'p047', 'p048', 'p049', 'p050', 'p051', 'p052', 'p053', 'p054',
 'p055', 'p056', 'p057', 'p058', 'p059', 'p060', 'p061', 'p062', 'p063',
 'p064', 'p065', 'p066', 'p067', 'p068', 'p069', 'p070', 'p071', 'p072',
 'p073', 'p074', 'p075', 'p076', 'p077', 'p078', 'p079', 'p080', 'p081',
 'p082', 'p083', 'p084', 'p085', 'p086', 'p087', 'p088', 'p089', 'p090',
 'p091', 'p092', 'p093', 'p094', 'p095', 'p097', 'p098', 'p099', 'p100']
Length: 99, dtype: str

Number of unique session labels:
2

Number of unique participant-session combinations:
198

In [76]:
sessions_per_participant = (
    df.groupby("participant")["session"]
    .nunique()
)

print("Sessions per participant:")
display(sessions_per_participant.value_counts().sort_index())

print("\nParticipants without exactly 2 sessions:")
display(sessions_per_participant[sessions_per_participant != 2])

Sessions per participant:

session
2    99
Name: count, dtype: int64

Participants without exactly 2 sessions:

Series([], Name: session, dtype: int64)

In [77]:
print("Records in each session:")
display(df["session"].value_counts().sort_index())

print("\nRecords for each participant and session:")
display(
    df.groupby(["participant", "session"])
    .size()
    .reset_index(name="record_count")
    .head(20)
)

Records in each session:

session
1    278186
2    284397
Name: count, dtype: int64

Records for each participant and session:

   participant  session  record_count
0         p001        1          2514
1         p001        2          2744
2         p002        1          2702
3         p002        2          2815
4         p003        1          2593
5         p003        2          2718
6         p004        1          4700
7         p004        2            38
8         p005        1          3296
9         p005        2          3410
10        p006        1          2763
11        p006        2          2881
12        p007        1          2565
13        p007        2          2725
14        p008        1          2474
15        p008        2          2754
16        p009        1          2717
17        p009        2          2786
18        p010        1          2425
19        p010        2          2561

In [78]:
print("Rows containing values in Unnamed: 9:")

display(
    df.loc[
        df["Unnamed: 9"].notna(),
        :
    ]
)

Rows containing values in Unnamed: 9:

,participant,session,key1,key2,DU.key1.key1,DD.key1.key2,DU.key1.key2,UD.key1.key2,UU.key1.key2,Unnamed: 9
23481,p005,1,2,",0.087,1.088,1.183,1.001,1.096,\np005,1,",Shift,0.095,-0.472,0.280,-0.567,0.185
169381,p031,1,Backspace,",0.081,0.761,0.896,0.68,0.815,\np031,1,",Shift,0.135,-0.341,0.177,-0.476,0.042
177980,p033,1,e,",0.088,0.2,0.28,0.112,0.192\np033,1,",Backspace,0.080,0.400,0.544,0.320,0.464
181842,p033,2,t,",0.079,0.184,0.263,0.105,0.184,\np033,2,",Shift,0.079,-0.041,0.151,-0.120,0.072
204716,p037,2,Backspace,",0.134,0.281,0.502,0.147,0.368,\np037,2,",Backspace,0.221,0.342,0.501,0.121,0.280
205245,p037,2,Backspace,",0.166,0.569,0.726,0.403,0.56,\np037,2,",Backspace,0.157,0.319,0.502,0.162,0.345
306776,p055,1,Backspace,",0.123,0.785,0.87,0.662,0.747,\np055,1,",Shift,0.085,-0.168,0.150,-0.253,0.065
319078,p057,1,y,",0.137,0.304,0.49,0.167,0.353,\np057,1,",Shift,0.186,-0.047,0.517,-0.233,0.331
491603,p087,1,Backspace,",0.096,6.082,6.177,5.986,6.081,\np087,1,",Shift,0.095,-0.289,0.159,-0.384,0.064
491610,p087,1,Shift,",0.472,1.76,1.888,1.288,1.416,\np087,1,",Shift,0.128,-0.352,0.248,-0.480,0.120
491613,p087,1,Backspace,",0.096,0.8,0.896,0.704,0.8,\np087,1,",Shift,0.096,-0.192,0.288,-0.288,0.192
552060,p099,1,Shift,",0.0,0.06,0.229,0.06,0.229,\np099,1,",Shift,0.169,-0.029,0.423,-0.198,0.254
552098,p099,1,Shift,",0.0,0.033,0.192,0.033,0.192,\np099,1,",Shift,0.159,-0.002,0.487,-0.161,0.328

In [79]:
print("Missing values in every column:")
display(df.isnull().sum())

Missing values in every column:

participant           0
session               0
key1                  0
key2                198
DU.key1.key1          0
DD.key1.key2        198
DU.key1.key2        198
UD.key1.key2        198
UU.key1.key2        198
Unnamed: 9       562570
dtype: int64

In [80]:
missing_timing = df[
    df[
        [
            "key2",
            "DD.key1.key2",
            "DU.key1.key2",
            "UD.key1.key2",
            "UU.key1.key2 "
        ]
    ].isna().any(axis=1)
]

print("Number of rows with missing key/timing values:")
print(len(missing_timing))

print("\nFirst 20 affected rows:")
display(missing_timing.head(20))

print("\nAffected rows per participant and session:")
display(
    missing_timing.groupby(["participant", "session"])
    .size()
    .reset_index(name="missing_count")
    .head(30)
)

Number of rows with missing key/timing values:
198

First 20 affected rows:

,participant,session,key1,key2,DU.key1.key1,DD.key1.key2,DU.key1.key2,UD.key1.key2,UU.key1.key2,Unnamed: 9
2513,p001,1,e,NaN,0.136,NaN,NaN,NaN,NaN,NaN
5257,p001,2,s,NaN,0.143,NaN,NaN,NaN,NaN,NaN
7959,p002,1,e,NaN,0.1,NaN,NaN,NaN,NaN,NaN
10774,p002,2,s,NaN,0.074,NaN,NaN,NaN,NaN,NaN
13367,p003,1,e,NaN,0.076,NaN,NaN,NaN,NaN,NaN
16085,p003,2,r,NaN,0.106,NaN,NaN,NaN,NaN,NaN
20785,p004,1,.,NaN,8.647,NaN,NaN,NaN,NaN,NaN
20823,p004,2,Space,NaN,178.759,NaN,NaN,NaN,NaN,NaN
24119,p005,1,e,NaN,0.112,NaN,NaN,NaN,NaN,NaN
27529,p005,2,s,NaN,0.104,NaN,NaN,NaN,NaN,NaN
30292,p006,1,e,NaN,0.144,NaN,NaN,NaN,NaN,NaN
33173,p006,2,r,NaN,0.135,NaN,NaN,NaN,NaN,NaN
35738,p007,1,e,NaN,0.107,NaN,NaN,NaN,NaN,NaN
38463,p007,2,s,NaN,0.1,NaN,NaN,NaN,NaN,NaN
40937,p008,1,Space,NaN,0.074,NaN,NaN,NaN,NaN,NaN
43691,p008,2,s,NaN,0.095,NaN,NaN,NaN,NaN,NaN
46408,p009,1,e,NaN,0.151,NaN,NaN,NaN,NaN,NaN
49194,p009,2,s,NaN,0.105,NaN,NaN,NaN,NaN,NaN
51619,p010,1,e,NaN,0.095,NaN,NaN,NaN,NaN,NaN
54180,p010,2,s,NaN,0.111,NaN,NaN,NaN,NaN,NaN

Affected rows per participant and session:

   participant  session  missing_count
0         p001        1              1
1         p001        2              1
2         p002        1              1
3         p002        2              1
4         p003        1              1
5         p003        2              1
6         p004        1              1
7         p004        2              1
8         p005        1              1
9         p005        2              1
10        p006        1              1
11        p006        2              1
12        p007        1              1
13        p007        2              1
14        p008        1              1
15        p008        2              1
16        p009        1              1
17        p009        2              1
18        p010        1              1
19        p010        2              1
20        p011        1              1
21        p011        2              1
22        p012        1              1
23        p012        2              1
24        p013        1              1
25        p013        2              1
26        p014        1              1
27        p014        2              1
28        p015        1              1
29        p015        2              1

In [81]:
session_counts = (
    df.groupby(["participant", "session"])
    .size()
    .unstack(fill_value=0)
)

session_counts.columns = [
    f"session_{col}_count" for col in session_counts.columns
]

session_counts["difference"] = abs(
    session_counts["session_1_count"]
    - session_counts["session_2_count"]
)

print("Participants with the largest differences between sessions:")

display(
    session_counts.sort_values(
        "difference", ascending=False
    ).head(15)
)

Participants with the largest differences between sessions:

             session_1_count  session_2_count  difference
participant
p004                    4700               38        4662
p073                    2992             3655         663
p092                    2742             3280         538
p065                    2917             3392         475
p017                    3037             2628         409
p059                    2773             3166         393
p054                    3330             3002         328
p074                    2944             3248         304
p008                    2474             2754         280
p082                    2915             3189         274
p018                    2623             2891         268
p099                    2762             3023         261
p083                    2644             2891         247
p071                    2890             3127         237
p035                    3107             2872         235

In [82]:
timing_columns = [
    "DU.key1.key1",
    "DD.key1.key2",
    "DU.key1.key2",
    "UD.key1.key2",
    "UU.key1.key2 "
]

# Convert timing columns to numeric values in a separate DataFrame
timing_numeric = df[timing_columns].apply(
    pd.to_numeric,
    errors="coerce"
)

print("Minimum and maximum values of timing features:")
display(timing_numeric.agg(["min", "max"]).T)

print("\nNumber of invalid text values in each timing column:")
display(
    (
        df[timing_columns].notna()
        & timing_numeric.isna()
    ).sum()
)

Minimum and maximum values of timing features:

                   min       max
DU.key1.key1     0.000   568.570
DD.key1.key2  -568.083  1712.727
DU.key1.key2    -7.935  1713.061
UD.key1.key2  -568.162  1712.648
UU.key1.key2   -10.782  1712.982

Number of invalid text values in each timing column:

DU.key1.key1     13
DD.key1.key2      0
DU.key1.key2      0
UD.key1.key2      0
UU.key1.key2      0
dtype: int64

In [83]:
negative_mask = (timing_numeric < 0).any(axis=1)

print("Rows with at least one negative timing value:")
print(negative_mask.sum())

print("\nExamples of rows with negative timing values:")

display(
    df.loc[
        negative_mask,
        ["participant", "session", "key1", "key2"]
    ].join(
        timing_numeric.loc[negative_mask]
    ).head(20)
)

Rows with at least one negative timing value:
97929

Examples of rows with negative timing values:

,participant,session,key1,key2,DU.key1.key1,DD.key1.key2,DU.key1.key2,UD.key1.key2,UU.key1.key2
0,p001,1,W,Shift,0.150,-0.796,0.166,-0.946,0.016
14,p001,1,a,t,0.150,0.134,0.198,-0.016,0.048
24,p001,1,c,h,0.128,0.120,0.184,-0.008,0.056
26,p001,1,a,n,0.184,0.134,0.216,-0.050,0.032
33,p001,1,e,Space,0.112,0.097,0.184,-0.015,0.072
37,p001,1,i,n,0.159,0.088,0.207,-0.071,0.048
44,p001,1,o,u,0.152,0.064,0.192,-0.088,0.040
45,p001,1,u,n,0.128,0.097,0.168,-0.031,0.040
57,p001,1,c,o,0.095,0.090,0.159,-0.005,0.064
63,p001,1,c,e,0.176,0.128,0.242,-0.048,0.066
66,p001,1,w,i,0.131,0.086,0.168,-0.045,0.037
71,p001,1,o,u,0.128,0.088,0.160,-0.040,0.032
75,p001,1,d,e,0.168,0.137,0.217,-0.031,0.049
77,p001,1,s,i,0.142,0.096,0.167,-0.046,0.025
134,p001,1,o,u,0.124,0.085,0.164,-0.039,0.040
137,p001,1,a,b,0.148,0.136,0.199,-0.012,0.051
142,p001,1,o,u,0.113,0.081,0.167,-0.032,0.054
146,p001,1,o,m,0.117,0.076,0.163,-0.041,0.046
151,p001,1,W,Shift,0.136,-0.152,0.152,-0.288,0.016
155,p001,1,d,o,0.144,0.112,0.223,-0.032,0.079

In [84]:
missing_rows = df[
    df[
        [
            "key2",
            "DD.key1.key2",
            "DU.key1.key2",
            "UD.key1.key2",
            "UU.key1.key2 "
        ]
    ].isna().all(axis=1)
]

print("Missing rows:", len(missing_rows))

print("\nMissing rows per participant-session:")
display(
    missing_rows.groupby(["participant", "session"])
    .size()
    .value_counts()
    .sort_index()
)

Missing rows: 198

Missing rows per participant-session:

1    198
Name: count, dtype: int64

In [85]:
# Find the last row of every participant-session group
last_rows = df.groupby(
    ["participant", "session"],
    sort=False
).tail(1)

print("Total final rows:")
print(len(last_rows))

print("\nFinal rows with missing key2:")
print(last_rows["key2"].isna().sum())

print("\nFinal rows with all timing-pair fields missing:")
display(
    last_rows[
        [
            "participant",
            "session",
            "key1",
            "key2",
            "DD.key1.key2",
            "DU.key1.key2",
            "UD.key1.key2",
            "UU.key1.key2 "
        ]
    ].head(15)
)

Total final rows:
198

Final rows with missing key2:
198

Final rows with all timing-pair fields missing:

,participant,session,key1,key2,DD.key1.key2,DU.key1.key2,UD.key1.key2,UU.key1.key2
2513,p001,1,e,NaN,NaN,NaN,NaN,NaN
5257,p001,2,s,NaN,NaN,NaN,NaN,NaN
7959,p002,1,e,NaN,NaN,NaN,NaN,NaN
10774,p002,2,s,NaN,NaN,NaN,NaN,NaN
13367,p003,1,e,NaN,NaN,NaN,NaN,NaN
16085,p003,2,r,NaN,NaN,NaN,NaN,NaN
20785,p004,1,.,NaN,NaN,NaN,NaN,NaN
20823,p004,2,Space,NaN,NaN,NaN,NaN,NaN
24119,p005,1,e,NaN,NaN,NaN,NaN,NaN
27529,p005,2,s,NaN,NaN,NaN,NaN,NaN
30292,p006,1,e,NaN,NaN,NaN,NaN,NaN
33173,p006,2,r,NaN,NaN,NaN,NaN,NaN
35738,p007,1,e,NaN,NaN,NaN,NaN,NaN
38463,p007,2,s,NaN,NaN,NaN,NaN,NaN
40937,p008,1,Space,NaN,NaN,NaN,NaN,NaN

In [86]:
# Step 3.2: Inspect rows with values in Unnamed: 9

suspicious_rows = df[df["Unnamed: 9"].notna()]

print("Number of suspicious rows:")
print(len(suspicious_rows))

print("\nSuspicious rows:")
display(suspicious_rows)

Number of suspicious rows:
13

Suspicious rows:

,participant,session,key1,key2,DU.key1.key1,DD.key1.key2,DU.key1.key2,UD.key1.key2,UU.key1.key2,Unnamed: 9
23481,p005,1,2,",0.087,1.088,1.183,1.001,1.096,\np005,1,",Shift,0.095,-0.472,0.280,-0.567,0.185
169381,p031,1,Backspace,",0.081,0.761,0.896,0.68,0.815,\np031,1,",Shift,0.135,-0.341,0.177,-0.476,0.042
177980,p033,1,e,",0.088,0.2,0.28,0.112,0.192\np033,1,",Backspace,0.080,0.400,0.544,0.320,0.464
181842,p033,2,t,",0.079,0.184,0.263,0.105,0.184,\np033,2,",Shift,0.079,-0.041,0.151,-0.120,0.072
204716,p037,2,Backspace,",0.134,0.281,0.502,0.147,0.368,\np037,2,",Backspace,0.221,0.342,0.501,0.121,0.280
205245,p037,2,Backspace,",0.166,0.569,0.726,0.403,0.56,\np037,2,",Backspace,0.157,0.319,0.502,0.162,0.345
306776,p055,1,Backspace,",0.123,0.785,0.87,0.662,0.747,\np055,1,",Shift,0.085,-0.168,0.150,-0.253,0.065
319078,p057,1,y,",0.137,0.304,0.49,0.167,0.353,\np057,1,",Shift,0.186,-0.047,0.517,-0.233,0.331
491603,p087,1,Backspace,",0.096,6.082,6.177,5.986,6.081,\np087,1,",Shift,0.095,-0.289,0.159,-0.384,0.064
491610,p087,1,Shift,",0.472,1.76,1.888,1.288,1.416,\np087,1,",Shift,0.128,-0.352,0.248,-0.480,0.120
491613,p087,1,Backspace,",0.096,0.8,0.896,0.704,0.8,\np087,1,",Shift,0.096,-0.192,0.288,-0.288,0.192
552060,p099,1,Shift,",0.0,0.06,0.229,0.06,0.229,\np099,1,",Shift,0.169,-0.029,0.423,-0.198,0.254
552098,p099,1,Shift,",0.0,0.033,0.192,0.033,0.192,\np099,1,",Shift,0.159,-0.002,0.487,-0.161,0.328

In [87]:
# Step 3.3: Inspect the original CSV around a suspicious row

from pathlib import Path

raw_file = Path("../data/raw/free-text.csv")

print("File exists:", raw_file.exists())
print("File path:", raw_file.resolve())

with open(raw_file, "r", encoding="utf-8", errors="replace") as file:
    lines = file.readlines()

print("\nTotal physical lines in the file:", len(lines))

# Inspect the area around the first suspicious DataFrame row.
# DataFrame index 23481 is not necessarily the physical line number,
# so this is only an initial location to investigate.
start = 23475
end = 23490

print("\nRaw file lines around the approximate location:")
for line_number in range(start, min(end, len(lines))):
    print(f"Line {line_number + 1}: {lines[line_number]!r}")

File exists: True
File path: C:\Users\LOQ\OneDrive\Desktop\Komal_clg\5th sem\DL Lab\Project\DeepKey_DL_Project\data\raw\free-text.csv

Total physical lines in the file: 562597

Raw file lines around the approximate location:
Line 23476: 'p005,1,t,h,0.12,0.16,0.24,0.04,0.12,\n'
Line 23477: 'p005,1,h,Backspace,0.08,0.464,0.536,0.384,0.456,\n'
Line 23478: 'p005,1,Backspace,c,0.072,0.12,0.256,0.048,0.184,\n'
Line 23479: 'p005,1,c,h,0.136,0.417,0.52,0.281,0.384,\n'
Line 23480: 'p005,1,h,-,0.103,0.608,0.711,0.505,0.608,\n'
Line 23481: 'p005,1,-,2,0.103,1,1.103,0.897,1,\n'
Line 23482: 'p005,1,2,2,0.103,0.192,0.279,0.089,0.176,\n'
Line 23483: 'p005,1,2,",0.087,1.088,1.183,1.001,1.096,\n'
Line 23484: 'p005,1,",Shift,0.095,-0.472,0.28,-0.567,0.185\n'
Line 23485: 'p005,1,Shift,Backspace,0.752,1.208,1.272,0.456,0.52,\n'
Line 23486: 'p005,1,Backspace,:,0.064,0.336,0.408,0.272,0.344,\n'
Line 23487: 'p005,1,:,Shift,0.072,-0.224,0.216,-0.296,0.144,\n'
Line 23488: 'p005,1,Shift,Space,0.44,0.8,0.96,0.36,0.52,\n'
Line 23489: 'p005,1,Space,a,0.16,0.296,0.4,0.136,0.24,\n'
Line 23490: 'p005,1,a,l,0.104,0.136,0.2,0.032,0.096,\n'

In [88]:
# Step 3.4: Compare normal and suspicious raw records

with open(raw_file, "r", encoding="utf-8", errors="replace") as file:
    for line_number, line in enumerate(file, start=1):

        if line_number in [23476, 23483, 23484, 23485]:
            print(f"\nPhysical line {line_number}")
            print("Raw record:", repr(line))
            print("Number of comma-separated fields:", len(line.rstrip("\n").split(",")))
            print("Fields:", line.rstrip("\n").split(","))

Physical line 23476
Raw record: 'p005,1,t,h,0.12,0.16,0.24,0.04,0.12,\n'
Number of comma-separated fields: 10
Fields: ['p005', '1', 't', 'h', '0.12', '0.16', '0.24', '0.04', '0.12', '']

Physical line 23483
Raw record: 'p005,1,2,",0.087,1.088,1.183,1.001,1.096,\n'
Number of comma-separated fields: 10
Fields: ['p005', '1', '2', '"', '0.087', '1.088', '1.183', '1.001', '1.096', '']

Physical line 23484
Raw record: 'p005,1,",Shift,0.095,-0.472,0.28,-0.567,0.185\n'
Number of comma-separated fields: 9
Fields: ['p005', '1', '"', 'Shift', '0.095', '-0.472', '0.28', '-0.567', '0.185']

Physical line 23485
Raw record: 'p005,1,Shift,Backspace,0.752,1.208,1.272,0.456,0.52,\n'
Number of comma-separated fields: 10
Fields: ['p005', '1', 'Shift', 'Backspace', '0.752', '1.208', '1.272', '0.456', '0.52', '']

In [89]:
# Step 3.5: Check the number of fields in every physical line

from collections import Counter

field_counts = Counter()
unusual_lines = []

with open(raw_file, "r", encoding="utf-8", errors="replace") as file:
    for line_number, line in enumerate(file, start=1):

        number_of_fields = len(line.rstrip("\r\n").split(","))

        field_counts[number_of_fields] += 1

        if number_of_fields != 10:
            unusual_lines.append(
                (line_number, number_of_fields, line.rstrip("\r\n"))
            )

print("Field-count distribution:")
print(dict(sorted(field_counts.items())))

print("\nTotal physical lines with a field count other than 10:")
print(len(unusual_lines))

print("\nFirst 20 unusual lines:")
for line_number, number_of_fields, content in unusual_lines[:20]:
    print(
        f"Line {line_number}: "
        f"{number_of_fields} fields | {content!r}"
    )

Field-count distribution:
{9: 14, 10: 551053, 11: 11514, 12: 16}

Total physical lines with a field count other than 10:
11544

First 20 unusual lines:
Line 315: 11 fields | 'p001,1,s,",",0.154,1.639,1.753,1.485,1.599,'
Line 316: 11 fields | 'p001,1,",",Space,0.114,0.066,0.168,-0.048,0.054,'
Line 484: 11 fields | 'p001,1,e,",",0.123,2.1,2.232,1.977,2.109,'
Line 485: 11 fields | 'p001,1,",",Space,0.132,0.12,0.195,-0.012,0.063,'
Line 526: 11 fields | 'p001,1,o,",",0.078,0.4,0.575,0.322,0.497,'
Line 527: 11 fields | 'p001,1,",",Space,0.175,1.119,1.206,0.944,1.031,'
Line 570: 11 fields | 'p001,1,t,",",0.091,1.756,1.899,1.665,1.808,'
Line 571: 11 fields | 'p001,1,",",Space,0.143,0.104,0.2,-0.039,0.057,'
Line 590: 11 fields | 'p001,1,t,",",0.088,1.096,1.256,1.008,1.168,'
Line 591: 11 fields | 'p001,1,",",Space,0.16,0.156,0.248,-0.004,0.088,'
Line 667: 11 fields | 'p001,1,t,",",0.063,0.816,0.92,0.753,0.857,'
Line 668: 11 fields | 'p001,1,",",Space,0.104,0.088,0.167,-0.016,0.063,'
Line 689: 11 fields | 'p001,1,t,",",0.07,0.424,0.574,0.354,0.504,'
Line 690: 11 fields | 'p001,1,",",Space,0.15,0.328,0.406,0.178,0.256,'
Line 1162: 11 fields | 'p001,1,f,",",0.103,0.256,0.36,0.153,0.257,'
Line 1163: 11 fields | 'p001,1,",",Space,0.104,0.184,0.287,0.08,0.183,'
Line 1350: 11 fields | 'p001,1,t,",",0.071,1.36,1.495,1.289,1.424,'
Line 1351: 11 fields | 'p001,1,",",Space,0.135,0.128,0.223,-0.007,0.088,'
Line 1443: 11 fields | 'p001,1,d,",",0.136,1.292,1.408,1.156,1.272,'
Line 1444: 11 fields | 'p001,1,",",Space,0.116,0.332,0.421,0.216,0.305,'

In [90]:
# Step 3.6: Inspect records using Python's CSV parser

import csv
from collections import Counter

csv_field_counts = Counter()
csv_unusual_records = []

with open(
    raw_file,
    "r",
    encoding="utf-8",
    errors="replace",
    newline=""
) as file:

    reader = csv.reader(file)

    for record_number, row in enumerate(reader, start=1):

        csv_field_counts[len(row)] += 1

        if len(row) != 10:
            csv_unusual_records.append(
                (record_number, len(row), row)
            )

print("CSV parser field-count distribution:")
print(dict(sorted(csv_field_counts.items())))

print("\nTotal records with a field count other than 10:")
print(len(csv_unusual_records))

print("\nFirst 15 unusual records:")

for record_number, field_count, row in csv_unusual_records[:15]:
    print(f"\nRecord {record_number}: {field_count} fields")
    print(row)

CSV parser field-count distribution:
{10: 562584}

Total records with a field count other than 10:
0

First 15 unusual records:

In [91]:
# Step 3.7: Compare CSV records with the pandas DataFrame

import csv

with open(
    raw_file,
    "r",
    encoding="utf-8",
    errors="replace",
    newline=""
) as file:

    reader = csv.reader(file)

    header = next(reader)
    total_data_records = sum(1 for _ in reader)

print("CSV header:")
print(header)

print("\nNumber of columns in CSV header:")
print(len(header))

print("\nNumber of data records according to CSV parser:")
print(total_data_records)

print("\nNumber of rows in pandas DataFrame:")
print(len(df))

print("\nNumber of columns in pandas DataFrame:")
print(len(df.columns))

print("\nDo the record counts match?")
print(total_data_records == len(df))

CSV header:
['participant', 'session', 'key1', 'key2', 'DU.key1.key1', 'DD.key1.key2', 'DU.key1.key2', 'UD.key1.key2', 'UU.key1.key2 ', '']

Number of columns in CSV header:
10

Number of data records according to CSV parser:
562583

Number of rows in pandas DataFrame:
562583

Number of columns in pandas DataFrame:
10

Do the record counts match?
True

In [92]:
# Step 3.8: Inspect the suspicious records using csv.reader

import csv

suspicious_indices = df.index[df["Unnamed: 9"].notna()].tolist()

print("Number of suspicious DataFrame rows:", len(suspicious_indices))
print("First 13 suspicious DataFrame indices:", suspicious_indices)

# Read all logical records using the CSV parser
with open(
    raw_file,
    "r",
    encoding="utf-8",
    errors="replace",
    newline=""
) as file:

    reader = csv.reader(file)
    header = next(reader)
    records = list(reader)

print("\nComparing the first 3 suspicious records:\n")

for idx in suspicious_indices[:3]:
    print("=" * 70)
    print("DataFrame index:", idx)

    print("\nPandas interpretation:")
    display(df.loc[[idx]])

    print("\nCSV parser interpretation:")
    print(records[idx])
    print("Number of fields:", len(records[idx]))

Number of suspicious DataFrame rows: 13
First 13 suspicious DataFrame indices: [23481, 169381, 177980, 181842, 204716, 205245, 306776, 319078, 491603, 491610, 491613, 552060, 552098]

Comparing the first 3 suspicious records:

======================================================================
DataFrame index: 23481

Pandas interpretation:

,participant,session,key1,key2,DU.key1.key1,DD.key1.key2,DU.key1.key2,UD.key1.key2,UU.key1.key2,Unnamed: 9
23481,p005,1,2,",0.087,1.088,1.183,1.001,1.096,\np005,1,",Shift,0.095,-0.472,0.28,-0.567,0.185

CSV parser interpretation:
['p005', '1', '2', ',0.087,1.088,1.183,1.001,1.096,\np005,1,', 'Shift', '0.095', '-0.472', '0.28', '-0.567', '0.185']
Number of fields: 10
======================================================================
DataFrame index: 169381

Pandas interpretation:

,participant,session,key1,key2,DU.key1.key1,DD.key1.key2,DU.key1.key2,UD.key1.key2,UU.key1.key2,Unnamed: 9
169381,p031,1,Backspace,",0.081,0.761,0.896,0.68,0.815,\np031,1,",Shift,0.135,-0.341,0.177,-0.476,0.042

CSV parser interpretation:
['p031', '1', 'Backspace', ',0.081,0.761,0.896,0.68,0.815,\np031,1,', 'Shift', '0.135', '-0.341', '0.177', '-0.476', '0.042']
Number of fields: 10
======================================================================
DataFrame index: 177980

Pandas interpretation:

,participant,session,key1,key2,DU.key1.key1,DD.key1.key2,DU.key1.key2,UD.key1.key2,UU.key1.key2,Unnamed: 9
177980,p033,1,e,",0.088,0.2,0.28,0.112,0.192\np033,1,",Backspace,0.08,0.4,0.544,0.32,0.464

CSV parser interpretation:
['p033', '1', 'e', ',0.088,0.2,0.28,0.112,0.192\np033,1,', 'Backspace', '0.08', '0.4', '0.544', '0.32', '0.464']
Number of fields: 10

In [93]:
# Step 3.9: Examine all suspicious key2 values

for idx in suspicious_indices:
    row = df.loc[idx]

    print("=" * 70)
    print("DataFrame index:", idx)
    print("Participant:", row["participant"])
    print("Session:", row["session"])
    print("key1:", repr(row["key1"]))
    print("key2:", repr(row["key2"]))
    print("DU.key1.key1:", repr(row["DU.key1.key1"]))
    print("Unnamed: 9:", repr(row["Unnamed: 9"]))

======================================================================
DataFrame index: 23481
Participant: p005
Session: 1
key1: '2'
key2: ',0.087,1.088,1.183,1.001,1.096,\np005,1,'
DU.key1.key1: 'Shift'
Unnamed: 9: np.float64(0.185)
======================================================================
DataFrame index: 169381
Participant: p031
Session: 1
key1: 'Backspace'
key2: ',0.081,0.761,0.896,0.68,0.815,\np031,1,'
DU.key1.key1: 'Shift'
Unnamed: 9: np.float64(0.042)
======================================================================
DataFrame index: 177980
Participant: p033
Session: 1
key1: 'e'
key2: ',0.088,0.2,0.28,0.112,0.192\np033,1,'
DU.key1.key1: 'Backspace'
Unnamed: 9: np.float64(0.464)
======================================================================
DataFrame index: 181842
Participant: p033
Session: 2
key1: 't'
key2: ',0.079,0.184,0.263,0.105,0.184,\np033,2,'
DU.key1.key1: 'Shift'
Unnamed: 9: np.float64(0.072)
======================================================================
DataFrame index: 204716
Participant: p037
Session: 2
key1: 'Backspace'
key2: ',0.134,0.281,0.502,0.147,0.368,\np037,2,'
DU.key1.key1: 'Backspace'
Unnamed: 9: np.float64(0.28)
======================================================================
DataFrame index: 205245
Participant: p037
Session: 2
key1: 'Backspace'
key2: ',0.166,0.569,0.726,0.403,0.56,\np037,2,'
DU.key1.key1: 'Backspace'
Unnamed: 9: np.float64(0.345)
======================================================================
DataFrame index: 306776
Participant: p055
Session: 1
key1: 'Backspace'
key2: ',0.123,0.785,0.87,0.662,0.747,\np055,1,'
DU.key1.key1: 'Shift'
Unnamed: 9: np.float64(0.065)
======================================================================
DataFrame index: 319078
Participant: p057
Session: 1
key1: 'y'
key2: ',0.137,0.304,0.49,0.167,0.353,\np057,1,'
DU.key1.key1: 'Shift'
Unnamed: 9: np.float64(0.331)
======================================================================
DataFrame index: 491603
Participant: p087
Session: 1
key1: 'Backspace'
key2: ',0.096,6.082,6.177,5.986,6.081,\np087,1,'
DU.key1.key1: 'Shift'
Unnamed: 9: np.float64(0.064)
======================================================================
DataFrame index: 491610
Participant: p087
Session: 1
key1: 'Shift'
key2: ',0.472,1.76,1.888,1.288,1.416,\np087,1,'
DU.key1.key1: 'Shift'
Unnamed: 9: np.float64(0.12)
======================================================================
DataFrame index: 491613
Participant: p087
Session: 1
key1: 'Backspace'
key2: ',0.096,0.8,0.896,0.704,0.8,\np087,1,'
DU.key1.key1: 'Shift'
Unnamed: 9: np.float64(0.192)
======================================================================
DataFrame index: 552060
Participant: p099
Session: 1
key1: 'Shift'
key2: ',0.0,0.06,0.229,0.06,0.229,\np099,1,'
DU.key1.key1: 'Shift'
Unnamed: 9: np.float64(0.254)
======================================================================
DataFrame index: 552098
Participant: p099
Session: 1
key1: 'Shift'
key2: ',0.0,0.033,0.192,0.033,0.192,\np099,1,'
DU.key1.key1: 'Shift'
Unnamed: 9: np.float64(0.328)

In [94]:
# Step 3.10: Find newline characters inside key2

newline_mask = df["key2"].astype(str).str.contains(
    "\n",
    regex=False,
    na=False
)

print("Rows with a newline inside key2:")
print(newline_mask.sum())

print("\nRows with a newline inside key2 and a non-missing Unnamed: 9:")
print(
    (
        newline_mask
        & df["Unnamed: 9"].notna()
    ).sum()
)

print("\nExamples of rows containing newlines:")
display(
    df.loc[
        newline_mask,
        [
            "participant",
            "session",
            "key1",
            "key2",
            "DU.key1.key1",
            "Unnamed: 9"
        ]
    ].head(10)
)

Rows with a newline inside key2:
13

Rows with a newline inside key2 and a non-missing Unnamed: 9:
13

Examples of rows containing newlines:

,participant,session,key1,key2,DU.key1.key1,Unnamed: 9
23481,p005,1,2,",0.087,1.088,1.183,1.001,1.096,\np005,1,",Shift,0.185
169381,p031,1,Backspace,",0.081,0.761,0.896,0.68,0.815,\np031,1,",Shift,0.042
177980,p033,1,e,",0.088,0.2,0.28,0.112,0.192\np033,1,",Backspace,0.464
181842,p033,2,t,",0.079,0.184,0.263,0.105,0.184,\np033,2,",Shift,0.072
204716,p037,2,Backspace,",0.134,0.281,0.502,0.147,0.368,\np037,2,",Backspace,0.280
205245,p037,2,Backspace,",0.166,0.569,0.726,0.403,0.56,\np037,2,",Backspace,0.345
306776,p055,1,Backspace,",0.123,0.785,0.87,0.662,0.747,\np055,1,",Shift,0.065
319078,p057,1,y,",0.137,0.304,0.49,0.167,0.353,\np057,1,",Shift,0.331
491603,p087,1,Backspace,",0.096,6.082,6.177,5.986,6.081,\np087,1,",Shift,0.064
491610,p087,1,Shift,",0.472,1.76,1.888,1.288,1.416,\np087,1,",Shift,0.120

In [95]:
# Step 3.11: Inspect neighbouring lines in the original CSV

suspicious_line_numbers = [
    23483,
    169383,
    177982,
    181844,
    204718,
    205247,
    306778,
    319080,
    491605,
    491612,
    491615,
    552062,
    552100
]

with open(raw_file, "r", encoding="utf-8", errors="replace") as file:
    raw_lines = file.readlines()

for line_number in suspicious_line_numbers:
    print("\n" + "=" * 80)
    print(f"Inspecting around physical line {line_number}")

    start = max(0, line_number - 3)
    end = min(len(raw_lines), line_number + 2)

    for i in range(start, end):
        print(f"Line {i + 1}: {raw_lines[i]!r}")

================================================================================
Inspecting around physical line 23483
Line 23481: 'p005,1,-,2,0.103,1,1.103,0.897,1,\n'
Line 23482: 'p005,1,2,2,0.103,0.192,0.279,0.089,0.176,\n'
Line 23483: 'p005,1,2,",0.087,1.088,1.183,1.001,1.096,\n'
Line 23484: 'p005,1,",Shift,0.095,-0.472,0.28,-0.567,0.185\n'
Line 23485: 'p005,1,Shift,Backspace,0.752,1.208,1.272,0.456,0.52,\n'

================================================================================
Inspecting around physical line 169383
Line 169381: 'p031,1,2,Shift,0.077,0.807,1.135,0.73,1.058,\n'
Line 169382: 'p031,1,Shift,;,0.328,0.472,0.567,0.144,0.239,\n'
Line 169383: 'p031,1,;,Backspace,0.095,0.788,0.869,0.693,0.774,\n'
Line 169384: 'p031,1,Backspace,",0.081,0.761,0.896,0.68,0.815,\n'
Line 169385: 'p031,1,",Shift,0.135,-0.341,0.177,-0.476,0.042\n'

================================================================================
Inspecting around physical line 177982
Line 177980: 'p033,1,b,l,0.017,0.064,0.144,0.047,0.127,\n'
Line 177981: 'p033,1,l,Backspace,0.08,0.224,0.305,0.144,0.225,\n'
Line 177982: 'p033,1,Backspace,l,0.081,0.352,0.432,0.271,0.351,\n'
Line 177983: 'p033,1,l,e,0.08,0.056,0.144,-0.024,0.064,\n'
Line 177984: 'p033,1,e,",0.088,0.2,0.28,0.112,0.192\n'

================================================================================
Inspecting around physical line 181844
Line 181842: 'p033,2,o,u,0.08,0.16,0.233,0.08,0.153,\n'
Line 181843: 'p033,2,u,t,0.073,0.064,0.152,-0.009,0.079,\n'
Line 181844: 'p033,2,t,Space,0.088,0.064,0.192,-0.024,0.104,\n'
Line 181845: 'p033,2,Space,i,0.128,0.104,0.192,-0.024,0.064,\n'
Line 181846: 'p033,2,i,t,0.088,0.041,0.12,-0.047,0.032,\n'

================================================================================
Inspecting around physical line 204718
Line 204716: 'p037,2,t,!,0.077,1.255,1.454,1.178,1.377,\n'
Line 204717: 'p037,2,!,Delete,0.199,0.688,0.846,0.489,0.647,\n'
Line 204718: 'p037,2,Delete,Shift,0.158,-0.968,0.825,-1.126,0.667,\n'
Line 204719: 'p037,2,Shift,Backspace,1.793,2.121,2.255,0.328,0.462,\n'
Line 204720: 'p037,2,Backspace,_,0.134,0.559,0.758,0.425,0.624,\n'

================================================================================
Inspecting around physical line 205247
Line 205245: 'p037,2,o,Backspace,0.12,0.317,0.43,0.197,0.31,\n'
Line 205246: 'p037,2,Backspace,Backspace,0.113,0.179,0.274,0.066,0.161,\n'
Line 205247: 'p037,2,Backspace,w,0.095,0.169,0.287,0.074,0.192,\n'
Line 205248: 'p037,2,w,o,0.118,0.552,0.766,0.434,0.648,\n'
Line 205249: 'p037,2,o,n,0.214,0.743,0.822,0.529,0.608,\n'

================================================================================
Inspecting around physical line 306778
Line 306776: 'p055,1,o,u,0.174,0.114,0.208,-0.06,0.034,\n'
Line 306777: 'p055,1,u,r,0.094,0.129,0.292,0.035,0.198,\n'
Line 306778: 'p055,1,r,a,0.163,0.129,0.247,-0.034,0.084,\n'
Line 306779: 'p055,1,a,b,0.118,0.254,0.364,0.136,0.246,\n'
Line 306780: 'p055,1,b,l,0.11,0.153,0.264,0.043,0.154,\n'

================================================================================
Inspecting around physical line 319080
Line 319078: 'p057,1,Space,w,0.144,0.084,0.223,-0.06,0.079,\n'
Line 319079: 'p057,1,w,h,0.139,0.211,0.344,0.072,0.205,\n'
Line 319080: 'p057,1,h,e,0.133,0.08,0.218,-0.053,0.085,\n'
Line 319081: 'p057,1,e,n,0.138,0.049,0.154,-0.089,0.016,\n'
Line 319082: 'p057,1,n,Space,0.105,0.162,0.294,0.057,0.189,\n'

================================================================================
Inspecting around physical line 491605
Line 491603: 'p087,1,y,`,0.096,1.121,1.177,1.025,1.081,\n'
Line 491604: 'p087,1,`,r,0.056,0.544,0.672,0.488,0.616,\n'
Line 491605: 'p087,1,r,e,0.128,0.128,0.216,0,0.088,\n'
Line 491606: 'p087,1,e,Backspace,0.088,0.448,0.6,0.36,0.512,\n'
Line 491607: 'p087,1,Backspace,Backspace,0.152,0.32,0.408,0.168,0.256,\n'

================================================================================
Inspecting around physical line 491612
Line 491610: 'p087,1,",",Backspace,0.096,0.64,0.736,0.544,0.64,\n'
Line 491611: 'p087,1,Backspace,`,0.096,1.28,1.376,1.184,1.28,\n'
Line 491612: 'p087,1,`,Backspace,0.096,0.608,0.704,0.512,0.608,\n'
Line 491613: 'p087,1,Backspace,",0.096,6.082,6.177,5.986,6.081,\n'
Line 491614: 'p087,1,",Shift,0.095,-0.289,0.159,-0.384,0.064\n'

================================================================================
Inspecting around physical line 491615
Line 491613: 'p087,1,Backspace,",0.096,6.082,6.177,5.986,6.081,\n'
Line 491614: 'p087,1,",Shift,0.095,-0.289,0.159,-0.384,0.064\n'
Line 491615: 'p087,1,Shift,Insert,0.448,1.088,1.184,0.64,0.736,\n'
Line 491616: 'p087,1,Insert,Backspace,0.096,1.569,1.664,1.473,1.568,\n'
Line 491617: 'p087,1,Backspace,`,0.095,1.887,1.983,1.792,1.888,\n'

================================================================================
Inspecting around physical line 552062
Line 552060: 'p099,1,t,.,0.091,1.22,1.295,1.129,1.204,\n'
Line 552061: 'p099,1,.,Space,0.075,0.205,0.289,0.13,0.214,\n'
Line 552062: 'p099,1,Space,CapsLock,0.084,0.141,0.229,0.057,0.145,\n'
Line 552063: 'p099,1,CapsLock,B,0.088,0.122,0.191,0.034,0.103,\n'
Line 552064: 'p099,1,B,CapsLock,0.069,0.062,0.174,-0.007,0.105,\n'

================================================================================
Inspecting around physical line 552100
Line 552098: 'p099,1,Space,i,0.085,0.527,0.601,0.442,0.516,\n'
Line 552099: 'p099,1,i,n,0.074,0.362,0.434,0.288,0.36,\n'
Line 552100: 'p099,1,n,Backspace,0.072,0.764,0.862,0.692,0.79,\n'
Line 552101: 'p099,1,Backspace,s,0.098,0.162,0.284,0.064,0.186,\n'
Line 552102: 'p099,1,s,n,0.122,0.682,0.75,0.56,0.628,\n'

In [96]:
# Step 3.12: Display the complete suspicious logical records

import csv

with open(
    raw_file,
    "r",
    encoding="utf-8",
    errors="replace",
    newline=""
) as file:

    reader = csv.reader(file)
    header = next(reader)

    for record_number, row in enumerate(reader, start=1):
        if any("\n" in field for field in row):
            print("\n" + "=" * 70)
            print("Logical record number:", record_number)
            print("Number of fields:", len(row))

            for column_name, value in zip(header, row):
                if "\n" in value or column_name == "":
                    print(f"{column_name!r}: {value!r}")

======================================================================
Logical record number: 23482
Number of fields: 10
'key2': ',0.087,1.088,1.183,1.001,1.096,\np005,1,'
'': '0.185'

======================================================================
Logical record number: 169382
Number of fields: 10
'key2': ',0.081,0.761,0.896,0.68,0.815,\np031,1,'
'': '0.042'

======================================================================
Logical record number: 177981
Number of fields: 10
'key2': ',0.088,0.2,0.28,0.112,0.192\np033,1,'
'': '0.464'

======================================================================
Logical record number: 181843
Number of fields: 10
'key2': ',0.079,0.184,0.263,0.105,0.184,\np033,2,'
'': '0.072'

======================================================================
Logical record number: 204717
Number of fields: 10
'key2': ',0.134,0.281,0.502,0.147,0.368,\np037,2,'
'': '0.28'

======================================================================
Logical record number: 205246
Number of fields: 10
'key2': ',0.166,0.569,0.726,0.403,0.56,\np037,2,'
'': '0.345'

======================================================================
Logical record number: 306777
Number of fields: 10
'key2': ',0.123,0.785,0.87,0.662,0.747,\np055,1,'
'': '0.065'

======================================================================
Logical record number: 319079
Number of fields: 10
'key2': ',0.137,0.304,0.49,0.167,0.353,\np057,1,'
'': '0.331'

======================================================================
Logical record number: 491604
Number of fields: 10
'key2': ',0.096,6.082,6.177,5.986,6.081,\np087,1,'
'': '0.064'

======================================================================
Logical record number: 491611
Number of fields: 10
'key2': ',0.472,1.76,1.888,1.288,1.416,\np087,1,'
'': '0.12'

======================================================================
Logical record number: 491614
Number of fields: 10
'key2': ',0.096,0.8,0.896,0.704,0.8,\np087,1,'
'': '0.192'

======================================================================
Logical record number: 552061
Number of fields: 10
'key2': ',0.0,0.06,0.229,0.06,0.229,\np099,1,'
'': '0.254'

======================================================================
Logical record number: 552099
Number of fields: 10
'key2': ',0.0,0.033,0.192,0.033,0.192,\np099,1,'
'': '0.328'

In [97]:
# Find rows where key2 contains a newline
# and the unnamed column is not empty

suspicious_rows = df[
    df["key2"].astype(str).str.contains("\n", regex=False)
    & df["Unnamed: 9"].notna()
]

print("Number of suspicious rows:", len(suspicious_rows))

for index, row in suspicious_rows.iterrows():
    print("\n" + "=" * 60)
    print("DataFrame index:", index)
    print("Participant:", row["participant"])
    print("Session:", row["session"])
    print("Key 1:", repr(row["key1"]))
    print("Key 2:", repr(row["key2"]))
    print("DU.key1.key1:", repr(row["DU.key1.key1"]))
    print("DD.key1.key2:", repr(row["DD.key1.key2"]))
    print("DU.key1.key2:", repr(row["DU.key1.key2"]))
    print("UD.key1.key2:", repr(row["UD.key1.key2"]))
    print("UU.key1.key2:", repr(row["UU.key1.key2 "]))
    print("Unnamed column:", repr(row["Unnamed: 9"]))

Number of suspicious rows: 13

============================================================
DataFrame index: 23481
Participant: p005
Session: 1
Key 1: '2'
Key 2: ',0.087,1.088,1.183,1.001,1.096,\np005,1,'
DU.key1.key1: 'Shift'
DD.key1.key2: 0.095
DU.key1.key2: -0.472
UD.key1.key2: 0.28
UU.key1.key2: -0.567
Unnamed column: 0.185

============================================================
DataFrame index: 169381
Participant: p031
Session: 1
Key 1: 'Backspace'
Key 2: ',0.081,0.761,0.896,0.68,0.815,\np031,1,'
DU.key1.key1: 'Shift'
DD.key1.key2: 0.135
DU.key1.key2: -0.341
UD.key1.key2: 0.177
UU.key1.key2: -0.476
Unnamed column: 0.042

============================================================
DataFrame index: 177980
Participant: p033
Session: 1
Key 1: 'e'
Key 2: ',0.088,0.2,0.28,0.112,0.192\np033,1,'
DU.key1.key1: 'Backspace'
DD.key1.key2: 0.08
DU.key1.key2: 0.4
UD.key1.key2: 0.544
UU.key1.key2: 0.32
Unnamed column: 0.464

============================================================
DataFrame index: 181842
Participant: p033
Session: 2
Key 1: 't'
Key 2: ',0.079,0.184,0.263,0.105,0.184,\np033,2,'
DU.key1.key1: 'Shift'
DD.key1.key2: 0.079
DU.key1.key2: -0.041
UD.key1.key2: 0.151
UU.key1.key2: -0.12
Unnamed column: 0.072

============================================================
DataFrame index: 204716
Participant: p037
Session: 2
Key 1: 'Backspace'
Key 2: ',0.134,0.281,0.502,0.147,0.368,\np037,2,'
DU.key1.key1: 'Backspace'
DD.key1.key2: 0.221
DU.key1.key2: 0.342
UD.key1.key2: 0.501
UU.key1.key2: 0.121
Unnamed column: 0.28

============================================================
DataFrame index: 205245
Participant: p037
Session: 2
Key 1: 'Backspace'
Key 2: ',0.166,0.569,0.726,0.403,0.56,\np037,2,'
DU.key1.key1: 'Backspace'
DD.key1.key2: 0.157
DU.key1.key2: 0.319
UD.key1.key2: 0.502
UU.key1.key2: 0.162
Unnamed column: 0.345

============================================================
DataFrame index: 306776
Participant: p055
Session: 1
Key 1: 'Backspace'
Key 2: ',0.123,0.785,0.87,0.662,0.747,\np055,1,'
DU.key1.key1: 'Shift'
DD.key1.key2: 0.085
DU.key1.key2: -0.168
UD.key1.key2: 0.15
UU.key1.key2: -0.253
Unnamed column: 0.065

============================================================
DataFrame index: 319078
Participant: p057
Session: 1
Key 1: 'y'
Key 2: ',0.137,0.304,0.49,0.167,0.353,\np057,1,'
DU.key1.key1: 'Shift'
DD.key1.key2: 0.186
DU.key1.key2: -0.047
UD.key1.key2: 0.517
UU.key1.key2: -0.233
Unnamed column: 0.331

============================================================
DataFrame index: 491603
Participant: p087
Session: 1
Key 1: 'Backspace'
Key 2: ',0.096,6.082,6.177,5.986,6.081,\np087,1,'
DU.key1.key1: 'Shift'
DD.key1.key2: 0.095
DU.key1.key2: -0.289
UD.key1.key2: 0.159
UU.key1.key2: -0.384
Unnamed column: 0.064

============================================================
DataFrame index: 491610
Participant: p087
Session: 1
Key 1: 'Shift'
Key 2: ',0.472,1.76,1.888,1.288,1.416,\np087,1,'
DU.key1.key1: 'Shift'
DD.key1.key2: 0.128
DU.key1.key2: -0.352
UD.key1.key2: 0.248
UU.key1.key2: -0.48
Unnamed column: 0.12

============================================================
DataFrame index: 491613
Participant: p087
Session: 1
Key 1: 'Backspace'
Key 2: ',0.096,0.8,0.896,0.704,0.8,\np087,1,'
DU.key1.key1: 'Shift'
DD.key1.key2: 0.096
DU.key1.key2: -0.192
UD.key1.key2: 0.288
UU.key1.key2: -0.288
Unnamed column: 0.192

============================================================
DataFrame index: 552060
Participant: p099
Session: 1
Key 1: 'Shift'
Key 2: ',0.0,0.06,0.229,0.06,0.229,\np099,1,'
DU.key1.key1: 'Shift'
DD.key1.key2: 0.169
DU.key1.key2: -0.029
UD.key1.key2: 0.423
UU.key1.key2: -0.198
Unnamed column: 0.254

============================================================
DataFrame index: 552098
Participant: p099
Session: 1
Key 1: 'Shift'
Key 2: ',0.0,0.033,0.192,0.033,0.192,\np099,1,'
DU.key1.key1: 'Shift'
DD.key1.key2: 0.159
DU.key1.key2: -0.002
UD.key1.key2: 0.487
UU.key1.key2: -0.161
Unnamed column: 0.328

In [98]:
from pathlib import Path

raw_file = Path("../data/raw/free-text.csv")

with open(raw_file, "r", encoding="utf-8", errors="replace") as file:
    lines = file.readlines()

# Display physical lines around the first suspicious record
for i in range(23478, 23487):
    print(f"Line {i + 1}: {lines[i].rstrip()!r}")

Line 23479: 'p005,1,c,h,0.136,0.417,0.52,0.281,0.384,'
Line 23480: 'p005,1,h,-,0.103,0.608,0.711,0.505,0.608,'
Line 23481: 'p005,1,-,2,0.103,1,1.103,0.897,1,'
Line 23482: 'p005,1,2,2,0.103,0.192,0.279,0.089,0.176,'
Line 23483: 'p005,1,2,",0.087,1.088,1.183,1.001,1.096,'
Line 23484: 'p005,1,",Shift,0.095,-0.472,0.28,-0.567,0.185'
Line 23485: 'p005,1,Shift,Backspace,0.752,1.208,1.272,0.456,0.52,'
Line 23486: 'p005,1,Backspace,:,0.064,0.336,0.408,0.272,0.344,'
Line 23487: 'p005,1,:,Shift,0.072,-0.224,0.216,-0.296,0.144,'

In [99]:
# Check how frequently quotation marks appear in key1 and key2

print("Quotation marks in key1:")
print(
    df["key1"]
    .astype(str)
    .str.contains('"', regex=False)
    .sum()
)

print("\nQuotation marks in key2:")
print(
    df["key2"]
    .astype(str)
    .str.contains('"', regex=False)
    .sum()
)

print("\nRows where key1 is a quotation mark:")
print(df[df["key1"].astype(str) == '"'][["participant", "session", "key1", "key2"]].head(10))

print("\nRows where key2 is a quotation mark:")
print(df[df["key2"].astype(str) == '"'][["participant", "session", "key1", "key2"]].head(10))

Quotation marks in key1:
0

Quotation marks in key2:
0

Rows where key1 is a quotation mark:
Empty DataFrame
Columns: [participant, session, key1, key2]
Index: []

Rows where key2 is a quotation mark:
Empty DataFrame
Columns: [participant, session, key1, key2]
Index: []

In [100]:
from pathlib import Path

raw_folder = Path("../data/raw")

print("Files in data/raw:")

for file in sorted(raw_folder.iterdir()):
    if file.is_file():
        print(file.name)

Files in data/raw:
fixed-text.csv
free-text.csv

In [101]:
# Summarize suspicious records by participant and session

suspicious_rows = df[
    df["key2"].astype(str).str.contains("\n", regex=False)
    & df["Unnamed: 9"].notna()
]

print("Total suspicious records:", len(suspicious_rows))

print("\nSuspicious records by session:")
print(suspicious_rows["session"].value_counts().sort_index())

print("\nSuspicious records by participant:")
print(suspicious_rows["participant"].value_counts().sort_index())

print("\nParticipant-session combinations affected:")
print(
    suspicious_rows.groupby(["participant", "session"])
    .size()
    .reset_index(name="suspicious_count")
    .to_string(index=False)
)

Total suspicious records: 13

Suspicious records by session:
session
1    10
2     3
Name: count, dtype: int64

Suspicious records by participant:
participant
p005    1
p031    1
p033    2
p037    2
p055    1
p057    1
p087    3
p099    2
Name: count, dtype: int64

Participant-session combinations affected:
participant  session  suspicious_count
       p005        1                 1
       p031        1                 1
       p033        1                 1
       p033        2                 1
       p037        2                 2
       p055        1                 1
       p057        1                 1
       p087        1                 3
       p099        1                 2

In [102]:
# Inspect the fixed-text dataset

print("Dataset shape:", df_fixed.shape)

print("\nFirst 5 rows:")
display(df_fixed.head())

print("\nData types:")
print(df_fixed.dtypes)

print("\nDuplicate rows:", df_fixed.duplicated().sum())

print("\nNumber of participants:", df_fixed["participant"].nunique())

print("\nSessions:")
print(df_fixed["session"].value_counts().sort_index())

print("\nRepetitions:")
print(df_fixed["repetition"].value_counts().sort_index())

NameError: name 'df_fixed' is not defined

In [ ]:
# 1. Count unique participants
print("Unique participants:", df_fixed["participant"].nunique())

# 2. Count sessions
print("\nUnique sessions:", sorted(df_fixed["session"].unique()))

# 3. Count repetitions
print("\nUnique repetition numbers:", df_fixed["repetition"].nunique())
print("Repetition values:", sorted(df_fixed["repetition"].unique()))

# 4. Count records per participant
print("\nRecords per participant:")
print(df_fixed.groupby("participant").size().describe())

# 5. Count records per session
print("\nRecords per session:")
print(df_fixed["session"].value_counts().sort_index())

# 6. Check duplicate rows
print("\nExact duplicate rows:", df_fixed.duplicated().sum())

# 7. Check missing values
print("\nTotal missing values:", df_fixed.isnull().sum().sum())

Unique participants: 99

Unique sessions: [np.int64(1), np.int64(2)]

Unique repetition numbers: 107
Repetition values: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69), np.int64(70), np.int64(71), np.int64(72), np.int64(73), np.int64(74), np.int64(75), np.int64(76), np.int64(77), np.int64(78), np.int64(79), np.int64(80), np.int64(81), np.int64(82), np.int64(83), np.int64(84), np.int64(85), np.int64(86), np.int64(87), np.int64(88), np.int64(89), np.int64(90), np.int64(91), np.int64(92), np.int64(93), np.int64(94), np.int64(95), np.int64(96), np.int64(97), np.int64(98), np.int64(99), np.int64(100), np.int64(101), np.int64(102), np.int64(103), np.int64(104), np.int64(105), np.int64(106), np.int64(107)]

Records per participant:
count     99.000000
mean     199.717172
std        1.152109
min      194.000000
25%      200.000000
50%      200.000000
75%      200.000000
max      207.000000
dtype: float64

Records per session:
session
1    9878
2    9894
Name: count, dtype: int64

Exact duplicate rows: 0

Total missing values: 0

In [ ]:
# Count records for each participant in each session

records_per_session = (
    df_fixed.groupby(["participant", "session"])
    .size()
    .unstack(fill_value=0)
)

print("Records per participant in each session:")
display(records_per_session.head(10))

print("\nSummary of records per participant-session:")
print(records_per_session.stack().describe())

print("\nMinimum records in a participant-session:")
print(records_per_session.stack().min())

print("\nMaximum records in a participant-session:")
print(records_per_session.stack().max())

print("\nParticipant-session combinations with fewer than 95 records:")
print(records_per_session[records_per_session.min(axis=1) < 95])

Records per participant in each session:

session        1    2
participant
p001         100  100
p002         100  100
p003         100  100
p004         100  100
p005         100  100
p006         100  100
p007         100  100
p008         100  100
p009          99  100
p010         100  100

Summary of records per participant-session:
count    198.000000
mean      99.858586
std        0.760845
min       95.000000
25%      100.000000
50%      100.000000
75%      100.000000
max      107.000000
dtype: float64

Minimum records in a participant-session:
95

Maximum records in a participant-session:
107

Participant-session combinations with fewer than 95 records:
Empty DataFrame
Columns: [1, 2]
Index: []

In [ ]:
# Select numeric timing columns, excluding identifiers
# and the total typing time column

timing_cols_fixed = [
    col for col in df_fixed.select_dtypes(include="number").columns
    if col not in ["session", "repetition", "total time"]
]

print("Number of timing features:", len(timing_cols_fixed))

print("\nTiming-feature summary:")
display(df_fixed[timing_cols_fixed].describe().T)

print("\nNegative values per timing feature:")
print(
    (df_fixed[timing_cols_fixed] < 0)
    .sum()
    .sort_values(ascending=False)
)

print("\nZero values per timing feature:")
print(
    (df_fixed[timing_cols_fixed] == 0)
    .sum()
    .sort_values(ascending=False)
)

Number of timing features: 46

Timing-feature summary:

,count,mean,std,min,25%,50%,75%,max
DU.v.v,19772.0,0.097076,0.030586,0.001,0.07800,0.0930,0.11200,0.965
DD.v.p,19772.0,0.262902,0.609094,-0.061,0.13600,0.1955,0.29100,76.414
DU.v.p,19772.0,0.167657,0.609162,-0.172,0.04100,0.0980,0.20000,76.321
UD.v.p,19772.0,0.359979,0.609240,0.004,0.23200,0.2950,0.38800,76.451
UU.v.p,19772.0,0.264733,0.608517,0.001,0.13900,0.1990,0.29300,76.358
DU.p.p,19772.0,0.095246,0.029670,0.001,0.07500,0.0900,0.11100,0.250
DD.p.w,19772.0,0.405263,0.826127,-6.965,0.17700,0.2650,0.44900,67.362
DU.p.w,19772.0,0.302647,0.826035,-7.064,0.07600,0.1600,0.34900,67.254
UD.p.w,19772.0,0.500509,0.826363,-6.889,0.27400,0.3630,0.54400,67.418
UU.p.w,19772.0,0.397893,0.825646,-6.988,0.17300,0.2550,0.44100,67.310
DU.w.w,19772.0,0.102616,0.031282,0.001,0.08000,0.0980,0.12000,0.448
DD.w.j,19772.0,0.429214,0.553540,-0.073,0.16300,0.2780,0.51700,28.340
DU.w.j,19772.0,0.333512,0.550036,-0.145,0.07500,0.1770,0.41700,28.286
UD.w.j,19772.0,0.531830,0.554719,0.005,0.26700,0.3810,0.62300,28.403
UU.w.j,19772.0,0.436128,0.550271,0.001,0.17900,0.2810,0.52000,28.349
DU.j.j,19772.0,0.095702,0.040909,0.001,0.07000,0.0850,0.11100,0.548
DD.j.k,19772.0,-54.220783,7665.255605,-1077833.670,0.16800,0.2080,0.26700,645.836
DU.j.k,19772.0,-54.319907,7665.255504,-1077833.755,0.07300,0.1180,0.17400,645.724
UD.j.k,19772.0,-54.125081,7665.255795,-1077833.601,0.25300,0.2950,0.35900,645.996
UU.j.k,19772.0,-54.224205,7665.255694,-1077833.686,0.15800,0.1970,0.25700,645.884
DU.k.k,19772.0,0.099124,0.031037,0.001,0.07900,0.0950,0.11400,0.333
DD.k.e,19772.0,0.296460,0.348266,-0.574,0.14200,0.2100,0.32400,16.546
DU.k.e,19772.0,54.705447,7665.252072,-0.478,0.03800,0.0990,0.21900,1077833.851
UD.k.e,19772.0,0.395583,0.350909,-0.489,0.23600,0.3120,0.43200,16.642
UU.k.e,19772.0,54.804570,7665.251972,-0.365,0.13500,0.2010,0.32000,1077833.936
DU.e.e,19772.0,54.617356,7665.256773,0.001,0.08100,0.1000,0.12200,1077834.425
DD.e.u,19772.0,0.231974,0.260189,-0.045,0.12475,0.1700,0.24800,14.724
DU.e.u,19772.0,0.140885,0.258797,-0.111,0.03800,0.0800,0.15300,14.625
UD.e.u,19772.0,-54.177013,7665.258665,-1077834.250,0.22400,0.2780,0.36100,14.871
UU.e.u,19772.0,-54.268101,7665.258571,-1077834.328,0.14000,0.1850,0.26000,14.772
DU.u.u,19772.0,0.091088,0.028891,0.001,0.07100,0.0870,0.10600,0.266
DD.u.r,19772.0,0.226383,0.253015,0.001,0.12800,0.1760,0.24600,20.236
DU.u.r,19772.0,0.130939,0.250923,-0.100,0.03900,0.0800,0.14500,20.157
UD.u.r,19772.0,0.317472,0.256665,0.005,0.21300,0.2690,0.34400,20.335
UU.u.r,19772.0,0.222027,0.252597,0.002,0.12600,0.1730,0.23900,20.256
DU.r.r,19772.0,0.095445,0.028761,0.001,0.07500,0.0920,0.11200,0.321
DD.r.k,19772.0,54.957758,7665.252099,-0.051,0.18200,0.3090,0.56000,1077834.106
DU.r.k,19772.0,54.863237,7665.252138,-0.148,0.08400,0.2090,0.46925,1077834.017
UD.r.k,19772.0,55.053202,7665.252117,0.003,0.27500,0.4090,0.65500,1077834.204
UU.r.k,19772.0,54.958682,7665.252156,0.001,0.18000,0.3090,0.56500,1077834.115
DU.k.k.1,19772.0,0.094520,0.030028,0.001,0.07300,0.0890,0.11100,0.292
DD.k.b,19772.0,-54.225695,7665.254621,-1077833.679,0.15200,0.2260,0.31200,332.701
DU.k.b,19772.0,-54.315447,7665.254658,-1077833.774,0.05700,0.1380,0.22525,332.605
UD.k.b,19772.0,-54.131175,7665.254660,-1077833.590,0.24800,0.3215,0.40800,332.829
UU.k.b,19772.0,-54.220927,7665.254697,-1077833.685,0.15600,0.2320,0.31600,332.733
DU.b.b,19772.0,0.089752,0.042830,0.001,0.07000,0.0850,0.10400,4.573

Negative values per timing feature:
DU.j.k      3480
DU.v.p      1825
DU.k.e      1633
DU.u.r      1150
DU.k.b      1082
DU.e.u      1035
DU.w.j      1032
DU.r.k       393
DU.p.w       368
DD.k.e        26
DD.j.k        25
UD.p.w        24
DD.p.w        24
UU.p.w        24
UU.k.e        23
UD.k.e        12
DD.k.b         7
DD.r.k         3
DD.w.j         3
DD.e.u         2
DD.v.p         2
UD.j.k         1
UU.j.k         1
UD.k.b         1
UU.k.b         1
UD.e.u         1
UU.e.u         1
UD.v.p         0
DU.v.v         0
DU.p.p         0
UD.w.j         0
DU.w.w         0
UU.v.p         0
DU.k.k         0
DU.e.e         0
DU.j.j         0
UU.w.j         0
DU.u.u         0
UU.u.r         0
DU.r.r         0
DD.u.r         0
UD.u.r         0
DU.k.k.1       0
UU.r.k         0
UD.r.k         0
DU.b.b         0
dtype: int64

Zero values per timing feature:
DU.k.e      214
DU.u.r      207
DU.k.b      194
DU.r.k      144
DU.v.p      132
DU.e.u      100
DU.j.k      100
DU.w.j       71
DU.p.w       39
DD.v.p        6
DD.w.j        2
DD.k.b        1
DD.j.k        1
DU.v.v        0
UD.w.j        0
DU.w.w        0
UD.p.w        0
UU.p.w        0
DD.p.w        0
UD.v.p        0
UU.v.p        0
DU.p.p        0
DD.k.e        0
DU.k.k        0
UU.k.e        0
UD.k.e        0
UD.j.k        0
UU.j.k        0
DU.j.j        0
UU.w.j        0
UU.e.u        0
UD.e.u        0
DD.e.u        0
DU.e.e        0
UD.u.r        0
UU.u.r        0
DD.u.r        0
DU.u.u        0
DD.r.k        0
DU.r.r        0
UU.r.k        0
UD.r.k        0
DU.k.k.1      0
UD.k.b        0
UU.k.b        0
DU.b.b        0
dtype: int64

In [ ]:
# Step 3.34: Identify extreme timing values

import numpy as np

# Select numeric timing features
timing_cols_fixed = [
    col for col in df_fixed.select_dtypes(include="number").columns
    if col not in ["session", "repetition", "total time"]
]

# Identify values with absolute magnitude greater than 100 seconds
extreme_mask = df_fixed[timing_cols_fixed].abs() > 100

# Find rows containing at least one extreme value
extreme_rows = df_fixed.loc[extreme_mask.any(axis=1)].copy()

print("Rows containing extreme timing values:", len(extreme_rows))

print("\nFirst 10 affected records:")
display(
    extreme_rows[
        ["participant", "session", "repetition"]
        + timing_cols_fixed
    ].head(10)
)

print("\nNumber of extreme values in each feature:")
print(
    extreme_mask.sum()
    .loc[lambda x: x > 0]
    .sort_values(ascending=False)
)

Rows containing extreme timing values: 3

First 10 affected records:

,participant,session,repetition,DU.v.v,DD.v.p,DU.v.p,UD.v.p,UU.v.p,DU.p.p,DD.p.w,...,DD.r.k,DU.r.k,UD.r.k,UU.r.k,DU.k.k.1,DD.k.b,DU.k.b,UD.k.b,UU.k.b,DU.b.b
3900,p020,2,4,0.118,0.299,0.226,0.417,0.344,0.073,0.169,...,1077834.106,1077834.017,1077834.204,1077834.115,0.089,-1077833.679,-1077833.774,-1077833.590,-1077833.685,0.095
14003,p071,1,20,0.144,0.080,-0.048,0.224,0.096,0.128,0.544,...,0.656,0.544,0.769,0.657,0.112,0.192,0.064,0.304,0.176,0.128
17185,p087,1,8,0.119,0.128,0.073,0.247,0.192,0.055,0.648,...,0.960,0.832,1.056,0.928,0.128,332.701,332.605,332.829,332.733,0.096

Number of extreme values in each feature:
DD.j.k    2
DU.j.k    2
UD.j.k    2
UU.j.k    2
UU.k.b    2
DD.k.b    2
DU.k.b    2
UD.k.b    2
DU.k.e    1
UU.e.u    1
UD.e.u    1
DU.e.e    1
UU.k.e    1
UU.r.k    1
UD.r.k    1
DU.r.k    1
DD.r.k    1
dtype: int64

In [ ]:
# Step 3.35: Inspect exact extreme timing values

for idx, row in extreme_rows.iterrows():

    print("\n" + "=" * 60)
    print("DataFrame index:", idx)
    print("Participant:", row["participant"])
    print("Session:", row["session"])
    print("Repetition:", row["repetition"])

    print("\nExtreme timing values:")

    for col in timing_cols_fixed:
        value = row[col]

        if abs(value) > 100:
            print(f"{col}: {value}")

============================================================
DataFrame index: 3900
Participant: p020
Session: 2
Repetition: 4

Extreme timing values:
DD.j.k: -1077833.67
DU.j.k: -1077833.755
UD.j.k: -1077833.601
UU.j.k: -1077833.686
DU.k.e: 1077833.851
UU.k.e: 1077833.936
DU.e.e: 1077834.425
UD.e.u: -1077834.25
UU.e.u: -1077834.328
DD.r.k: 1077834.106
DU.r.k: 1077834.017
UD.r.k: 1077834.204
UU.r.k: 1077834.115
DD.k.b: -1077833.679
DU.k.b: -1077833.774
UD.k.b: -1077833.59
UU.k.b: -1077833.685

============================================================
DataFrame index: 14003
Participant: p071
Session: 1
Repetition: 20

Extreme timing values:
DD.j.k: 645.836
DU.j.k: 645.724
UD.j.k: 645.996
UU.j.k: 645.884

============================================================
DataFrame index: 17185
Participant: p087
Session: 1
Repetition: 8

Extreme timing values:
DD.k.b: 332.701
DU.k.b: 332.605
UD.k.b: 332.829
UU.k.b: 332.733

In [ ]:
# Step 3.37: Create a compact report of extreme timing values

extreme_report = []

for idx, row in extreme_rows.iterrows():

    for col in timing_cols_fixed:
        value = row[col]

        if abs(value) > 100:
            extreme_report.append({
                "dataframe_index": idx,
                "participant": row["participant"],
                "session": row["session"],
                "repetition": row["repetition"],
                "feature": col,
                "value": value
            })

extreme_report_df = pd.DataFrame(extreme_report)

display(extreme_report_df)

    dataframe_index participant  session  repetition feature        value
0              3900        p020        2           4  DD.j.k -1077833.670
1              3900        p020        2           4  DU.j.k -1077833.755
2              3900        p020        2           4  UD.j.k -1077833.601
3              3900        p020        2           4  UU.j.k -1077833.686
4              3900        p020        2           4  DU.k.e  1077833.851
5              3900        p020        2           4  UU.k.e  1077833.936
6              3900        p020        2           4  DU.e.e  1077834.425
7              3900        p020        2           4  UD.e.u -1077834.250
8              3900        p020        2           4  UU.e.u -1077834.328
9              3900        p020        2           4  DD.r.k  1077834.106
10             3900        p020        2           4  DU.r.k  1077834.017
11             3900        p020        2           4  UD.r.k  1077834.204
12             3900        p020        2           4  UU.r.k  1077834.115
13             3900        p020        2           4  DD.k.b -1077833.679
14             3900        p020        2           4  DU.k.b -1077833.774
15             3900        p020        2           4  UD.k.b -1077833.590
16             3900        p020        2           4  UU.k.b -1077833.685
17            14003        p071        1          20  DD.j.k      645.836
18            14003        p071        1          20  DU.j.k      645.724
19            14003        p071        1          20  UD.j.k      645.996
20            14003        p071        1          20  UU.j.k      645.884
21            17185        p087        1           8  DD.k.b      332.701
22            17185        p087        1           8  DU.k.b      332.605
23            17185        p087        1           8  UD.k.b      332.829
24            17185        p087        1           8  UU.k.b      332.733

In [ ]:
# Step 3.39: Inspect neighboring repetitions

participants_to_check = [
    ("p020", 2, 4),
    ("p071", 1, 20),
    ("p087", 1, 8)
]

for participant, session, repetition in participants_to_check:

    print("\n" + "=" * 80)
    print(
        f"Participant: {participant} | "
        f"Session: {session} | "
        f"Repetition: {repetition}"
    )

    # Find the selected repetition and its nearby repetitions
    nearby_records = df_fixed[
        (df_fixed["participant"] == participant) &
        (df_fixed["session"] == session) &
        (df_fixed["repetition"].between(
            repetition - 2,
            repetition + 2
        ))
    ].sort_values("repetition")

    # Display identifiers and timing features
    display(nearby_records)

================================================================================
Participant: p020 | Session: 2 | Repetition: 4

,participant,session,repetition,DU.v.v,DD.v.p,DU.v.p,UD.v.p,UU.v.p,DU.p.p,DD.p.w,...,DU.r.k,UD.r.k,UU.r.k,DU.k.k.1,DD.k.b,DU.k.b,UD.k.b,UU.k.b,DU.b.b,total time
3898,p020,2,2,0.092,0.085,-0.007,0.177,0.085,0.092,0.109,...,0.392,0.558,0.472,0.086,0.066,-0.023,0.152,0.063,0.089,1.294
3899,p020,2,3,0.113,0.079,-0.040,0.192,0.073,0.119,0.114,...,2.591,2.743,2.667,0.076,0.134,0.051,0.210,0.127,0.083,3.462
3900,p020,2,4,0.118,0.299,0.226,0.417,0.344,0.073,0.169,...,1077834.017,1077834.204,1077834.115,0.089,-1077833.679,-1077833.774,-1077833.590,-1077833.685,0.095,-1077832.627
3901,p020,2,5,0.132,0.071,-0.043,0.203,0.089,0.114,0.159,...,1.042,1.216,1.123,0.093,0.218,0.130,0.311,0.223,0.088,2.180
3902,p020,2,6,0.099,0.088,-0.003,0.187,0.096,0.091,0.131,...,0.191,0.379,0.301,0.078,0.133,0.046,0.211,0.124,0.087,1.165

================================================================================
Participant: p071 | Session: 1 | Repetition: 20

,participant,session,repetition,DU.v.v,DD.v.p,DU.v.p,UD.v.p,UU.v.p,DU.p.p,DD.p.w,...,DU.r.k,UD.r.k,UU.r.k,DU.k.k.1,DD.k.b,DU.k.b,UD.k.b,UU.k.b,DU.b.b,total time
14001,p071,1,18,0.160,0.112,-0.080,0.272,0.080,0.192,0.704,...,0.448,0.720,0.592,0.128,0.192,0.032,0.320,0.160,0.160,2.816
14002,p071,1,19,0.176,0.096,-0.112,0.272,0.064,0.208,0.768,...,0.688,0.960,0.848,0.112,0.128,0.001,0.240,0.113,0.127,4.385
14003,p071,1,20,0.144,0.080,-0.048,0.224,0.096,0.128,0.544,...,0.544,0.769,0.657,0.112,0.192,0.064,0.304,0.176,0.128,647.964
14004,p071,1,21,0.144,0.144,0.016,0.288,0.160,0.128,0.256,...,0.159,0.400,0.271,0.129,0.256,0.160,0.385,0.289,0.096,2.176
14005,p071,1,22,0.144,0.224,0.048,0.368,0.192,0.176,0.464,...,0.256,0.480,0.368,0.112,0.080,0.064,0.192,0.176,0.016,2.032

================================================================================
Participant: p087 | Session: 1 | Repetition: 8

,participant,session,repetition,DU.v.v,DD.v.p,DU.v.p,UD.v.p,UU.v.p,DU.p.p,DD.p.w,...,DU.r.k,UD.r.k,UU.r.k,DU.k.k.1,DD.k.b,DU.k.b,UD.k.b,UU.k.b,DU.b.b,total time
17183,p087,1,6,0.128,0.160,0.032,0.288,0.160,0.128,0.928,...,0.512,0.736,0.608,0.128,0.192,0.065,0.320,0.193,0.127,3.297
17184,p087,1,7,0.096,0.128,0.064,0.224,0.160,0.064,0.672,...,0.320,0.479,0.415,0.064,0.160,0.001,0.224,0.065,0.159,3.585
17185,p087,1,8,0.119,0.128,0.073,0.247,0.192,0.055,0.648,...,0.832,1.056,0.928,0.128,332.701,332.605,332.829,332.733,0.096,335.526
17186,p087,1,9,0.096,0.608,0.512,0.704,0.608,0.096,0.480,...,0.609,0.800,0.705,0.095,0.128,0.065,0.223,0.160,0.063,3.009
17187,p087,1,10,0.096,0.128,0.064,0.224,0.160,0.064,1.632,...,0.649,0.800,0.704,0.096,0.064,0.000,0.160,0.096,0.064,4.105

In [ ]:
# Step 3.41: Compare total time with extreme timing features

for idx in extreme_rows.index:

    row = df_fixed.loc[idx]

    print("\n" + "=" * 60)
    print("DataFrame index:", idx)
    print("Participant:", row["participant"])
    print("Session:", row["session"])
    print("Repetition:", row["repetition"])

    print("\nTotal time:", row["total time"])

    print("\nTiming features with absolute values greater than 100:")

    for col in timing_cols_fixed:
        value = row[col]

        if abs(value) > 100:
            print(f"{col}: {value}")

============================================================
DataFrame index: 3900
Participant: p020
Session: 2
Repetition: 4

Total time: -1077832.627

Timing features with absolute values greater than 100:
DD.j.k: -1077833.67
DU.j.k: -1077833.755
UD.j.k: -1077833.601
UU.j.k: -1077833.686
DU.k.e: 1077833.851
UU.k.e: 1077833.936
DU.e.e: 1077834.425
UD.e.u: -1077834.25
UU.e.u: -1077834.328
DD.r.k: 1077834.106
DU.r.k: 1077834.017
UD.r.k: 1077834.204
UU.r.k: 1077834.115
DD.k.b: -1077833.679
DU.k.b: -1077833.774
UD.k.b: -1077833.59
UU.k.b: -1077833.685

============================================================
DataFrame index: 14003
Participant: p071
Session: 1
Repetition: 20

Total time: 647.964

Timing features with absolute values greater than 100:
DD.j.k: 645.836
DU.j.k: 645.724
UD.j.k: 645.996
UU.j.k: 645.884

============================================================
DataFrame index: 17185
Participant: p087
Session: 1
Repetition: 8

Total time: 335.526

Timing features with absolute values greater than 100:
DD.k.b: 332.701
DU.k.b: 332.605
UD.k.b: 332.829
UU.k.b: 332.733

In [ ]:
# Step 3.43: Save the extreme-value report

from pathlib import Path

report_dir = Path("../results/metrics")
report_dir.mkdir(parents=True, exist_ok=True)

report_path = report_dir / "fixed_text_extreme_values.csv"

extreme_report_df.to_csv(report_path, index=False)

print("Extreme-value report saved successfully.")
print("Location:", report_path.resolve())
print("Number of flagged timing values:", len(extreme_report_df))
print("Number of affected records:", extreme_report_df["dataframe_index"].nunique())

Extreme-value report saved successfully.
Location: C:\Users\LOQ\OneDrive\Desktop\Komal_clg\5th sem\DL Lab\Project\DeepKey_DL_Project\results\metrics\fixed_text_extreme_values.csv
Number of flagged timing values: 25
Number of affected records: 3

In [ ]:
# Step 3.44: Count negative values in timing features

# Select numeric timing columns
timing_cols_fixed = [
    col for col in df_fixed.select_dtypes(include="number").columns
    if col not in ["session", "repetition", "total time"]
]

# Count negative values in each feature
negative_counts = (df_fixed[timing_cols_fixed] < 0).sum()

# Keep only features that contain negative values
negative_counts = negative_counts[negative_counts > 0]

# Sort from highest to lowest
negative_counts = negative_counts.sort_values(ascending=False)

print("Number of timing features containing negative values:",
      len(negative_counts))

print("\nNegative values per feature:")
display(negative_counts.to_frame(name="negative_value_count"))

print("\nTotal negative feature values:",
      int(negative_counts.sum()))

Number of timing features containing negative values: 27

Negative values per feature:

        negative_value_count
DU.j.k                  3480
DU.v.p                  1825
DU.k.e                  1633
DU.u.r                  1150
DU.k.b                  1082
DU.e.u                  1035
DU.w.j                  1032
DU.r.k                   393
DU.p.w                   368
DD.k.e                    26
DD.j.k                    25
DD.p.w                    24
UD.p.w                    24
UU.p.w                    24
UU.k.e                    23
UD.k.e                    12
DD.k.b                     7
DD.w.j                     3
DD.r.k                     3
DD.e.u                     2
DD.v.p                     2
UD.j.k                     1
UU.j.k                     1
UD.e.u                     1
UU.e.u                     1
UD.k.b                     1
UU.k.b                     1

Total negative feature values: 12179

In [ ]:
# Step 3.46: Analyze the ranges of negative timing values

negative_feature_stats = df_fixed[negative_counts.index].agg(
    ["min", "max", "mean", "std"]
).T

negative_feature_stats["negative_count"] = negative_counts

negative_feature_stats = negative_feature_stats.sort_values(
    by="negative_count",
    ascending=False
)

print("Statistics for timing features containing negative values:")

display(negative_feature_stats)

Statistics for timing features containing negative values:

                min          max       mean          std  negative_count
DU.j.k -1077833.755      645.724 -54.319907  7665.255504            3480
DU.v.p       -0.172       76.321   0.167657     0.609162            1825
DU.k.e       -0.478  1077833.851  54.705447  7665.252072            1633
DU.u.r       -0.100       20.157   0.130939     0.250923            1150
DU.k.b -1077833.774      332.605 -54.315447  7665.254658            1082
DU.e.u       -0.111       14.625   0.140885     0.258797            1035
DU.w.j       -0.145       28.286   0.333512     0.550036            1032
DU.r.k       -0.148  1077834.017  54.863237  7665.252138             393
DU.p.w       -7.064       67.254   0.302647     0.826035             368
DD.k.e       -0.574       16.546   0.296460     0.348266              26
DD.j.k -1077833.670      645.836 -54.220783  7665.255605              25
DD.p.w       -6.965       67.362   0.405263     0.826127              24
UD.p.w       -6.889       67.418   0.500509     0.826363              24
UU.p.w       -6.988       67.310   0.397893     0.825646              24
UU.k.e       -0.365  1077833.936  54.804570  7665.251972              23
UD.k.e       -0.489       16.642   0.395583     0.350909              12
DD.k.b -1077833.679      332.701 -54.225695  7665.254621               7
DD.w.j       -0.073       28.340   0.429214     0.553540               3
DD.r.k       -0.051  1077834.106  54.957758  7665.252099               3
DD.e.u       -0.045       14.724   0.231974     0.260189               2
DD.v.p       -0.061       76.414   0.262902     0.609094               2
UD.j.k -1077833.601      645.996 -54.125081  7665.255795               1
UU.j.k -1077833.686      645.884 -54.224205  7665.255694               1
UD.e.u -1077834.250       14.871 -54.177013  7665.258665               1
UU.e.u -1077834.328       14.772 -54.268101  7665.258571               1
UD.k.b -1077833.590      332.829 -54.131175  7665.254660               1
UU.k.b -1077833.685      332.733 -54.220927  7665.254697               1

In [ ]:
# Step 3.48: Count records containing extreme timing values

import numpy as np

# Use the same timing columns as before
timing_cols_fixed = [
    col for col in df_fixed.select_dtypes(include="number").columns
    if col not in ["session", "repetition", "total time"]
]

# Identify extreme values
extreme_mask = df_fixed[timing_cols_fixed].abs() > 100

# Count affected records
extreme_record_count = int(extreme_mask.any(axis=1).sum())

# Count affected feature values
extreme_value_count = int(extreme_mask.sum().sum())

print("Total records:", len(df_fixed))
print("Records containing timing values above 100 seconds in magnitude:",
      extreme_record_count)
print("Total extreme timing-feature values:", extreme_value_count)

print("\nAffected records:")
display(
    df_fixed.loc[
        extreme_mask.any(axis=1),
        ["participant", "session", "repetition", "total time"]
    ]
)

Total records: 19772
Records containing timing values above 100 seconds in magnitude: 3
Total extreme timing-feature values: 25

Affected records:

      participant  session  repetition   total time
3900         p020        2           4 -1077832.627
14003        p071        1          20      647.964
17185        p087        1           8      335.526

In [ ]:
# Step 3.50: Inspect total time

print("Total records:", len(df_fixed))

print("\nMissing total-time values:")
print(df_fixed["total time"].isna().sum())

print("\nNegative total-time values:")
print((df_fixed["total time"] < 0).sum())

print("\nTotal times above 100 seconds:")
print((df_fixed["total time"] > 100).sum())

print("\nTotal-time statistics:")
display(
    df_fixed["total time"].describe().to_frame()
)

print("\nRecords with total time below zero or above 100 seconds:")

unusual_total_time = df_fixed[
    (df_fixed["total time"] < 0) |
    (df_fixed["total time"] > 100)
]

display(
    unusual_total_time[
        ["participant", "session", "repetition", "total time"]
    ]
)

Total records: 19772

Missing total-time values:
0

Negative total-time values:
1

Total times above 100 seconds:
2

Total-time statistics:

         total time
count  1.977200e+04
mean  -5.172628e+01
std    7.665266e+03
min   -1.077833e+06
25%    1.819000e+00
50%    2.413000e+00
75%    3.245500e+00
max    6.479640e+02

Records with total time below zero or above 100 seconds:

      participant  session  repetition   total time
3900         p020        2           4 -1077832.627
14003        p071        1          20      647.964
17185        p087        1           8      335.526

In [ ]:
# Step 3.52: Compare total-time statistics

# Original total-time statistics
print("Original dataset — total time:")
display(df_fixed["total time"].describe().to_frame())

# Temporarily exclude the three flagged records for comparison
flagged_indices = extreme_rows.index

df_comparison = df_fixed.drop(index=flagged_indices)

print("\nComparison dataset — excluding flagged records temporarily:")
display(df_comparison["total time"].describe().to_frame())

print("\nRecords in original dataset:", len(df_fixed))
print("Records in comparison dataset:", len(df_comparison))
print("Flagged records excluded for comparison:", len(flagged_indices))

Original dataset — total time:

         total time
count  1.977200e+04
mean  -5.172628e+01
std    7.665266e+03
min   -1.077833e+06
25%    1.819000e+00
50%    2.413000e+00
75%    3.245500e+00
max    6.479640e+02

Comparison dataset — excluding flagged records temporarily:

         total time
count  19769.000000
mean       2.737479
std        1.769956
min        0.027000
25%        1.819000
50%        2.413000
75%        3.245000
max       83.201000

Records in original dataset: 19772
Records in comparison dataset: 19769
Flagged records excluded for comparison: 3

In [ ]:
# Step 3.53: Investigate unusually large total times

# Find records where total time is greater than 10 seconds
large_time_records = df_fixed[df_fixed["total time"] > 10]

print("Number of records with total time > 10 seconds:",
      len(large_time_records))

# Display the important columns
display(
    large_time_records[
        ["participant", "session", "repetition", "total time"]
    ].sort_values(by="total time", ascending=False)
)

Number of records with total time > 10 seconds: 78

      participant  session  repetition  total time
14003        p071        1          20     647.964
17185        p087        1           8     335.526
4985         p025        2          82      83.201
8318         p042        2          23      77.652
2100         p011        2           2      57.359
...           ...      ...         ...         ...
8160         p041        2          64      10.198
6201         p032        1           4      10.196
8000         p041        1           4      10.119
0            p001        1           1      10.101
10830        p055        1          45      10.045

[78 rows x 4 columns]

In [ ]:
# Step 3.54: Investigate timing features in long-duration records

# Select records with total time greater than 10 seconds
large_time_records = df_fixed[df_fixed["total time"] > 10]

# Select the timing columns
timing_columns = [
    col for col in df_fixed.select_dtypes(include="number").columns
    if col not in ["session", "repetition", "total time"]
]

# Count timing features with absolute values greater than 100
large_time_records = large_time_records.copy()

large_time_records["extreme_feature_count"] = (
    large_time_records[timing_columns].abs() > 100
).sum(axis=1)

# Display the results
display(
    large_time_records[
        [
            "participant",
            "session",
            "repetition",
            "total time",
            "extreme_feature_count"
        ]
    ].sort_values(
        by="total time",
        ascending=False
    )
)

      participant  session  repetition  total time  extreme_feature_count
14003        p071        1          20     647.964                      4
17185        p087        1           8     335.526                      4
4985         p025        2          82      83.201                      0
8318         p042        2          23      77.652                      0
2100         p011        2           2      57.359                      0
...           ...      ...         ...         ...                    ...
8160         p041        2          64      10.198                      0
6201         p032        1           4      10.196                      0
8000         p041        1           4      10.119                      0
0            p001        1           1      10.101                      0
10830        p055        1          45      10.045                      0

[78 rows x 5 columns]

In [ ]:
# Step 3.55: Inspect the three previously flagged records

flagged_indices = [3900, 14003, 17185]

# Select the flagged records
flagged_records = df_fixed.loc[flagged_indices]

# Display identifiers and total time
display(
    flagged_records[
        ["participant", "session", "repetition", "total time"]
    ]
)

# Display timing features for these records
display(flagged_records[timing_columns].T)

      participant  session  repetition   total time
3900         p020        2           4 -1077832.627
14003        p071        1          20      647.964
17185        p087        1           8      335.526

                3900     14003    17185
DU.v.v          0.118    0.144    0.119
DD.v.p          0.299    0.080    0.128
DU.v.p          0.226   -0.048    0.073
UD.v.p          0.417    0.224    0.247
UU.v.p          0.344    0.096    0.192
DU.p.p          0.073    0.128    0.055
DD.p.w          0.169    0.544    0.648
DU.p.w          0.065    0.400    0.553
UD.p.w          0.242    0.672    0.703
UU.p.w          0.138    0.528    0.608
DU.w.w          0.104    0.144    0.095
DD.w.j          0.496    0.096    0.257
DU.w.j          0.427   -0.064    0.193
UD.w.j          0.600    0.240    0.352
UU.w.j          0.531    0.080    0.288
DU.j.j          0.069    0.160    0.064
DD.j.k   -1077833.670  645.836    0.288
DU.j.k   -1077833.755  645.724    0.224
UD.j.k   -1077833.601  645.996    0.352
UU.j.k   -1077833.686  645.884    0.288
DU.k.k          0.085    0.112    0.064
DD.k.e         -0.574    0.160    0.128
DU.k.e    1077833.851    0.032    0.032
UD.k.e         -0.489    0.272    0.192
UU.k.e    1077833.936    0.144    0.096
DU.e.e    1077834.425    0.128    0.096
DD.e.u          0.175    0.384    0.319
DU.e.u          0.097    0.272    0.256
UD.e.u   -1077834.250    0.512    0.415
UU.e.u   -1077834.328    0.400    0.352
DU.u.u          0.078    0.112    0.063
DD.u.r          0.146    0.144    0.193
DU.u.r          0.048    0.031    0.097
UD.u.r          0.224    0.256    0.256
UU.u.r          0.126    0.143    0.160
DU.r.r          0.098    0.113    0.096
DD.r.k    1077834.106    0.656    0.960
DU.r.k    1077834.017    0.544    0.832
UD.r.k    1077834.204    0.769    1.056
UU.r.k    1077834.115    0.657    0.928
DU.k.k.1        0.089    0.112    0.128
DD.k.b   -1077833.679    0.192  332.701
DU.k.b   -1077833.774    0.064  332.605
UD.k.b   -1077833.590    0.304  332.829
UU.k.b   -1077833.685    0.176  332.733
DU.b.b          0.095    0.128    0.096

In [ ]:
# Step 3.56: Compare flagged records with nearby repetitions

flagged_cases = [
    ("p020", 2, 4),
    ("p071", 1, 20),
    ("p087", 1, 8)
]

for participant, session, repetition in flagged_cases:

    print(
        f"\nParticipant: {participant}, "
        f"Session: {session}, "
        f"Flagged repetition: {repetition}"
    )

    # Select nearby repetitions from the same participant and session
    nearby_records = df_fixed[
        (df_fixed["participant"] == participant) &
        (df_fixed["session"] == session) &
        (df_fixed["repetition"].between(
            repetition - 2, repetition + 2
        ))
    ]

    # Display repetition numbers and total times
    display(
        nearby_records[
            ["participant", "session", "repetition", "total time"]
        ].sort_values("repetition")
    )

Participant: p020, Session: 2, Flagged repetition: 4

     participant  session  repetition   total time
3898        p020        2           2        1.294
3899        p020        2           3        3.462
3900        p020        2           4 -1077832.627
3901        p020        2           5        2.180
3902        p020        2           6        1.165

Participant: p071, Session: 1, Flagged repetition: 20

      participant  session  repetition  total time
14001        p071        1          18       2.816
14002        p071        1          19       4.385
14003        p071        1          20     647.964
14004        p071        1          21       2.176
14005        p071        1          22       2.032

Participant: p087, Session: 1, Flagged repetition: 8

      participant  session  repetition  total time
17183        p087        1           6       3.297
17184        p087        1           7       3.585
17185        p087        1           8     335.526
17186        p087        1           9       3.009
17187        p087        1          10       4.105

In [ ]:
# Step 3.57: Summarize the three flagged records

quality_summary = pd.DataFrame({
    "participant": ["p020", "p071", "p087"],
    "session": [2, 1, 1],
    "repetition": [4, 20, 8],
    "total_time": [-1077832.627, 647.964, 335.526],
    "finding": [
        "Extremely large positive and negative timing values",
        "Four timing features around 646 seconds",
        "Four timing features around 333 seconds"
    ],
    "neighbouring_records": [
        "Nearby repetitions have normal-looking durations",
        "Nearby repetitions have normal-looking durations",
        "Nearby repetitions have normal-looking durations"
    ],
    "decision": [
        "Investigate before cleaning",
        "Investigate before cleaning",
        "Investigate before cleaning"
    ]
})

display(quality_summary)

,participant,session,repetition,total_time,finding,neighbouring_records,decision
0,p020,2,4,-1077832.627,Extremely large positive and negative timing v...,Nearby repetitions have normal-looking durations,Investigate before cleaning
1,p071,1,20,647.964,Four timing features around 646 seconds,Nearby repetitions have normal-looking durations,Investigate before cleaning
2,p087,1,8,335.526,Four timing features around 333 seconds,Nearby repetitions have normal-looking durations,Investigate before cleaning

In [ ]:
# Step 3.58: Document preliminary data-cleaning rules

cleaning_rules = pd.DataFrame({
    "issue": [
        "Extreme fixed-text timing values",
        "Long total times",
        "Negative timing features",
        "Missing terminal key-pair values",
        "Suspicious free-text CSV records",
        "Missing values in fixed-text dataset"
    ],

    "observation": [
        "Three records contain extreme timing values",
        "78 records have total time greater than 10 seconds",
        "Negative values occur in several timing features",
        "198 records have missing key2 and pair-timing values",
        "13 records have unusual parsed CSV fields",
        "No missing values were detected"
    ],

    "planned_action": [
        "Investigate and verify before deciding whether to exclude",
        "Inspect individually; do not automatically delete",
        "Understand timing definitions before changing values",
        "Verify whether these are expected terminal records",
        "Inspect the raw CSV structure before correcting",
        "No missing-value treatment currently required"
    ],

    "status": [
        "Pending verification",
        "Pending investigation",
        "Pending verification",
        "Pending verification",
        "Pending investigation",
        "Initial check completed"
    ]
})

display(cleaning_rules)

,issue,observation,planned_action,status
0,Extreme fixed-text timing values,Three records contain extreme timing values,Investigate and verify before deciding whether...,Pending verification
1,Long total times,78 records have total time greater than 10 sec...,Inspect individually; do not automatically delete,Pending investigation
2,Negative timing features,Negative values occur in several timing features,Understand timing definitions before changing ...,Pending verification
3,Missing terminal key-pair values,198 records have missing key2 and pair-timing ...,Verify whether these are expected terminal rec...,Pending verification
4,Suspicious free-text CSV records,13 records have unusual parsed CSV fields,Inspect the raw CSV structure before correcting,Pending investigation
5,Missing values in fixed-text dataset,No missing values were detected,No missing-value treatment currently required,Initial check completed

In [ ]:
# Step 3.59: Check data types in the fixed-text dataset

print("Dataset shape:", df_fixed.shape)

print("\nData types of all columns:")
display(df_fixed.dtypes)

print("\nCount of each data type:")
display(df_fixed.dtypes.value_counts())

Dataset shape: (19772, 50)

Data types of all columns:

participant        str
session          int64
repetition       int64
DU.v.v         float64
DD.v.p         float64
DU.v.p         float64
UD.v.p         float64
UU.v.p         float64
DU.p.p         float64
DD.p.w         float64
DU.p.w         float64
UD.p.w         float64
UU.p.w         float64
DU.w.w         float64
DD.w.j         float64
DU.w.j         float64
UD.w.j         float64
UU.w.j         float64
DU.j.j         float64
DD.j.k         float64
DU.j.k         float64
UD.j.k         float64
UU.j.k         float64
DU.k.k         float64
DD.k.e         float64
DU.k.e         float64
UD.k.e         float64
UU.k.e         float64
DU.e.e         float64
DD.e.u         float64
DU.e.u         float64
UD.e.u         float64
UU.e.u         float64
DU.u.u         float64
DD.u.r         float64
DU.u.r         float64
UD.u.r         float64
UU.u.r         float64
DU.r.r         float64
DD.r.k         float64
DU.r.k         float64
UD.r.k         float64
UU.r.k         float64
DU.k.k.1       float64
DD.k.b         float64
DU.k.b         float64
UD.k.b         float64
UU.k.b         float64
DU.b.b         float64
total time     float64
dtype: object

Count of each data type:

float64    47
int64       2
str         1
Name: count, dtype: int64

In [ ]:
# Step 3.60: Check data types in the free-text dataset

print("Dataset shape:", df.shape)

print("\nData types of all columns:")
display(df.dtypes)

print("\nCount of each data type:")
display(df.dtypes.value_counts())

Dataset shape: (562583, 10)

Data types of all columns:

participant          str
session            int64
key1                 str
key2                 str
DU.key1.key1      object
DD.key1.key2     float64
DU.key1.key2     float64
UD.key1.key2     float64
UU.key1.key2     float64
Unnamed: 9       float64
dtype: object

Count of each data type:

float64    5
str        3
int64      1
object     1
Name: count, dtype: int64

In [ ]:
# Step 3.61: Investigate DU.key1.key1

print("Original data type:")
print(df["DU.key1.key1"].dtype)

print("\nSample values:")
display(df["DU.key1.key1"].head(15))

# Attempt numeric conversion for inspection only
du_numeric = pd.to_numeric(
    df["DU.key1.key1"],
    errors="coerce"
)

# Count values that could not be converted
non_numeric_count = (
    df["DU.key1.key1"].notna() & du_numeric.isna()
).sum()

print("\nValues that cannot be converted to numbers:")
print(non_numeric_count)

print("\nNumber of missing values after conversion:")
print(du_numeric.isna().sum())

Original data type:
object

Sample values:

0      0.15
1     0.962
2     0.107
3      0.08
4      0.08
5      0.16
6     0.104
7     0.073
8     0.164
9     0.063
10    0.128
11     0.08
12    0.062
13    0.085
14     0.15
Name: DU.key1.key1, dtype: object

Values that cannot be converted to numbers:
13

Number of missing values after conversion:
13

In [ ]:
# Step 3.62: Find non-numeric values in DU.key1.key1

du_numeric = pd.to_numeric(
    df["DU.key1.key1"],
    errors="coerce"
)

# Select values that are present but could not be converted
non_numeric_mask = (
    df["DU.key1.key1"].notna() &
    du_numeric.isna()
)

print("Number of non-numeric values:",
      non_numeric_mask.sum())

print("\nRows containing non-numeric values:")

display(
    df.loc[
        non_numeric_mask,
        [
            "participant",
            "session",
            "key1",
            "key2",
            "DU.key1.key1",
            "Unnamed: 9"
        ]
    ]
)

Number of non-numeric values: 13

Rows containing non-numeric values:

,participant,session,key1,key2,DU.key1.key1,Unnamed: 9
23481,p005,1,2,",0.087,1.088,1.183,1.001,1.096,\np005,1,",Shift,0.185
169381,p031,1,Backspace,",0.081,0.761,0.896,0.68,0.815,\np031,1,",Shift,0.042
177980,p033,1,e,",0.088,0.2,0.28,0.112,0.192\np033,1,",Backspace,0.464
181842,p033,2,t,",0.079,0.184,0.263,0.105,0.184,\np033,2,",Shift,0.072
204716,p037,2,Backspace,",0.134,0.281,0.502,0.147,0.368,\np037,2,",Backspace,0.280
205245,p037,2,Backspace,",0.166,0.569,0.726,0.403,0.56,\np037,2,",Backspace,0.345
306776,p055,1,Backspace,",0.123,0.785,0.87,0.662,0.747,\np055,1,",Shift,0.065
319078,p057,1,y,",0.137,0.304,0.49,0.167,0.353,\np057,1,",Shift,0.331
491603,p087,1,Backspace,",0.096,6.082,6.177,5.986,6.081,\np087,1,",Shift,0.064
491610,p087,1,Shift,",0.472,1.76,1.888,1.288,1.416,\np087,1,",Shift,0.120
491613,p087,1,Backspace,",0.096,0.8,0.896,0.704,0.8,\np087,1,",Shift,0.192
552060,p099,1,Shift,",0.0,0.06,0.229,0.06,0.229,\np099,1,",Shift,0.254
552098,p099,1,Shift,",0.0,0.033,0.192,0.033,0.192,\np099,1,",Shift,0.328

In [ ]:
# Step 3.63: Verify suspicious records

# Identify rows with non-numeric DU.key1.key1 values
du_numeric = pd.to_numeric(
    df["DU.key1.key1"],
    errors="coerce"
)

non_numeric_mask = (
    df["DU.key1.key1"].notna() &
    du_numeric.isna()
)

# Identify rows with values in the unexpected column
unnamed_mask = df["Unnamed: 9"].notna()

# Identify rows where key2 contains a newline
newline_mask = df["key2"].str.contains(
    "\n",
    regex=False,
    na=False
)

print("Non-numeric timing values:", non_numeric_mask.sum())
print("Rows with Unnamed: 9 values:", unnamed_mask.sum())
print("Rows with newlines in key2:", newline_mask.sum())

print(
    "\nNon-numeric rows also having Unnamed: 9 values:",
    (non_numeric_mask & unnamed_mask).sum()
)

print(
    "Non-numeric rows also having newlines in key2:",
    (non_numeric_mask & newline_mask).sum()
)

print(
    "All three conditions match:",
    (
        (non_numeric_mask == unnamed_mask) &
        (non_numeric_mask == newline_mask)
    ).all()
)

Non-numeric timing values: 13
Rows with Unnamed: 9 values: 13
Rows with newlines in key2: 13

Non-numeric rows also having Unnamed: 9 values: 13
Non-numeric rows also having newlines in key2: 13
All three conditions match: True

In [ ]:
# Step 3.64: Inspect the original CSV around a suspicious record

from pathlib import Path

raw_file = Path("../data/raw/free-text.csv")

print("File exists:", raw_file.exists())
print("File path:", raw_file.resolve())

# Read the original file without modifying it
with open(raw_file, "r", encoding="utf-8", newline="") as file:
    raw_lines = file.readlines()

# Show a small section around the suspicious record
start_line = 23478
end_line = 23489

print("\nOriginal CSV lines:")
for line_number in range(start_line, end_line + 1):
    print(f"Line {line_number}: {raw_lines[line_number - 1].rstrip()}")

File exists: True
File path: C:\Users\LOQ\OneDrive\Desktop\Komal_clg\5th sem\DL Lab\Project\DeepKey_DL_Project\data\raw\free-text.csv

Original CSV lines:
Line 23478: p005,1,Backspace,c,0.072,0.12,0.256,0.048,0.184,
Line 23479: p005,1,c,h,0.136,0.417,0.52,0.281,0.384,
Line 23480: p005,1,h,-,0.103,0.608,0.711,0.505,0.608,
Line 23481: p005,1,-,2,0.103,1,1.103,0.897,1,
Line 23482: p005,1,2,2,0.103,0.192,0.279,0.089,0.176,
Line 23483: p005,1,2,",0.087,1.088,1.183,1.001,1.096,
Line 23484: p005,1,",Shift,0.095,-0.472,0.28,-0.567,0.185
Line 23485: p005,1,Shift,Backspace,0.752,1.208,1.272,0.456,0.52,
Line 23486: p005,1,Backspace,:,0.064,0.336,0.408,0.272,0.344,
Line 23487: p005,1,:,Shift,0.072,-0.224,0.216,-0.296,0.144,
Line 23488: p005,1,Shift,Space,0.44,0.8,0.96,0.36,0.52,
Line 23489: p005,1,Space,a,0.16,0.296,0.4,0.136,0.24,

In [ ]:
# Step 3.65: Compare normal and suspicious CSV lines

import csv

# Normal record
normal_line = raw_lines[23481 - 1]

# Suspicious physical lines
suspicious_line_1 = raw_lines[23483 - 1]
suspicious_line_2 = raw_lines[23484 - 1]

print("Normal line:")
print(normal_line.rstrip())
print("Fields:", len(next(csv.reader([normal_line]))))

print("\nSuspicious line 1:")
print(suspicious_line_1.rstrip())
print("Fields:", len(next(csv.reader([suspicious_line_1]))))

print("\nSuspicious line 2:")
print(suspicious_line_2.rstrip())
print("Fields:", len(next(csv.reader([suspicious_line_2]))))

Normal line:
p005,1,-,2,0.103,1,1.103,0.897,1,
Fields: 10

Suspicious line 1:
p005,1,2,",0.087,1.088,1.183,1.001,1.096,
Fields: 4

Suspicious line 2:
p005,1,",Shift,0.095,-0.472,0.28,-0.567,0.185
Fields: 3

In [ ]:
# Step 3.66: Summarize all suspicious records

suspicious_records = df.loc[
    non_numeric_mask,
    [
        "participant",
        "session",
        "key1",
        "key2",
        "DU.key1.key1",
        "DD.key1.key2",
        "DU.key1.key2",
        "UD.key1.key2",
        "UU.key1.key2 ",
        "Unnamed: 9"
    ]
].copy()

print("Number of suspicious records:", len(suspicious_records))

print("\nSuspicious records by participant:")
display(
    suspicious_records["participant"].value_counts().sort_index()
)

print("\nSuspicious records by session:")
display(
    suspicious_records["session"].value_counts().sort_index()
)

print("\nSuspicious records:")
display(suspicious_records)

Number of suspicious records: 13

Suspicious records by participant:

participant
p005    1
p031    1
p033    2
p037    2
p055    1
p057    1
p087    3
p099    2
Name: count, dtype: int64

Suspicious records by session:

session
1    10
2     3
Name: count, dtype: int64

Suspicious records:

,participant,session,key1,key2,DU.key1.key1,DD.key1.key2,DU.key1.key2,UD.key1.key2,UU.key1.key2,Unnamed: 9
23481,p005,1,2,",0.087,1.088,1.183,1.001,1.096,\np005,1,",Shift,0.095,-0.472,0.280,-0.567,0.185
169381,p031,1,Backspace,",0.081,0.761,0.896,0.68,0.815,\np031,1,",Shift,0.135,-0.341,0.177,-0.476,0.042
177980,p033,1,e,",0.088,0.2,0.28,0.112,0.192\np033,1,",Backspace,0.080,0.400,0.544,0.320,0.464
181842,p033,2,t,",0.079,0.184,0.263,0.105,0.184,\np033,2,",Shift,0.079,-0.041,0.151,-0.120,0.072
204716,p037,2,Backspace,",0.134,0.281,0.502,0.147,0.368,\np037,2,",Backspace,0.221,0.342,0.501,0.121,0.280
205245,p037,2,Backspace,",0.166,0.569,0.726,0.403,0.56,\np037,2,",Backspace,0.157,0.319,0.502,0.162,0.345
306776,p055,1,Backspace,",0.123,0.785,0.87,0.662,0.747,\np055,1,",Shift,0.085,-0.168,0.150,-0.253,0.065
319078,p057,1,y,",0.137,0.304,0.49,0.167,0.353,\np057,1,",Shift,0.186,-0.047,0.517,-0.233,0.331
491603,p087,1,Backspace,",0.096,6.082,6.177,5.986,6.081,\np087,1,",Shift,0.095,-0.289,0.159,-0.384,0.064
491610,p087,1,Shift,",0.472,1.76,1.888,1.288,1.416,\np087,1,",Shift,0.128,-0.352,0.248,-0.480,0.120
491613,p087,1,Backspace,",0.096,0.8,0.896,0.704,0.8,\np087,1,",Shift,0.096,-0.192,0.288,-0.288,0.192
552060,p099,1,Shift,",0.0,0.06,0.229,0.06,0.229,\np099,1,",Shift,0.169,-0.029,0.423,-0.198,0.254
552098,p099,1,Shift,",0.0,0.033,0.192,0.033,0.192,\np099,1,",Shift,0.159,-0.002,0.487,-0.161,0.328

In [ ]:
# Step 3.67: Inspect the suspicious record using csv.reader

import csv
from pathlib import Path

raw_file = Path("../data/raw/free-text.csv")

with open(raw_file, "r", encoding="utf-8", newline="") as file:
    csv_reader = csv.reader(file)

    for record_number, row in enumerate(csv_reader):
        if record_number in range(23478, 23487):
            print(
                f"Logical record {record_number}: "
                f"{len(row)} fields"
            )
            print(row)
            print()

Logical record 23478: 10 fields
['p005', '1', 'c', 'h', '0.136', '0.417', '0.52', '0.281', '0.384', '']

Logical record 23479: 10 fields
['p005', '1', 'h', '-', '0.103', '0.608', '0.711', '0.505', '0.608', '']

Logical record 23480: 10 fields
['p005', '1', '-', '2', '0.103', '1', '1.103', '0.897', '1', '']

Logical record 23481: 10 fields
['p005', '1', '2', '2', '0.103', '0.192', '0.279', '0.089', '0.176', '']

Logical record 23482: 10 fields
['p005', '1', '2', ',0.087,1.088,1.183,1.001,1.096,\np005,1,', 'Shift', '0.095', '-0.472', '0.28', '-0.567', '0.185']

Logical record 23483: 10 fields
['p005', '1', 'Shift', 'Backspace', '0.752', '1.208', '1.272', '0.456', '0.52', '']

Logical record 23484: 10 fields
['p005', '1', 'Backspace', ':', '0.064', '0.336', '0.408', '0.272', '0.344', '']

Logical record 23485: 10 fields
['p005', '1', ':', 'Shift', '0.072', '-0.224', '0.216', '-0.296', '0.144', '']

Logical record 23486: 10 fields
['p005', '1', 'Shift', 'Space', '0.44', '0.8', '0.96', '0.36', '0.52', '']

In [ ]:
# Step 3.68: Compare the suspicious record with its neighbors

import csv
from pathlib import Path

raw_file = Path("../data/raw/free-text.csv")

target_record = 23482

with open(raw_file, "r", encoding="utf-8", newline="") as file:
    csv_reader = csv.reader(file)

    for record_number, row in enumerate(csv_reader):
        if target_record - 2 <= record_number <= target_record + 2:
            print(f"\nLogical record: {record_number}")
            print("Number of fields:", len(row))

            for column_number, value in enumerate(row):
                print(f"  Field {column_number}: {repr(value)}")

        if record_number > target_record + 2:
            break

Logical record: 23480
Number of fields: 10
  Field 0: 'p005'
  Field 1: '1'
  Field 2: '-'
  Field 3: '2'
  Field 4: '0.103'
  Field 5: '1'
  Field 6: '1.103'
  Field 7: '0.897'
  Field 8: '1'
  Field 9: ''

Logical record: 23481
Number of fields: 10
  Field 0: 'p005'
  Field 1: '1'
  Field 2: '2'
  Field 3: '2'
  Field 4: '0.103'
  Field 5: '0.192'
  Field 6: '0.279'
  Field 7: '0.089'
  Field 8: '0.176'
  Field 9: ''

Logical record: 23482
Number of fields: 10
  Field 0: 'p005'
  Field 1: '1'
  Field 2: '2'
  Field 3: ',0.087,1.088,1.183,1.001,1.096,\np005,1,'
  Field 4: 'Shift'
  Field 5: '0.095'
  Field 6: '-0.472'
  Field 7: '0.28'
  Field 8: '-0.567'
  Field 9: '0.185'

Logical record: 23483
Number of fields: 10
  Field 0: 'p005'
  Field 1: '1'
  Field 2: 'Shift'
  Field 3: 'Backspace'
  Field 4: '0.752'
  Field 5: '1.208'
  Field 6: '1.272'
  Field 7: '0.456'
  Field 8: '0.52'
  Field 9: ''

Logical record: 23484
Number of fields: 10
  Field 0: 'p005'
  Field 1: '1'
  Field 2: 'Backspace'
  Field 3: ':'
  Field 4: '0.064'
  Field 5: '0.336'
  Field 6: '0.408'
  Field 7: '0.272'
  Field 8: '0.344'
  Field 9: ''

In [ ]:
# Step 3.69: Display neighboring records without truncation

import csv
import pandas as pd
from pathlib import Path

raw_file = Path("../data/raw/free-text.csv")
target_record = 23482

records = []

with open(raw_file, "r", encoding="utf-8", newline="") as file:
    csv_reader = csv.reader(file)

    for record_number, row in enumerate(csv_reader):
        if target_record - 2 <= record_number <= target_record + 2:
            records.append({
                "logical_record": record_number,
                "number_of_fields": len(row),
                "participant": row[0],
                "session": row[1],
                "key1": row[2],
                "key2": row[3],
                "field_4": row[4],
                "field_5": row[5],
                "field_6": row[6],
                "field_7": row[7],
                "field_8": row[8],
                "field_9": row[9]
            })

        if record_number > target_record + 2:
            break

display(pd.DataFrame(records).to_string(index=False))

' logical_record  number_of_fields participant session      key1                                     key2 field_4 field_5 field_6 field_7 field_8 field_9\n          23480                10        p005       1         -                                        2   0.103       1   1.103   0.897       1        \n          23481                10        p005       1         2                                        2   0.103   0.192   0.279   0.089   0.176        \n          23482                10        p005       1         2 ,0.087,1.088,1.183,1.001,1.096,\\np005,1,   Shift   0.095  -0.472    0.28  -0.567   0.185\n          23483                10        p005       1     Shift                                Backspace   0.752   1.208   1.272   0.456    0.52        \n          23484                10        p005       1 Backspace                                        :   0.064   0.336   0.408   0.272   0.344        '

In [ ]:
# Step 3.70: Compare original CSV and DataFrame values

target_index = 23481

print("DATAFRAME RECORD")
display(df.loc[[target_index]])

print("\nORIGINAL CSV LOGICAL RECORD")

with open(raw_file, "r", encoding="utf-8", newline="") as file:
    csv_reader = csv.reader(file)

    for record_number, row in enumerate(csv_reader):
        # The header is logical record 0, so DataFrame index 23481
        # corresponds to logical CSV record 23482.
        if record_number == target_index + 1:
            for i, value in enumerate(row):
                print(f"Field {i}: {repr(value)}")
            break

DATAFRAME RECORD

,participant,session,key1,key2,DU.key1.key1,DD.key1.key2,DU.key1.key2,UD.key1.key2,UU.key1.key2,Unnamed: 9
23481,p005,1,2,",0.087,1.088,1.183,1.001,1.096,\np005,1,",Shift,0.095,-0.472,0.28,-0.567,0.185

ORIGINAL CSV LOGICAL RECORD
Field 0: 'p005'
Field 1: '1'
Field 2: '2'
Field 3: ',0.087,1.088,1.183,1.001,1.096,\np005,1,'
Field 4: 'Shift'
Field 5: '0.095'
Field 6: '-0.472'
Field 7: '0.28'
Field 8: '-0.567'
Field 9: '0.185'

In [ ]:
# Step 3.71: Search for quotation-mark keys in the free-text dataset

# Check the key columns for quotation marks
quote_in_key1 = df["key1"].astype(str).str.contains(
    '"', regex=False
)

quote_in_key2 = df["key2"].astype(str).str.contains(
    '"', regex=False
)

print("Quotation marks found in key1:", quote_in_key1.sum())
print("Quotation marks found in key2:", quote_in_key2.sum())

print("\nRows containing quotation marks in key columns:")

display(
    df.loc[
        quote_in_key1 | quote_in_key2,
        ["participant", "session", "key1", "key2"]
    ].head(20)
)

Quotation marks found in key1: 0
Quotation marks found in key2: 0

Rows containing quotation marks in key columns:

Empty DataFrame
Columns: [participant, session, key1, key2]
Index: []

In [ ]:
# Step 3.72: Summarize free-text dataset quality findings

free_text_quality_summary = pd.DataFrame({
    "check": [
        "Dataset dimensions",
        "Missing key2 values",
        "Rows with missing pair-timing values",
        "Non-numeric DU.key1.key1 values",
        "Rows with values in Unnamed: 9",
        "Rows with newlines in key2",
        "Negative timing values",
        "Affected participants"
    ],
    "finding": [
        f"{df.shape[0]} rows and {df.shape[1]} columns",
        int(df["key2"].isna().sum()),
        int(df[
            [
                "DD.key1.key2",
                "DU.key1.key2",
                "UD.key1.key2",
                "UU.key1.key2 "
            ]
        ].isna().all(axis=1).sum()),
        int(non_numeric_mask.sum()),
        int(df["Unnamed: 9"].notna().sum()),
        int(df["key2"].str.contains(
            "\n", regex=False, na=False
        ).sum()),
        int(
            df[
                [
                    "DU.key1.key1",
                    "DD.key1.key2",
                    "DU.key1.key2",
                    "UD.key1.key2",
                    "UU.key1.key2 "
                ]
            ]
            .apply(pd.to_numeric, errors="coerce")
            .lt(0)
            .any(axis=1)
            .sum()
        ),
        int(suspicious_records["participant"].nunique())
    ],
    "status": [
        "Verified",
        "Verified",
        "Verified",
        "Investigated; repair pending",
        "Investigated; repair pending",
        "Investigated; repair pending",
        "Requires semantic verification",
        "Verified"
    ]
})

display(free_text_quality_summary)

,check,finding,status
0,Dataset dimensions,562583 rows and 10 columns,Verified
1,Missing key2 values,198,Verified
2,Rows with missing pair-timing values,198,Verified
3,Non-numeric DU.key1.key1 values,13,Investigated; repair pending
4,Rows with values in Unnamed: 9,13,Investigated; repair pending
5,Rows with newlines in key2,13,Investigated; repair pending
6,Negative timing values,97929,Requires semantic verification
7,Affected participants,8,Verified

In [ ]:
# Step 3.73: Inspect negative values in free-text timing features

timing_columns = [
    "DU.key1.key1",
    "DD.key1.key2",
    "DU.key1.key2",
    "UD.key1.key2",
    "UU.key1.key2 "
]

# Convert timing features to numeric for analysis only
timing_numeric = df[timing_columns].apply(
    pd.to_numeric,
    errors="coerce"
)

# Count negative values in each timing feature
negative_counts = timing_numeric.lt(0).sum()

# Calculate minimum and maximum values
timing_ranges = timing_numeric.agg(["min", "max"]).T

# Combine the results
negative_summary = pd.DataFrame({
    "negative_value_count": negative_counts,
    "minimum_value": timing_ranges["min"],
    "maximum_value": timing_ranges["max"]
})

print("Negative values and ranges by timing feature:")
display(negative_summary)

Negative values and ranges by timing feature:

               negative_value_count  minimum_value  maximum_value
DU.key1.key1                      0          0.000        568.570
DD.key1.key2                   8526       -568.083       1712.727
DU.key1.key2                     16         -7.935       1713.061
UD.key1.key2                  97919       -568.162       1712.648
UU.key1.key2                     17        -10.782       1712.982

In [ ]:
# Step 3.74: Identify extreme timing values in the free-text dataset

# Use numeric timing values already created in Step 3.73
absolute_timing = timing_numeric.abs()

# Find the maximum absolute timing value in each row
max_absolute_value = absolute_timing.max(axis=1)

# Select the 10 rows with the largest absolute values
top_extreme_indices = max_absolute_value.nlargest(10).index

# Display identifiers and timing values
extreme_records = df.loc[
    top_extreme_indices,
    ["participant", "session", "key1", "key2"]
].copy()

# Add the absolute maximum for each selected row
extreme_records["max_absolute_timing"] = (
    max_absolute_value.loc[top_extreme_indices]
)

# Add the timing features for investigation
for column in timing_columns:
    extreme_records[column] = timing_numeric.loc[
        top_extreme_indices, column
    ]

print("Top 10 records with the largest absolute timing values:")
display(extreme_records)

Top 10 records with the largest absolute timing values:

,participant,session,key1,key2,max_absolute_timing,DU.key1.key1,DD.key1.key2,DU.key1.key2,UD.key1.key2,UU.key1.key2
281255,p050,2,Space,Shift,1713.061,0.079,1712.727,1713.061,1712.648,1712.982
279007,p050,1,n,Space,1482.148,0.068,1482.061,1482.148,1481.993,1482.080
224298,p041,1,Backspace,CapsLock,1292.591,0.100,1292.476,1292.591,1292.376,1292.491
79620,p015,1,Space,T,1067.746,0.088,1067.658,1067.746,1067.570,1067.658
213589,p039,1,Shift,Shift,781.129,0.327,780.867,781.129,780.540,780.802
499175,p088,2,Space,s,696.319,0.095,696.208,696.319,696.113,696.224
490969,p087,1,Space,Shift,671.848,0.095,671.597,671.848,671.502,671.753
428090,p076,1,s,Space,657.289,0.087,657.177,657.289,657.090,657.202
541907,p097,1,Meta,Meta,569.068,568.570,202.461,569.068,-366.109,0.498
541906,p097,1,n,Meta,568.162,0.079,-568.083,0.487,-568.162,0.408

In [ ]:
# Step 3.75: Count records with extreme timing values

thresholds = [10, 100, 500]

extreme_counts = {}

for threshold in thresholds:

    mask = absolute_timing.gt(threshold).any(axis=1)

    extreme_counts[f"Absolute timing > {threshold} seconds"] = {
        "record_count": int(mask.sum()),
        "percentage": round(mask.mean() * 100, 4)
    }

extreme_summary = pd.DataFrame(extreme_counts).T

print("Records containing extreme timing values:")
display(extreme_summary)

Records containing extreme timing values:

                               record_count  percentage
Absolute timing > 10 seconds         2888.0      0.5133
Absolute timing > 100 seconds         232.0      0.0412
Absolute timing > 500 seconds          10.0      0.0018

In [ ]:
# Step 3.76: Inspect records with extreme timing values

extreme_mask_100 = absolute_timing.gt(100).any(axis=1)

extreme_records_100 = df.loc[extreme_mask_100].copy()

print("Records with at least one absolute timing value > 100 seconds:")
print("Number of records:", len(extreme_records_100))

# Display participant, session, and key information
display(
    extreme_records_100[
        ["participant", "session", "key1", "key2"]
    ].head(20)
)

Records with at least one absolute timing value > 100 seconds:
Number of records: 232

       participant  session       key1   key2
20567         p004        1          s      .
20568         p004        1          .      ,
20820         p004        2      Space  Space
20821         p004        2      Space  Space
20822         p004        2      Space  Space
20823         p004        2      Space    NaN
27539         p006        1  Backspace  Shift
39531         p008        1      Space      T
52646         p010        2      Space      b
79620         p015        1      Space      T
92320         p017        1          u      '
92321         p017        1          '  Shift
101809        p019        1      Space      I
102176        p019        1      Space  Shift
103182        p019        1          t      '
103183        p019        1          '      '
103509        p019        1          s      .
103510        p019        1          .  Space
104911        p019        2          u      '
104912        p019        2          '      l

In [ ]:
# Step 3.77: Count extreme values in each timing feature

extreme_feature_counts = (
    absolute_timing.gt(100)
    .sum()
    .sort_values(ascending=False)
)

extreme_feature_summary = pd.DataFrame({
    "Extreme values > 100 seconds": extreme_feature_counts
})

display(extreme_feature_summary)

               Extreme values > 100 seconds
DD.key1.key2                            218
DU.key1.key2                            144
UD.key1.key2                            139
DU.key1.key1                            103
UU.key1.key2                             38

In [ ]:
# Step 3.78: Count extreme timing features in each record

extreme_mask_100 = absolute_timing.gt(100)

extreme_records_summary = pd.DataFrame({
    "participant": df["participant"],
    "session": df["session"],
    "key1": df["key1"],
    "key2": df["key2"],
    "extreme_feature_count": extreme_mask_100.sum(axis=1),
    "maximum_absolute_timing": absolute_timing.max(axis=1)
})

# Keep only records with at least one extreme timing value
extreme_records_summary = extreme_records_summary[
    extreme_records_summary["extreme_feature_count"] > 0
].copy()

# Show records with the most extreme features first
extreme_records_summary = extreme_records_summary.sort_values(
    by=["extreme_feature_count", "maximum_absolute_timing"],
    ascending=False
)

print("Total affected records:", len(extreme_records_summary))

print("\nNumber of extreme features per record:")
display(
    extreme_records_summary["extreme_feature_count"]
    .value_counts()
    .sort_index()
    .rename_axis("Extreme features in one record")
    .reset_index(name="Number of records")
)

print("\nTop 15 records requiring investigation:")
display(extreme_records_summary.head(15))

Total affected records: 232

Number of extreme features per record:

   Extreme features in one record  Number of records
0                               1                  2
1                               2                 91
2                               3                 98
3                               4                 41

Top 15 records requiring investigation:

,participant,session,key1,key2,extreme_feature_count,maximum_absolute_timing
281255,p050,2,Space,Shift,4,1713.061
279007,p050,1,n,Space,4,1482.148
224298,p041,1,Backspace,CapsLock,4,1292.591
79620,p015,1,Space,T,4,1067.746
213589,p039,1,Shift,Shift,4,781.129
499175,p088,2,Space,s,4,696.319
490969,p087,1,Space,Shift,4,671.848
428090,p076,1,s,Space,4,657.289
541907,p097,1,Meta,Meta,4,569.068
404000,p071,2,",",Space,4,393.391
259425,p047,1,Space,I,4,389.053
406941,p072,2,s,.,4,386.916
203923,p037,2,e,Space,4,386.393
406471,p072,1,Space,I,4,382.287
541909,p097,1,Meta,Meta,4,359.244

In [ ]:
# Step 3.79A: Summarize free-text data-quality findings

suspicious_mask = (
    df["Unnamed: 9"].notna()
    | df["key2"].astype(str).str.contains("\n", regex=False)
    | pd.to_numeric(
        df["DU.key1.key1"], errors="coerce"
    ).isna()
)

missing_pair_mask = df[
    [
        "key2",
        "DD.key1.key2",
        "DU.key1.key2",
        "UD.key1.key2",
        "UU.key1.key2 "
    ]
].isna().all(axis=1)

extreme_mask_100 = absolute_timing.gt(100).any(axis=1)

filtering_summary = pd.DataFrame({
    "Issue": [
        "Suspicious records",
        "Rows with all pair-timing fields missing",
        "Records with an absolute timing value above 100 seconds",
        "Records with an absolute timing value above 500 seconds"
    ],
    "Affected records": [
        int(suspicious_mask.sum()),
        int(missing_pair_mask.sum()),
        int(extreme_mask_100.sum()),
        int(absolute_timing.gt(500).any(axis=1).sum())
    ],
    "Planned action": [
        "Exclude from modelling copy if unresolved",
        "Investigate and handle separately",
        "Investigate before filtering",
        "Investigate before filtering"
    ]
})

display(filtering_summary)

,Issue,Affected records,Planned action
0,Suspicious records,13,Exclude from modelling copy if unresolved
1,Rows with all pair-timing fields missing,198,Investigate and handle separately
2,Records with an absolute timing value above 10...,232,Investigate before filtering
3,Records with an absolute timing value above 50...,10,Investigate before filtering

In [ ]:
# Step 3.79B: Inspect rows with missing pair-timing information

missing_pair_records = df.loc[
    missing_pair_mask,
    ["participant", "session", "key1", "key2"]
].copy()

print("Rows with missing pair information:", len(missing_pair_records))

print("\nMissing pair rows by session:")
display(missing_pair_records["session"].value_counts().sort_index())

print("\nFirst 10 affected rows:")
display(missing_pair_records.head(10))

Rows with missing pair information: 198

Missing pair rows by session:

session
1    99
2    99
Name: count, dtype: int64

First 10 affected rows:

      participant  session   key1 key2
2513         p001        1      e  NaN
5257         p001        2      s  NaN
7959         p002        1      e  NaN
10774        p002        2      s  NaN
13367        p003        1      e  NaN
16085        p003        2      r  NaN
20785        p004        1      .  NaN
20823        p004        2  Space  NaN
24119        p005        1      e  NaN
27529        p005        2      s  NaN

In [ ]:
# Step 3.80: Check whether missing pair-timing rows are terminal records

df_check = df.copy()

df_check["original_row_order"] = range(len(df_check))

missing_pair_records = df_check.loc[
    missing_pair_mask,
    ["participant", "session", "key1", "key2", "original_row_order"]
].copy()

last_row_indices = (
    df_check.groupby(["participant", "session"])["original_row_order"]
    .max()
    .reset_index(name="last_row_order")
)

check_result = missing_pair_records.merge(
    last_row_indices,
    on=["participant", "session"],
    how="left"
)

check_result["is_last_row"] = (
    check_result["original_row_order"]
    == check_result["last_row_order"]
)

print("Total rows with missing pair information:", len(check_result))
print("Rows that are the last row of their participant-session:",
      int(check_result["is_last_row"].sum()))
print("Rows that are NOT the last row:",
      int((~check_result["is_last_row"]).sum()))

display(check_result.head(10))

Total rows with missing pair information: 198
Rows that are the last row of their participant-session: 198
Rows that are NOT the last row: 0

,participant,session,key1,key2,original_row_order,last_row_order,is_last_row
0,p001,1,e,NaN,2513,2513,True
1,p001,2,s,NaN,5257,5257,True
2,p002,1,e,NaN,7959,7959,True
3,p002,2,s,NaN,10774,10774,True
4,p003,1,e,NaN,13367,13367,True
5,p003,2,r,NaN,16085,16085,True
6,p004,1,.,NaN,20785,20785,True
7,p004,2,Space,NaN,20823,20823,True
8,p005,1,e,NaN,24119,24119,True
9,p005,2,s,NaN,27529,27529,True

In [ ]:
# Step 3.81: Inspect suspicious records before cleaning

suspicious_mask = (
    df["Unnamed: 9"].notna()
    | df["key2"].astype(str).str.contains("\n", regex=False)
    | pd.to_numeric(df["DU.key1.key1"], errors="coerce").isna()
)

suspicious_records = df.loc[
    suspicious_mask,
    [
        "participant",
        "session",
        "key1",
        "key2",
        "DU.key1.key1",
        "DD.key1.key2",
        "DU.key1.key2",
        "UD.key1.key2",
        "UU.key1.key2 ",
        "Unnamed: 9"
    ]
].copy()

print("Number of suspicious records:", len(suspicious_records))

display(suspicious_records)

Number of suspicious records: 13

,participant,session,key1,key2,DU.key1.key1,DD.key1.key2,DU.key1.key2,UD.key1.key2,UU.key1.key2,Unnamed: 9
23481,p005,1,2,",0.087,1.088,1.183,1.001,1.096,\np005,1,",Shift,0.095,-0.472,0.280,-0.567,0.185
169381,p031,1,Backspace,",0.081,0.761,0.896,0.68,0.815,\np031,1,",Shift,0.135,-0.341,0.177,-0.476,0.042
177980,p033,1,e,",0.088,0.2,0.28,0.112,0.192\np033,1,",Backspace,0.080,0.400,0.544,0.320,0.464
181842,p033,2,t,",0.079,0.184,0.263,0.105,0.184,\np033,2,",Shift,0.079,-0.041,0.151,-0.120,0.072
204716,p037,2,Backspace,",0.134,0.281,0.502,0.147,0.368,\np037,2,",Backspace,0.221,0.342,0.501,0.121,0.280
205245,p037,2,Backspace,",0.166,0.569,0.726,0.403,0.56,\np037,2,",Backspace,0.157,0.319,0.502,0.162,0.345
306776,p055,1,Backspace,",0.123,0.785,0.87,0.662,0.747,\np055,1,",Shift,0.085,-0.168,0.150,-0.253,0.065
319078,p057,1,y,",0.137,0.304,0.49,0.167,0.353,\np057,1,",Shift,0.186,-0.047,0.517,-0.233,0.331
491603,p087,1,Backspace,",0.096,6.082,6.177,5.986,6.081,\np087,1,",Shift,0.095,-0.289,0.159,-0.384,0.064
491610,p087,1,Shift,",0.472,1.76,1.888,1.288,1.416,\np087,1,",Shift,0.128,-0.352,0.248,-0.480,0.120
491613,p087,1,Backspace,",0.096,0.8,0.896,0.704,0.8,\np087,1,",Shift,0.096,-0.192,0.288,-0.288,0.192
552060,p099,1,Shift,",0.0,0.06,0.229,0.06,0.229,\np099,1,",Shift,0.169,-0.029,0.423,-0.198,0.254
552098,p099,1,Shift,",0.0,0.033,0.192,0.033,0.192,\np099,1,",Shift,0.159,-0.002,0.487,-0.161,0.328

In [ ]:
# Step 3.82: Create a cleaned copy of the free-text dataset

# Start with a copy of the original dataset
df_free_clean = df.copy()

# Identify suspicious records
suspicious_mask = (
    df_free_clean["Unnamed: 9"].notna()
    | df_free_clean["key2"].astype(str).str.contains("\n", regex=False)
    | pd.to_numeric(
        df_free_clean["DU.key1.key1"],
        errors="coerce"
    ).isna()
)

# Remove suspicious records from the copy only
df_free_clean = df_free_clean.loc[~suspicious_mask].copy()

# Convert timing columns to numeric values
free_timing_columns = [
    "DU.key1.key1",
    "DD.key1.key2",
    "DU.key1.key2",
    "UD.key1.key2",
    "UU.key1.key2 "
]

for column in free_timing_columns:
    df_free_clean[column] = pd.to_numeric(
        df_free_clean[column],
        errors="coerce"
    )

# Reset the row index
df_free_clean.reset_index(drop=True, inplace=True)

print("Original dataset shape:", df.shape)
print("Cleaned dataset shape:", df_free_clean.shape)
print("Records removed:", len(df) - len(df_free_clean))

print("\nRemaining non-numeric timing values:")
display(
    df_free_clean[free_timing_columns]
    .isna()
    .sum()
    .to_frame(name="Missing values")
)

Original dataset shape: (562583, 10)
Cleaned dataset shape: (562570, 10)
Records removed: 13

Remaining non-numeric timing values:

               Missing values
DU.key1.key1                0
DD.key1.key2              198
DU.key1.key2              198
UD.key1.key2              198
UU.key1.key2              198

In [ ]:
# Step 3.83: Validate the cleaned free-text dataset

print("CLEANED DATASET VALIDATION")
print("-" * 40)

print("Cleaned dataset shape:", df_free_clean.shape)

print("\nUnique participants:",
      df_free_clean["participant"].nunique())

print("Available sessions:",
      sorted(df_free_clean["session"].unique()))

# Check for suspicious records again
remaining_suspicious = (
    df_free_clean["Unnamed: 9"].notna()
    | df_free_clean["key2"].astype(str).str.contains("\n", regex=False)
    | pd.to_numeric(
        df_free_clean["DU.key1.key1"],
        errors="coerce"
    ).isna()
)

print("\nRemaining suspicious records:",
      int(remaining_suspicious.sum()))

# Check timing-column data types
print("\nTiming column data types:")
display(df_free_clean[free_timing_columns].dtypes.to_frame("Data type"))

# Confirm the original data has not been changed
print("\nOriginal dataset shape remains:", df.shape)

CLEANED DATASET VALIDATION
----------------------------------------
Cleaned dataset shape: (562570, 10)

Unique participants: 99
Available sessions: [np.int64(1), np.int64(2)]

Remaining suspicious records: 0

Timing column data types:

              Data type
DU.key1.key1    float64
DD.key1.key2    float64
DU.key1.key2    float64
UD.key1.key2    float64
UU.key1.key2    float64

Original dataset shape remains: (562583, 10)

In [ ]:
# Step 3.84: Save the cleaned free-text dataset

from pathlib import Path

# Find the project root
project_root = Path.cwd().parent

# Create the processed-data folder if it doesn't exist
processed_dir = project_root / "data" / "processed"
processed_dir.mkdir(parents=True, exist_ok=True)

# Define the output file
free_output_path = processed_dir / "free_text_cleaned.csv"

# Save the cleaned dataset
df_free_clean.to_csv(free_output_path, index=False)

print("Cleaned free-text dataset saved successfully!")
print("File location:", free_output_path)
print("Saved records:", len(df_free_clean))
print("Saved columns:", len(df_free_clean.columns))
print("File exists:", free_output_path.exists())

Cleaned free-text dataset saved successfully!
File location: c:\Users\LOQ\OneDrive\Desktop\Komal_clg\5th sem\DL Lab\Project\DeepKey_DL_Project\data\processed\free_text_cleaned.csv
Saved records: 562570
Saved columns: 10
File exists: True

In [ ]:
# Step 3.85: Check the fixed-text dataset before cleaning

print("FIXED-TEXT DATASET SUMMARY")
print("-" * 40)

print("Dataset shape:", df_fixed.shape)

print("\nUnique participants:",
      df_fixed["participant"].nunique())

print("Available sessions:",
      sorted(df_fixed["session"].unique()))

print("\nMissing values:", df_fixed.isna().sum().sum())

print("Duplicate rows:", df_fixed.duplicated().sum())

print("\nColumn data types:")
display(df_fixed.dtypes.value_counts().to_frame("Number of columns"))

print("\nFirst five records:")
display(df_fixed.head())

FIXED-TEXT DATASET SUMMARY
----------------------------------------
Dataset shape: (19772, 50)

Unique participants: 99
Available sessions: [np.int64(1), np.int64(2)]

Missing values: 0
Duplicate rows: 0

Column data types:

         Number of columns
float64                 47
int64                    2
str                      1

First five records:

,participant,session,repetition,DU.v.v,DD.v.p,DU.v.p,UD.v.p,UU.v.p,DU.p.p,DD.p.w,...,DU.r.k,UD.r.k,UU.r.k,DU.k.k.1,DD.k.b,DU.k.b,UD.k.b,UU.k.b,DU.b.b,total time
0,p001,1,1,0.129,1.917,1.804,2.046,1.933,0.113,0.719,...,1.289,1.509,1.423,0.086,0.450,0.352,0.536,0.438,0.098,10.101
1,p001,1,2,0.112,0.192,0.096,0.304,0.208,0.096,0.448,...,0.921,1.135,1.056,0.079,0.418,0.336,0.497,0.415,0.082,5.768
2,p001,1,3,0.088,0.253,0.182,0.341,0.270,0.071,1.536,...,1.066,1.271,1.194,0.077,0.448,0.352,0.525,0.429,0.096,7.877
3,p001,1,4,0.104,0.323,0.233,0.427,0.337,0.090,0.912,...,0.927,1.129,1.063,0.066,0.418,0.330,0.484,0.396,0.088,5.443
4,p001,1,5,0.107,0.188,0.100,0.295,0.207,0.088,0.858,...,1.237,1.423,1.344,0.079,0.457,0.369,0.536,0.448,0.088,5.284

In [ ]:
# Step 3.86: Inspect potentially anomalous fixed-text records

records_to_check = [
    ("p020", 2, 4),
    ("p071", 1, 20),
    ("p087", 1, 8)
]

for participant_id, session_id, repetition_id in records_to_check:

    print("\n" + "=" * 70)
    print(
        f"Participant: {participant_id} | "
        f"Session: {session_id} | "
        f"Repetition: {repetition_id}"
    )
    print("=" * 70)

    # Select nearby repetitions from the same participant and session
    nearby_records = df_fixed[
        (df_fixed["participant"] == participant_id)
        & (df_fixed["session"] == session_id)
        & (
            df_fixed["repetition"].between(
                repetition_id - 2,
                repetition_id + 2
            )
        )
    ].sort_values("repetition")

    display(nearby_records)

======================================================================
Participant: p020 | Session: 2 | Repetition: 4
======================================================================

,participant,session,repetition,DU.v.v,DD.v.p,DU.v.p,UD.v.p,UU.v.p,DU.p.p,DD.p.w,...,DU.r.k,UD.r.k,UU.r.k,DU.k.k.1,DD.k.b,DU.k.b,UD.k.b,UU.k.b,DU.b.b,total time
3898,p020,2,2,0.092,0.085,-0.007,0.177,0.085,0.092,0.109,...,0.392,0.558,0.472,0.086,0.066,-0.023,0.152,0.063,0.089,1.294
3899,p020,2,3,0.113,0.079,-0.040,0.192,0.073,0.119,0.114,...,2.591,2.743,2.667,0.076,0.134,0.051,0.210,0.127,0.083,3.462
3900,p020,2,4,0.118,0.299,0.226,0.417,0.344,0.073,0.169,...,1077834.017,1077834.204,1077834.115,0.089,-1077833.679,-1077833.774,-1077833.590,-1077833.685,0.095,-1077832.627
3901,p020,2,5,0.132,0.071,-0.043,0.203,0.089,0.114,0.159,...,1.042,1.216,1.123,0.093,0.218,0.130,0.311,0.223,0.088,2.180
3902,p020,2,6,0.099,0.088,-0.003,0.187,0.096,0.091,0.131,...,0.191,0.379,0.301,0.078,0.133,0.046,0.211,0.124,0.087,1.165

======================================================================
Participant: p071 | Session: 1 | Repetition: 20
======================================================================

,participant,session,repetition,DU.v.v,DD.v.p,DU.v.p,UD.v.p,UU.v.p,DU.p.p,DD.p.w,...,DU.r.k,UD.r.k,UU.r.k,DU.k.k.1,DD.k.b,DU.k.b,UD.k.b,UU.k.b,DU.b.b,total time
14001,p071,1,18,0.160,0.112,-0.080,0.272,0.080,0.192,0.704,...,0.448,0.720,0.592,0.128,0.192,0.032,0.320,0.160,0.160,2.816
14002,p071,1,19,0.176,0.096,-0.112,0.272,0.064,0.208,0.768,...,0.688,0.960,0.848,0.112,0.128,0.001,0.240,0.113,0.127,4.385
14003,p071,1,20,0.144,0.080,-0.048,0.224,0.096,0.128,0.544,...,0.544,0.769,0.657,0.112,0.192,0.064,0.304,0.176,0.128,647.964
14004,p071,1,21,0.144,0.144,0.016,0.288,0.160,0.128,0.256,...,0.159,0.400,0.271,0.129,0.256,0.160,0.385,0.289,0.096,2.176
14005,p071,1,22,0.144,0.224,0.048,0.368,0.192,0.176,0.464,...,0.256,0.480,0.368,0.112,0.080,0.064,0.192,0.176,0.016,2.032

======================================================================
Participant: p087 | Session: 1 | Repetition: 8
======================================================================

,participant,session,repetition,DU.v.v,DD.v.p,DU.v.p,UD.v.p,UU.v.p,DU.p.p,DD.p.w,...,DU.r.k,UD.r.k,UU.r.k,DU.k.k.1,DD.k.b,DU.k.b,UD.k.b,UU.k.b,DU.b.b,total time
17183,p087,1,6,0.128,0.160,0.032,0.288,0.160,0.128,0.928,...,0.512,0.736,0.608,0.128,0.192,0.065,0.320,0.193,0.127,3.297
17184,p087,1,7,0.096,0.128,0.064,0.224,0.160,0.064,0.672,...,0.320,0.479,0.415,0.064,0.160,0.001,0.224,0.065,0.159,3.585
17185,p087,1,8,0.119,0.128,0.073,0.247,0.192,0.055,0.648,...,0.832,1.056,0.928,0.128,332.701,332.605,332.829,332.733,0.096,335.526
17186,p087,1,9,0.096,0.608,0.512,0.704,0.608,0.096,0.480,...,0.609,0.800,0.705,0.095,0.128,0.065,0.223,0.160,0.063,3.009
17187,p087,1,10,0.096,0.128,0.064,0.224,0.160,0.064,1.632,...,0.649,0.800,0.704,0.096,0.064,0.000,0.160,0.096,0.064,4.105

In [ ]:
# Step 3.87: Identify extreme timing features in the three records

metadata_columns = ["participant", "session", "repetition", "total time"]

timing_columns_fixed = [
    column for column in df_fixed.columns
    if column not in metadata_columns
]

records_to_check = [
    ("p020", 2, 4),
    ("p071", 1, 20),
    ("p087", 1, 8)
]

for participant_id, session_id, repetition_id in records_to_check:

    record = df_fixed[
        (df_fixed["participant"] == participant_id)
        & (df_fixed["session"] == session_id)
        & (df_fixed["repetition"] == repetition_id)
    ]

    print(
        f"\n{participant_id} | Session {session_id} "
        f"| Repetition {repetition_id}"
    )

    if record.empty:
        print("Record not found.")
        continue

    timing_values = record[timing_columns_fixed].iloc[0]

    extreme_values = timing_values[
        timing_values.abs() > 100
    ]

    if extreme_values.empty:
        print("No timing feature exceeds 100 seconds.")
    else:
        display(
            extreme_values
            .rename("Timing value")
            .to_frame()
        )

    print("Total time:", record["total time"].iloc[0])

p020 | Session 2 | Repetition 4

        Timing value
DD.j.k  -1077833.670
DU.j.k  -1077833.755
UD.j.k  -1077833.601
UU.j.k  -1077833.686
DU.k.e   1077833.851
UU.k.e   1077833.936
DU.e.e   1077834.425
UD.e.u  -1077834.250
UU.e.u  -1077834.328
DD.r.k   1077834.106
DU.r.k   1077834.017
UD.r.k   1077834.204
UU.r.k   1077834.115
DD.k.b  -1077833.679
DU.k.b  -1077833.774
UD.k.b  -1077833.590
UU.k.b  -1077833.685

Total time: -1077832.627

p071 | Session 1 | Repetition 20

        Timing value
DD.j.k       645.836
DU.j.k       645.724
UD.j.k       645.996
UU.j.k       645.884

Total time: 647.964

p087 | Session 1 | Repetition 8

        Timing value
DD.k.b       332.701
DU.k.b       332.605
UD.k.b       332.829
UU.k.b       332.733

Total time: 335.526

In [ ]:
# Step 3.88: Create a cleaned copy of the fixed-text dataset

# Make a separate copy of the original dataset
df_fixed_clean = df_fixed.copy()

# Identify the clearly invalid record
invalid_record_mask = (
    (df_fixed_clean["participant"] == "p020")
    & (df_fixed_clean["session"] == 2)
    & (df_fixed_clean["repetition"] == 4)
)

# Count records before removal
original_count = len(df_fixed_clean)

# Remove the invalid record from the copy
df_fixed_clean = df_fixed_clean.loc[
    ~invalid_record_mask
].copy()

# Reset the index
df_fixed_clean.reset_index(drop=True, inplace=True)

print("FIXED-TEXT CLEANING SUMMARY")
print("-" * 40)

print("Original records:", original_count)
print("Cleaned records:", len(df_fixed_clean))
print("Records removed:", original_count - len(df_fixed_clean))

print("\nRemaining missing values:",
      df_fixed_clean.isna().sum().sum())

print("Remaining duplicate rows:",
      df_fixed_clean.duplicated().sum())

print("\nOriginal dataset shape:", df_fixed.shape)
print("Cleaned dataset shape:", df_fixed_clean.shape)

FIXED-TEXT CLEANING SUMMARY
----------------------------------------
Original records: 19772
Cleaned records: 19771
Records removed: 1

Remaining missing values: 0
Remaining duplicate rows: 0

Original dataset shape: (19772, 50)
Cleaned dataset shape: (19771, 50)

In [ ]:
# Step 3.89: Validate the cleaned fixed-text dataset

print("CLEANED FIXED-TEXT VALIDATION")
print("-" * 40)

print("Dataset shape:", df_fixed_clean.shape)

print("\nUnique participants:",
      df_fixed_clean["participant"].nunique())

print("Available sessions:",
      sorted(df_fixed_clean["session"].unique()))

print("\nMissing values:",
      df_fixed_clean.isna().sum().sum())

print("Duplicate rows:",
      df_fixed_clean.duplicated().sum())

# Confirm the invalid record was removed
invalid_record_remaining = (
    (df_fixed_clean["participant"] == "p020")
    & (df_fixed_clean["session"] == 2)
    & (df_fixed_clean["repetition"] == 4)
).sum()

print("\nInvalid p020 record remaining:",
      int(invalid_record_remaining))

# Confirm the original dataset is unchanged
print("\nOriginal dataset shape:", df_fixed.shape)

CLEANED FIXED-TEXT VALIDATION
----------------------------------------
Dataset shape: (19771, 50)

Unique participants: 99
Available sessions: [np.int64(1), np.int64(2)]

Missing values: 0
Duplicate rows: 0

Invalid p020 record remaining: 0

Original dataset shape: (19772, 50)

In [ ]:
# Step 3.90: Save the cleaned fixed-text dataset

from pathlib import Path

# Locate the project root
project_root = Path.cwd().parent

# Create the processed-data directory if necessary
processed_dir = project_root / "data" / "processed"
processed_dir.mkdir(parents=True, exist_ok=True)

# Define the output file
fixed_output_path = processed_dir / "fixed_text_cleaned.csv"

# Save the cleaned dataset without the notebook index
df_fixed_clean.to_csv(fixed_output_path, index=False)

print("Cleaned fixed-text dataset saved successfully!")
print("File location:", fixed_output_path)
print("Saved records:", len(df_fixed_clean))
print("Saved columns:", len(df_fixed_clean.columns))
print("File exists:", fixed_output_path.exists())

Cleaned fixed-text dataset saved successfully!
File location: c:\Users\LOQ\OneDrive\Desktop\Komal_clg\5th sem\DL Lab\Project\DeepKey_DL_Project\data\processed\fixed_text_cleaned.csv
Saved records: 19771
Saved columns: 50
File exists: True

In [ ]:
# Step 3.91: Load the saved cleaned fixed-text dataset

import pandas as pd
from pathlib import Path

# Locate the project root
project_root = Path.cwd().parent

# Path to the saved cleaned dataset
fixed_path = (
    project_root
    / "data"
    / "processed"
    / "fixed_text_cleaned.csv"
)

# Load the dataset
df_fixed_clean = pd.read_csv(fixed_path)

print("Saved dataset loaded successfully!")
print("Dataset shape:", df_fixed_clean.shape)

print("\nFirst five records:")
display(df_fixed_clean.head())

print("\nColumn names:")
print(df_fixed_clean.columns.tolist())

Saved dataset loaded successfully!
Dataset shape: (19771, 50)

First five records:

,participant,session,repetition,DU.v.v,DD.v.p,DU.v.p,UD.v.p,UU.v.p,DU.p.p,DD.p.w,...,DU.r.k,UD.r.k,UU.r.k,DU.k.k.1,DD.k.b,DU.k.b,UD.k.b,UU.k.b,DU.b.b,total time
0,p001,1,1,0.129,1.917,1.804,2.046,1.933,0.113,0.719,...,1.289,1.509,1.423,0.086,0.450,0.352,0.536,0.438,0.098,10.101
1,p001,1,2,0.112,0.192,0.096,0.304,0.208,0.096,0.448,...,0.921,1.135,1.056,0.079,0.418,0.336,0.497,0.415,0.082,5.768
2,p001,1,3,0.088,0.253,0.182,0.341,0.270,0.071,1.536,...,1.066,1.271,1.194,0.077,0.448,0.352,0.525,0.429,0.096,7.877
3,p001,1,4,0.104,0.323,0.233,0.427,0.337,0.090,0.912,...,0.927,1.129,1.063,0.066,0.418,0.330,0.484,0.396,0.088,5.443
4,p001,1,5,0.107,0.188,0.100,0.295,0.207,0.088,0.858,...,1.237,1.423,1.344,0.079,0.457,0.369,0.536,0.448,0.088,5.284

Column names:
['participant', 'session', 'repetition', 'DU.v.v', 'DD.v.p', 'DU.v.p', 'UD.v.p', 'UU.v.p', 'DU.p.p', 'DD.p.w', 'DU.p.w', 'UD.p.w', 'UU.p.w', 'DU.w.w', 'DD.w.j', 'DU.w.j', 'UD.w.j', 'UU.w.j', 'DU.j.j', 'DD.j.k', 'DU.j.k', 'UD.j.k', 'UU.j.k', 'DU.k.k', 'DD.k.e', 'DU.k.e', 'UD.k.e', 'UU.k.e', 'DU.e.e', 'DD.e.u', 'DU.e.u', 'UD.e.u', 'UU.e.u', 'DU.u.u', 'DD.u.r', 'DU.u.r', 'UD.u.r', 'UU.u.r', 'DU.r.r', 'DD.r.k', 'DU.r.k', 'UD.r.k', 'UU.r.k', 'DU.k.k.1', 'DD.k.b', 'DU.k.b', 'UD.k.b', 'UU.k.b', 'DU.b.b', 'total time']

In [ ]:
# Step 3.92: Identify feature and metadata columns

# Target column
target_column = "participant"

# Metadata columns that should not be model inputs
metadata_columns = [
    "participant",
    "session",
    "repetition"
]

# Timing columns available for feature selection
timing_feature_columns = [
    column
    for column in df_fixed_clean.columns
    if column not in metadata_columns + ["total time"]
]

print("Target column:", target_column)

print("\nNumber of timing features:",
      len(timing_feature_columns))

print("\nTiming feature columns:")
print(timing_feature_columns)

print("\nNumber of participants:",
      df_fixed_clean[target_column].nunique())

print("\nRecords per participant — summary:")
display(
    df_fixed_clean.groupby(target_column).size().describe()
)

Target column: participant

Number of timing features: 46

Timing feature columns:
['DU.v.v', 'DD.v.p', 'DU.v.p', 'UD.v.p', 'UU.v.p', 'DU.p.p', 'DD.p.w', 'DU.p.w', 'UD.p.w', 'UU.p.w', 'DU.w.w', 'DD.w.j', 'DU.w.j', 'UD.w.j', 'UU.w.j', 'DU.j.j', 'DD.j.k', 'DU.j.k', 'UD.j.k', 'UU.j.k', 'DU.k.k', 'DD.k.e', 'DU.k.e', 'UD.k.e', 'UU.k.e', 'DU.e.e', 'DD.e.u', 'DU.e.u', 'UD.e.u', 'UU.e.u', 'DU.u.u', 'DD.u.r', 'DU.u.r', 'UD.u.r', 'UU.u.r', 'DU.r.r', 'DD.r.k', 'DU.r.k', 'UD.r.k', 'UU.r.k', 'DU.k.k.1', 'DD.k.b', 'DU.k.b', 'UD.k.b', 'UU.k.b', 'DU.b.b']

Number of participants: 99

Records per participant — summary:

count     99.000000
mean     199.707071
std        1.090333
min      194.000000
25%      200.000000
50%      200.000000
75%      200.000000
max      206.000000
dtype: float64

In [ ]:
# Step 3.93: Inspect timing feature statistics

timing_summary = df_fixed_clean[timing_feature_columns].describe().T

timing_summary = timing_summary[
    ["mean", "std", "min", "25%", "50%", "75%", "max"]
]

display(timing_summary.round(3))

           mean    std    min    25%    50%    75%      max
DU.v.v    0.097  0.031  0.001  0.078  0.093  0.112    0.965
DD.v.p    0.263  0.609 -0.061  0.136  0.195  0.291   76.414
DU.v.p    0.168  0.609 -0.172  0.041  0.098  0.200   76.321
UD.v.p    0.360  0.609  0.004  0.232  0.295  0.388   76.451
UU.v.p    0.265  0.609  0.001  0.139  0.199  0.293   76.358
DU.p.p    0.095  0.030  0.001  0.075  0.090  0.111    0.250
DD.p.w    0.405  0.826 -6.965  0.177  0.265  0.449   67.362
DU.p.w    0.303  0.826 -7.064  0.076  0.160  0.349   67.254
UD.p.w    0.501  0.826 -6.889  0.274  0.363  0.544   67.418
UU.p.w    0.398  0.826 -6.988  0.174  0.255  0.441   67.310
DU.w.w    0.103  0.031  0.001  0.080  0.098  0.120    0.448
DD.w.j    0.429  0.554 -0.073  0.163  0.278  0.517   28.340
DU.w.j    0.334  0.550 -0.145  0.075  0.177  0.417   28.286
UD.w.j    0.532  0.555  0.005  0.267  0.381  0.623   28.403
UU.w.j    0.436  0.550  0.001  0.179  0.281  0.520   28.349
DU.j.j    0.096  0.041  0.001  0.070  0.085  0.111    0.548
DD.j.k    0.292  4.601 -0.075  0.168  0.208  0.267  645.836
DU.j.k    0.193  4.601 -0.179  0.073  0.118  0.174  645.724
UD.j.k    0.388  4.602  0.002  0.253  0.295  0.359  645.996
UU.j.k    0.289  4.602  0.001  0.158  0.197  0.257  645.884
DU.k.k    0.099  0.031  0.001  0.079  0.095  0.114    0.333
DD.k.e    0.297  0.348 -0.382  0.142  0.210  0.324   16.546
DU.k.e    0.192  0.348 -0.478  0.038  0.099  0.219   16.458
UD.k.e    0.396  0.351 -0.269  0.236  0.312  0.432   16.642
UU.k.e    0.291  0.350 -0.365  0.135  0.201  0.320   16.554
DU.e.e    0.104  0.032  0.001  0.081  0.100  0.122    0.294
DD.e.u    0.232  0.260 -0.045  0.124  0.170  0.248   14.724
DU.e.u    0.141  0.259 -0.111  0.038  0.080  0.153   14.625
UD.e.u    0.336  0.263  0.005  0.224  0.278  0.361   14.871
UU.e.u    0.245  0.259  0.003  0.140  0.185  0.260   14.772
DU.u.u    0.091  0.029  0.001  0.071  0.087  0.106    0.266
DD.u.r    0.226  0.253  0.001  0.128  0.176  0.246   20.236
DU.u.r    0.131  0.251 -0.100  0.039  0.080  0.145   20.157
UD.u.r    0.317  0.257  0.005  0.213  0.269  0.344   20.335
UU.u.r    0.222  0.253  0.002  0.126  0.173  0.239   20.256
DU.r.r    0.095  0.029  0.001  0.075  0.092  0.112    0.321
DD.r.k    0.445  0.485 -0.051  0.182  0.309  0.560   32.132
DU.r.k    0.350  0.486 -0.148  0.084  0.209  0.469   32.094
UD.r.k    0.540  0.486  0.003  0.275  0.409  0.655   32.200
UU.r.k    0.446  0.486  0.001  0.180  0.309  0.565   32.162
DU.k.k.1  0.095  0.030  0.001  0.073  0.089  0.111    0.292
DD.k.b    0.287  2.374 -0.063  0.152  0.226  0.312  332.701
DU.k.b    0.198  2.374 -0.147  0.057  0.138  0.226  332.605
UD.k.b    0.382  2.375  0.002  0.248  0.322  0.408  332.829
UU.k.b    0.292  2.374  0.001  0.156  0.232  0.316  332.733
DU.b.b    0.090  0.043  0.001  0.070  0.085  0.104    4.573

In [ ]:
# Step 3.94: Identify records with unusually large timing values

import numpy as np

# Find records where any timing feature has an absolute value above 5 seconds
large_timing_mask = (
    df_fixed_clean[timing_feature_columns]
    .abs()
    .gt(5)
    .any(axis=1)
)

# Store the suspicious records in a separate DataFrame
large_timing_records = df_fixed_clean.loc[
    large_timing_mask,
    ["participant", "session", "repetition"]
].copy()

print("Total cleaned records:", len(df_fixed_clean))

print(
    "Records with at least one timing value above 5 seconds:",
    len(large_timing_records)
)

print("\nSuspicious records:")
display(large_timing_records.head(20))

Total cleaned records: 19771
Records with at least one timing value above 5 seconds: 74

Suspicious records:

     participant  session  repetition
633         p004        1          34
1239        p007        1          40
1600        p009        1           1
1951        p010        2          53
2100        p011        2           2
2195        p011        2          97
2199        p012        1           1
2347        p012        2          49
4759        p024        2          57
4821        p025        1          19
4848        p025        1          46
4871        p025        1          69
4944        p025        2          42
4948        p025        2          46
4958        p025        2          56
4965        p025        2          63
4966        p025        2          64
4973        p025        2          71
4984        p025        2          82
6143        p031        2          47

In [ ]:
# Step 3.95: Inspect unusually large timing values

# Select records flagged in Step 3.94
suspicious_data = df_fixed_clean.loc[large_timing_mask].copy()

# Display the participant, session, repetition, and unusual feature values
for index, row in suspicious_data.head(10).iterrows():

    print(
        f"\nParticipant: {row['participant']} | "
        f"Session: {row['session']} | "
        f"Repetition: {row['repetition']}"
    )

    unusual_features = {
        feature: row[feature]
        for feature in timing_feature_columns
        if abs(row[feature]) > 5
    }

    print("Unusual timing features:", unusual_features)

Participant: p004 | Session: 1 | Repetition: 34
Unusual timing features: {'DD.p.w': 7.568, 'DU.p.w': 7.504, 'UD.p.w': 7.613, 'UU.p.w': 7.549}

Participant: p007 | Session: 1 | Repetition: 40
Unusual timing features: {'DD.e.u': 6.402, 'DU.e.u': 6.183, 'UD.e.u': 6.542, 'UU.e.u': 6.323}

Participant: p009 | Session: 1 | Repetition: 1
Unusual timing features: {'DD.p.w': 18.752, 'DU.p.w': 18.624, 'UD.p.w': 18.843, 'UU.p.w': 18.715}

Participant: p010 | Session: 2 | Repetition: 53
Unusual timing features: {'DD.k.e': 5.888, 'DU.k.e': 5.81, 'UD.k.e': 5.943, 'UU.k.e': 5.865}

Participant: p011 | Session: 2 | Repetition: 2
Unusual timing features: {'DD.p.w': 51.415, 'DU.p.w': 51.323, 'UD.p.w': 51.531, 'UU.p.w': 51.439}

Participant: p011 | Session: 2 | Repetition: 97
Unusual timing features: {'DD.r.k': 5.487, 'DU.r.k': 5.387, 'UD.r.k': 5.572, 'UU.r.k': 5.472}

Participant: p012 | Session: 1 | Repetition: 1
Unusual timing features: {'DD.k.e': 5.158, 'DU.k.e': 5.048, 'UD.k.e': 5.28, 'UU.k.e': 5.17}

Participant: p012 | Session: 2 | Repetition: 49
Unusual timing features: {'DD.v.p': 6.416, 'DU.v.p': 6.309, 'UD.v.p': 6.56, 'UU.v.p': 6.453, 'DD.p.w': -6.172, 'DU.p.w': -6.239, 'UD.p.w': -6.065, 'UU.p.w': -6.132}

Participant: p024 | Session: 2 | Repetition: 57
Unusual timing features: {'DD.w.j': 19.644, 'DU.w.j': 19.384, 'UD.w.j': 19.763, 'UU.w.j': 19.503}

Participant: p025 | Session: 1 | Repetition: 19
Unusual timing features: {'UD.u.r': 5.056}

In [ ]:
# Step 3.96: Recheck the two extreme timing records

records_to_check = [
    ("p071", 1, 20),
    ("p087", 1, 8)
]

for participant, session, repetition in records_to_check:

    record = df_fixed_clean[
        (df_fixed_clean["participant"] == participant)
        & (df_fixed_clean["session"] == session)
        & (df_fixed_clean["repetition"] == repetition)
    ]

    print(
        f"\nParticipant: {participant}, "
        f"Session: {session}, "
        f"Repetition: {repetition}"
    )

    if record.empty:
        print("Record not found.")
    else:
        display(
            record[
                ["participant", "session", "repetition"]
                + timing_feature_columns
                + ["total time"]
            ].T
        )

Participant: p071, Session: 1, Repetition: 20

               14002
participant     p071
session            1
repetition        20
DU.v.v         0.144
DD.v.p          0.08
DU.v.p        -0.048
UD.v.p         0.224
UU.v.p         0.096
DU.p.p         0.128
DD.p.w         0.544
DU.p.w           0.4
UD.p.w         0.672
UU.p.w         0.528
DU.w.w         0.144
DD.w.j         0.096
DU.w.j        -0.064
UD.w.j          0.24
UU.w.j          0.08
DU.j.j          0.16
DD.j.k       645.836
DU.j.k       645.724
UD.j.k       645.996
UU.j.k       645.884
DU.k.k         0.112
DD.k.e          0.16
DU.k.e         0.032
UD.k.e         0.272
UU.k.e         0.144
DU.e.e         0.128
DD.e.u         0.384
DU.e.u         0.272
UD.e.u         0.512
UU.e.u           0.4
DU.u.u         0.112
DD.u.r         0.144
DU.u.r         0.031
UD.u.r         0.256
UU.u.r         0.143
DU.r.r         0.113
DD.r.k         0.656
DU.r.k         0.544
UD.r.k         0.769
UU.r.k         0.657
DU.k.k.1       0.112
DD.k.b         0.192
DU.k.b         0.064
UD.k.b         0.304
UU.k.b         0.176
DU.b.b         0.128
total time   647.964

Participant: p087, Session: 1, Repetition: 8

               17184
participant     p087
session            1
repetition         8
DU.v.v         0.119
DD.v.p         0.128
DU.v.p         0.073
UD.v.p         0.247
UU.v.p         0.192
DU.p.p         0.055
DD.p.w         0.648
DU.p.w         0.553
UD.p.w         0.703
UU.p.w         0.608
DU.w.w         0.095
DD.w.j         0.257
DU.w.j         0.193
UD.w.j         0.352
UU.w.j         0.288
DU.j.j         0.064
DD.j.k         0.288
DU.j.k         0.224
UD.j.k         0.352
UU.j.k         0.288
DU.k.k         0.064
DD.k.e         0.128
DU.k.e         0.032
UD.k.e         0.192
UU.k.e         0.096
DU.e.e         0.096
DD.e.u         0.319
DU.e.u         0.256
UD.e.u         0.415
UU.e.u         0.352
DU.u.u         0.063
DD.u.r         0.193
DU.u.r         0.097
UD.u.r         0.256
UU.u.r          0.16
DU.r.r         0.096
DD.r.k          0.96
DU.r.k         0.832
UD.r.k         1.056
UU.r.k         0.928
DU.k.k.1       0.128
DD.k.b       332.701
DU.k.b       332.605
UD.k.b       332.829
UU.k.b       332.733
DU.b.b         0.096
total time   335.526

In [ ]:
# Step 3.97: Create the modeling dataset

# Make a separate copy of the cleaned dataset
df_model = df_fixed_clean.copy()

# Records identified as extreme during our inspection
extreme_records = [
    ("p071", 1, 20),
    ("p087", 1, 8)
]

# Remove only these records from the modeling copy
for participant, session, repetition in extreme_records:

    df_model = df_model[
        ~(
            (df_model["participant"] == participant)
            & (df_model["session"] == session)
            & (df_model["repetition"] == repetition)
        )
    ]

# Reset row numbering
df_model = df_model.reset_index(drop=True)

print("Original cleaned dataset shape:", df_fixed_clean.shape)
print("Modeling dataset shape:", df_model.shape)

print("\nRemaining records:", len(df_model))
print("Unique participants:", df_model["participant"].nunique())
print("Missing values:", df_model.isnull().sum().sum())

print("\nExcluded records:")
display(
    df_fixed_clean[
        df_fixed_clean.apply(
            lambda row: (
                row["participant"],
                row["session"],
                row["repetition"]
            ) in extreme_records,
            axis=1
        )
    ][["participant", "session", "repetition", "total time"]]
)

Original cleaned dataset shape: (19771, 50)
Modeling dataset shape: (19769, 50)

Remaining records: 19769
Unique participants: 99
Missing values: 0

Excluded records:

      participant  session  repetition  total time
14002        p071        1          20     647.964
17184        p087        1           8     335.526

In [ ]:
# Step 3.98: Check remaining extreme timing values

# Find records with at least one absolute timing value above 5 seconds
remaining_extreme_mask = (
    df_model[timing_feature_columns]
    .abs()
    .gt(5)
    .any(axis=1)
)

remaining_extreme_records = df_model.loc[
    remaining_extreme_mask,
    ["participant", "session", "repetition"]
].copy()

print("Total modeling records:", len(df_model))

print(
    "Records with timing values above 5 seconds:",
    len(remaining_extreme_records)
)

print("\nFirst 10 remaining records:")
display(remaining_extreme_records.head(10))

Total modeling records: 19769
Records with timing values above 5 seconds: 72

First 10 remaining records:

     participant  session  repetition
633         p004        1          34
1239        p007        1          40
1600        p009        1           1
1951        p010        2          53
2100        p011        2           2
2195        p011        2          97
2199        p012        1           1
2347        p012        2          49
4759        p024        2          57
4821        p025        1          19

In [ ]:
# Step 3.99: Finalize input features and target labels

# Input features: 46 typing-timing measurements
X = df_model[timing_feature_columns].copy()

# Target labels: participant identities
y = df_model["participant"].copy()

print("Input features shape:", X.shape)
print("Target labels shape:", y.shape)

print("\nNumber of input features:", X.shape[1])
print("Number of participants:", y.nunique())

print("\nMissing values in input features:", X.isnull().sum().sum())
print("Missing values in target labels:", y.isnull().sum())

print("\nFirst five input records:")
display(X.head())

print("\nFirst five target labels:")
display(y.head())

Input features shape: (19769, 46)
Target labels shape: (19769,)

Number of input features: 46
Number of participants: 99

Missing values in input features: 0
Missing values in target labels: 0

First five input records:

,DU.v.v,DD.v.p,DU.v.p,UD.v.p,UU.v.p,DU.p.p,DD.p.w,DU.p.w,UD.p.w,UU.p.w,...,DD.r.k,DU.r.k,UD.r.k,UU.r.k,DU.k.k.1,DD.k.b,DU.k.b,UD.k.b,UU.k.b,DU.b.b
0,0.129,1.917,1.804,2.046,1.933,0.113,0.719,0.569,0.832,0.682,...,1.375,1.289,1.509,1.423,0.086,0.450,0.352,0.536,0.438,0.098
1,0.112,0.192,0.096,0.304,0.208,0.096,0.448,0.296,0.544,0.392,...,1.000,0.921,1.135,1.056,0.079,0.418,0.336,0.497,0.415,0.082
2,0.088,0.253,0.182,0.341,0.270,0.071,1.536,1.417,1.607,1.488,...,1.143,1.066,1.271,1.194,0.077,0.448,0.352,0.525,0.429,0.096
3,0.104,0.323,0.233,0.427,0.337,0.090,0.912,0.782,1.002,0.872,...,0.993,0.927,1.129,1.063,0.066,0.418,0.330,0.484,0.396,0.088
4,0.107,0.188,0.100,0.295,0.207,0.088,0.858,0.721,0.946,0.809,...,1.316,1.237,1.423,1.344,0.079,0.457,0.369,0.536,0.448,0.088

First five target labels:

0    p001
1    p001
2    p001
3    p001
4    p001
Name: participant, dtype: str

In [ ]:
# Step 4.00: Split data using separate sessions

# Training records come from session 1
train_mask = df_model["session"] == 1

# Testing records come from session 2
test_mask = df_model["session"] == 2

# Create training inputs and labels
X_train = X.loc[train_mask].copy()
y_train = y.loc[train_mask].copy()

# Create testing inputs and labels
X_test = X.loc[test_mask].copy()
y_test = y.loc[test_mask].copy()

print("Training data shape:", X_train.shape)
print("Training labels shape:", y_train.shape)

print("\nTesting data shape:", X_test.shape)
print("Testing labels shape:", y_test.shape)

print("\nParticipants in training:", y_train.nunique())
print("Participants in testing:", y_test.nunique())

print("\nTraining sessions:", df_model.loc[train_mask, "session"].unique())
print("Testing sessions:", df_model.loc[test_mask, "session"].unique())

# Check whether all testing participants appear in training
unseen_participants = set(y_test.unique()) - set(y_train.unique())

print("\nParticipants in testing but not training:", unseen_participants)

Training data shape: (9876, 46)
Training labels shape: (9876,)

Testing data shape: (9893, 46)
Testing labels shape: (9893,)

Participants in training: 99
Participants in testing: 99

Training sessions: [1]
Testing sessions: [2]

Participants in testing but not training: set()

In [ ]:
# Step 4.01: Scale the timing features

from sklearn.preprocessing import StandardScaler

# Create the scaler
scaler = StandardScaler()

# Learn scaling parameters from training data only
X_train_scaled = scaler.fit_transform(X_train)

# Apply the same scaling parameters to testing data
X_test_scaled = scaler.transform(X_test)

print("Scaled training data shape:", X_train_scaled.shape)
print("Scaled testing data shape:", X_test_scaled.shape)

print("\nMean of first five scaled training features:")
print(X_train_scaled.mean(axis=0)[:5].round(3))

print("\nStandard deviation of first five scaled training features:")
print(X_train_scaled.std(axis=0)[:5].round(3))

print("\nAny NaN values in training data:", __import__("numpy").isnan(X_train_scaled).any())
print("Any NaN values in testing data:", __import__("numpy").isnan(X_test_scaled).any())

Scaled training data shape: (9876, 46)
Scaled testing data shape: (9893, 46)

Mean of first five scaled training features:
[ 0. -0.  0.  0.  0.]

Standard deviation of first five scaled training features:
[1. 1. 1. 1. 1.]

Any NaN values in training data: False
Any NaN values in testing data: False

In [ ]:
# Step 4.02: Encode participant labels

from sklearn.preprocessing import LabelEncoder

# Create the label encoder
label_encoder = LabelEncoder()

# Learn participant labels from training data
y_train_encoded = label_encoder.fit_transform(y_train)

# Apply the same mapping to testing data
y_test_encoded = label_encoder.transform(y_test)

# Display the results
print("Training labels shape:", y_train_encoded.shape)
print("Testing labels shape:", y_test_encoded.shape)

print("\nTotal number of participants:", len(label_encoder.classes_))

print("\nFirst 10 participant IDs:")
print(label_encoder.classes_[:10])

print("\nFirst 10 encoded training labels:")
print(y_train_encoded[:10])

print("\nMinimum encoded label:", y_train_encoded.min())
print("Maximum encoded label:", y_train_encoded.max())

Training labels shape: (9876,)
Testing labels shape: (9893,)

Total number of participants: 99

First 10 participant IDs:
['p001' 'p002' 'p003' 'p004' 'p005' 'p006' 'p007' 'p008' 'p009' 'p010']

First 10 encoded training labels:
[0 0 0 0 0 0 0 0 0 0]

Minimum encoded label: 0
Maximum encoded label: 98

In [ ]:
# Step 4.03: Build and train the MLP model

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
import warnings
from sklearn.exceptions import ConvergenceWarning

# Create the MLP model
mlp_model = MLPClassifier(
    hidden_layer_sizes=(128, 64),
    activation="relu",
    solver="adam",
    batch_size=256,
    learning_rate_init=0.001,
    max_iter=50,
    early_stopping=False,
    random_state=42,
    verbose=True
)

print("Starting MLP model training...\n")

# Train the model using Session 1 data
with warnings.catch_warnings(record=True) as caught_warnings:
    warnings.simplefilter("always", ConvergenceWarning)
    mlp_model.fit(X_train_scaled, y_train_encoded)

    convergence_warnings = [
        warning for warning in caught_warnings
        if issubclass(warning.category, ConvergenceWarning)
    ]

print("\nModel training completed.")

print("Number of training iterations:", mlp_model.n_iter_)
print("Training data shape:", X_train_scaled.shape)
print("Number of input features:", mlp_model.n_features_in_)
print("Number of output classes:", len(mlp_model.classes_))

if convergence_warnings:
    print("\nNote: The model reached the iteration limit before convergence.")
    print("We will review the training results before deciding whether to adjust it.")

Starting MLP model training...

Iteration 1, loss = 4.42563592
Iteration 2, loss = 3.73784291
Iteration 3, loss = 2.98224367
Iteration 4, loss = 2.49967942
Iteration 5, loss = 2.18168040
Iteration 6, loss = 1.96854887
Iteration 7, loss = 1.80035285
Iteration 8, loss = 1.67686631
Iteration 9, loss = 1.56926222
Iteration 10, loss = 1.48445301
Iteration 11, loss = 1.41218853
Iteration 12, loss = 1.34902585
Iteration 13, loss = 1.29269282
Iteration 14, loss = 1.24669276
Iteration 15, loss = 1.20312022
Iteration 16, loss = 1.16630434
Iteration 17, loss = 1.12845434
Iteration 18, loss = 1.09946602
Iteration 19, loss = 1.06823641
Iteration 20, loss = 1.04430474
Iteration 21, loss = 1.01643849
Iteration 22, loss = 0.99296157
Iteration 23, loss = 0.96998989
Iteration 24, loss = 0.95085582
Iteration 25, loss = 0.93235155
Iteration 26, loss = 0.90893230
Iteration 27, loss = 0.88817037
Iteration 28, loss = 0.87596511
Iteration 29, loss = 0.85639974
Iteration 30, loss = 0.84088754
Iteration 31, loss = 0.82556500
Iteration 32, loss = 0.81622218
Iteration 33, loss = 0.79707311
Iteration 34, loss = 0.78342922
Iteration 35, loss = 0.76641327
Iteration 36, loss = 0.75782674
Iteration 37, loss = 0.74323636
Iteration 38, loss = 0.73221164
Iteration 39, loss = 0.71922088
Iteration 40, loss = 0.71511190
Iteration 41, loss = 0.70422627
Iteration 42, loss = 0.68961458
Iteration 43, loss = 0.68009000
Iteration 44, loss = 0.67011711
Iteration 45, loss = 0.66197086
Iteration 46, loss = 0.64926734
Iteration 47, loss = 0.64360206
Iteration 48, loss = 0.63347600
Iteration 49, loss = 0.62067971
Iteration 50, loss = 0.61583336

Model training completed.
Number of training iterations: 50
Training data shape: (9876, 46)
Number of input features: 46
Number of output classes: 99

Note: The model reached the iteration limit before convergence.
We will review the training results before deciding whether to adjust it.

In [ ]:
# Step 4.04: Evaluate the MLP model

from sklearn.metrics import accuracy_score, balanced_accuracy_score

# Predict participant labels for Session 2
y_test_pred = mlp_model.predict(X_test_scaled)

# Calculate evaluation metrics
test_accuracy = accuracy_score(y_test_encoded, y_test_pred)
test_balanced_accuracy = balanced_accuracy_score(
    y_test_encoded,
    y_test_pred
)

# Calculate training accuracy for comparison
y_train_pred = mlp_model.predict(X_train_scaled)
train_accuracy = accuracy_score(y_train_encoded, y_train_pred)

# Display results
print("MODEL EVALUATION RESULTS")
print("-" * 35)

print(f"Training Accuracy: {train_accuracy * 100:.2f}%")
print(f"Testing Accuracy: {test_accuracy * 100:.2f}%")
print(f"Balanced Testing Accuracy: {test_balanced_accuracy * 100:.2f}%")

print("\nTesting samples:", len(y_test_encoded))
print("Correct predictions:", (y_test_encoded == y_test_pred).sum())
print("Incorrect predictions:", (y_test_encoded != y_test_pred).sum())

MODEL EVALUATION RESULTS
-----------------------------------
Training Accuracy: 83.71%
Testing Accuracy: 44.91%
Balanced Testing Accuracy: 44.91%

Testing samples: 9893
Correct predictions: 4443
Incorrect predictions: 5450

In [ ]:
# Step 4.05: Analyze participant predictions

import pandas as pd
import numpy as np

# Count how often each participant is predicted
predicted_counts = pd.Series(y_test_pred).value_counts()

# Count actual samples for each participant
actual_counts = pd.Series(y_test_encoded).value_counts()

# Compare actual and predicted participant counts
prediction_summary = pd.DataFrame({
    "Actual Samples": actual_counts,
    "Predicted Samples": predicted_counts
}).fillna(0).astype(int)

# Sort by encoded participant label
prediction_summary = prediction_summary.sort_index()

print("Number of participants in actual testing data:",
      actual_counts.size)

print("Number of participants predicted by the model:",
      predicted_counts.size)

print("\nParticipants predicted most frequently:")
print(
    prediction_summary
    .sort_values("Predicted Samples", ascending=False)
    .head(10)
)

print("\nParticipants predicted least frequently:")
print(
    prediction_summary
    .sort_values("Predicted Samples", ascending=True)
    .head(10)
)

print("\nTotal actual testing samples:",
      prediction_summary["Actual Samples"].sum())

print("Total predicted testing samples:",
      prediction_summary["Predicted Samples"].sum())

Number of participants in actual testing data: 99
Number of participants predicted by the model: 99

Participants predicted most frequently:
    Actual Samples  Predicted Samples
67             100                273
7              100                224
20             100                221
46              99                220
11              99                201
60             100                196
79             100                188
38             100                181
12             100                174
39             100                174

Participants predicted least frequently:
    Actual Samples  Predicted Samples
31             100                 17
40             100                 21
6              100                 23
23             100                 32
8              100                 32
88              99                 36
94             100                 37
15             100                 41
87             100                 43
54             100                 46

Total actual testing samples: 9893
Total predicted testing samples: 9893

In [ ]:
# Step 4.06: Analyze accuracy for individual participants

from sklearn.metrics import classification_report
import pandas as pd

# Generate a classification report
report = classification_report(
    y_test_encoded,
    y_test_pred,
    labels=range(len(label_encoder.classes_)),
    target_names=label_encoder.classes_,
    output_dict=True,
    zero_division=0
)

# Convert the report into a DataFrame
participant_report = pd.DataFrame(report).T

# Keep only individual participant results
participant_report = participant_report.loc[
    label_encoder.classes_,
    ["precision", "recall", "f1-score", "support"]
]

# Sort by recall
participant_report_sorted = participant_report.sort_values(
    "recall",
    ascending=False
)

print("TOP 10 PARTICIPANTS BY RECALL")
print(
    participant_report_sorted.head(10).round(3)
)

print("\nBOTTOM 10 PARTICIPANTS BY RECALL")
print(
    participant_report_sorted.tail(10).round(3)
)

print("\nAVERAGE PARTICIPANT RECALL:",
      round(participant_report["recall"].mean() * 100, 2), "%")

TOP 10 PARTICIPANTS BY RECALL
      precision  recall  f1-score  support
p021      0.434   0.960     0.598    100.0
p001      0.922   0.940     0.931    100.0
p003      0.596   0.900     0.717    100.0
p077      0.856   0.890     0.873    100.0
p047      0.400   0.889     0.552     99.0
p064      0.925   0.860     0.891    100.0
p060      0.494   0.850     0.625    100.0
p040      0.489   0.850     0.620    100.0
p057      0.615   0.830     0.706    100.0
p098      0.554   0.820     0.661    100.0

BOTTOM 10 PARTICIPANTS BY RECALL
      precision  recall  f1-score  support
p088      0.209    0.09     0.126    100.0
p041      0.381    0.08     0.132    100.0
p065      0.105    0.06     0.076    100.0
p007      0.217    0.05     0.081    100.0
p013      0.023    0.04     0.029    100.0
p019      0.073    0.04     0.052    100.0
p009      0.094    0.03     0.045    100.0
p090      0.030    0.03     0.030    100.0
p024      0.062    0.02     0.030    100.0
p004      0.018    0.02     0.019    100.0

AVERAGE PARTICIPANT RECALL: 44.91 %

In [ ]:
# Step 4.07: Inspect extreme values in training features

import pandas as pd
import numpy as np

# Create a DataFrame from the training features
X_train_df = X_train.copy()

# Calculate feature statistics
feature_stats = pd.DataFrame({
    "Mean": X_train_df.mean(),
    "Std": X_train_df.std(),
    "Minimum": X_train_df.min(),
    "Maximum": X_train_df.max(),
    "Abs_99th_Percentile": X_train_df.abs().quantile(0.99),
    "Abs_Maximum": X_train_df.abs().max()
})

# Sort features by their largest absolute value
feature_stats = feature_stats.sort_values(
    "Abs_Maximum",
    ascending=False
)

print("TOP 15 FEATURES WITH THE LARGEST ABSOLUTE VALUES")
print(feature_stats.head(15).round(3))

# Count extreme values using a threshold for investigation only
extreme_counts = (X_train_df.abs() > 5).sum()

print("\nFEATURES WITH VALUES ABOVE 5 SECONDS IN ABSOLUTE MAGNITUDE")
print(
    extreme_counts[extreme_counts > 0]
    .sort_values(ascending=False)
)

print("\nTotal feature values exceeding 5 seconds:",
      int((X_train_df.abs() > 5).sum().sum()))

TOP 15 FEATURES WITH THE LARGEST ABSOLUTE VALUES
         Mean    Std  Minimum  Maximum  Abs_99th_Percentile  Abs_Maximum
UD.p.w  0.570  0.630   -3.928   34.021                2.154       34.021
UU.p.w  0.466  0.629   -4.063   33.964                2.068       33.964
DD.p.w  0.474  0.630   -3.944   33.959                2.061       33.959
DU.p.w  0.370  0.630   -4.079   33.902                1.961       33.902
UD.w.j  0.626  0.580    0.048   17.216                2.289       17.216
DD.w.j  0.522  0.579   -0.024   17.113                2.186       17.113
UU.w.j  0.530  0.575    0.002   17.048                2.166       17.048
DU.w.j  0.426  0.574   -0.090   16.945                2.048       16.945
UD.k.e  0.440  0.370   -0.269   12.760                1.773       12.760
UU.k.e  0.336  0.369   -0.365   12.688                1.679       12.688
DD.k.e  0.341  0.367   -0.382   12.680                1.676       12.680
DU.k.e  0.237  0.368   -0.478   12.608                1.584       12.608
UD.j.k  0.386  0.304    0.047    8.990                1.627        8.990
DD.j.k  0.290  0.306   -0.023    8.878                1.540        8.878
UU.j.k  0.287  0.305    0.004    8.861                1.545        8.861

FEATURES WITH VALUES ABOVE 5 SECONDS IN ABSOLUTE MAGNITUDE
UD.w.j    15
UU.w.j    14
DU.w.j    14
DD.w.j    14
DD.p.w     8
UD.p.w     8
UU.p.w     8
DU.p.w     7
DD.r.k     5
UU.r.k     5
UD.r.k     5
DU.r.k     5
DD.k.e     4
UD.k.e     4
UU.k.e     4
DU.k.e     4
DD.e.u     2
DD.j.k     2
DU.j.k     2
UD.j.k     2
UU.j.k     2
UD.e.u     2
UU.e.u     2
DU.e.u     2
UU.v.p     1
DD.v.p     1
DU.v.p     1
UD.v.p     1
UD.u.r     1
dtype: int64

Total feature values exceeding 5 seconds: 145

In [ ]:
# Step 4.08: Identify training records with extreme timing values

import pandas as pd

# Find records containing at least one timing value above 5 seconds
extreme_mask = X_train.abs().gt(5).any(axis=1)

# Select the corresponding records from the modeling dataset
extreme_records = df_model.loc[
    X_train.index[extreme_mask],
    ["participant", "session", "repetition", "total time"]
].copy()

# Count extreme timing features in each record
extreme_records["Extreme Feature Count"] = (
    X_train.loc[extreme_mask].abs().gt(5).sum(axis=1)
)

# Find the largest absolute timing value in each record
extreme_records["Maximum Absolute Timing"] = (
    X_train.loc[extreme_mask].abs().max(axis=1)
)

# Sort records by the largest absolute timing value
extreme_records = extreme_records.sort_values(
    "Maximum Absolute Timing",
    ascending=False
)

print("Training records with at least one extreme timing value:",
      len(extreme_records))

print("\nTop 20 records requiring investigation:")
print(extreme_records.head(20).to_string())

print("\nNumber of affected participants:",
      extreme_records["participant"].nunique())

Training records with at least one extreme timing value: 38

Top 20 records requiring investigation:
      participant  session  repetition  total time  Extreme Feature Count  Maximum Absolute Timing
11010        p056        1          26      37.515                      4                   34.021
1600         p009        1           1      21.818                      4                   18.843
8056         p041        1          61      22.691                      4                   17.216
8801         p045        1           8      19.584                      4                   16.608
11000        p056        1          16      19.925                      4                   15.515
18600        p094        1          31      16.512                      4                   14.278
19171        p098        1           2      15.632                      4                   13.133
8888         p045        1          95      17.889                      4                   12.760
19633        p100        1          65      12.345                      4                   10.732
14212        p072        1          31      12.253                      4                   10.395
10620        p054        1          33      12.976                      4                   10.340
7062         p036        1          67      12.132                      4                   10.100
8048         p041        1          53      13.825                      4                    9.541
8023         p041        1          28      16.900                      4                    8.990
8015         p041        1          20      13.064                      4                    8.708
9819         p050        1          27      11.343                      4                    8.390
8050         p041        1          55      13.777                      4                    7.946
15584        p079        1           7      10.969                      4                    7.671
633          p004        1          34       9.986                      4                    7.613
10829        p055        1          45      10.045                      4                    7.135

Number of affected participants: 22

In [ ]:
# Step 4.09: Inspect the four timing features with the largest extremes

features_to_inspect = [
    "UD.p.w",
    "UU.p.w",
    "DD.p.w",
    "DU.p.w"
]

# Select records containing any value above 5 seconds
extreme_mask = X_train.abs().gt(5).any(axis=1)

# Get the indices of those records
extreme_indices = X_train.index[extreme_mask]

# Select metadata and the four timing features
inspection_columns = [
    "participant",
    "session",
    "repetition",
    "total time"
]

extreme_feature_inspection = df_model.loc[
    extreme_indices,
    inspection_columns
].copy()

# Add the selected timing features
for feature in features_to_inspect:
    extreme_feature_inspection[feature] = X_train.loc[
        extreme_indices, feature
    ]

# Display the 15 records with the largest absolute value
extreme_feature_inspection["Largest Absolute Value"] = (
    extreme_feature_inspection[features_to_inspect]
    .abs()
    .max(axis=1)
)

extreme_feature_inspection = extreme_feature_inspection.sort_values(
    "Largest Absolute Value",
    ascending=False
)

print("Extreme timing feature inspection:")
print(
    extreme_feature_inspection.head(15).round(3).to_string()
)

Extreme timing feature inspection:
      participant  session  repetition  total time  UD.p.w  UU.p.w  DD.p.w  DU.p.w  Largest Absolute Value
11010        p056        1          26      37.515  34.021  33.964  33.959  33.902                  34.021
1600         p009        1           1      21.818  18.843  18.715  18.752  18.624                  18.843
8801         p045        1           8      19.584  16.608  16.504  16.520  16.416                  16.608
18600        p094        1          31      16.512  14.278  14.175  14.208  14.105                  14.278
15584        p079        1           7      10.969   7.671   7.586   7.600   7.515                   7.671
633          p004        1          34       9.986   7.613   7.549   7.568   7.504                   7.613
16403        p083        1          26       6.852   5.941   5.851   5.876   5.786                   5.941
8890         p045        1          97       8.416   5.112   5.017   5.056   4.961                   5.112
8056         p041        1          61      22.691   2.517   2.414   2.429   2.326                   2.517
8050         p041        1          55      13.777   1.989   1.851   1.859   1.721                   1.989
8048         p041        1          53      13.825   1.581   1.487   1.468   1.374                   1.581
6797         p035        1           1      14.500   1.360   1.282   1.259   1.181                   1.360
8015         p041        1          20      13.064   1.326   1.232   1.274   1.180                   1.326
8023         p041        1          28      16.900   1.320   1.197   1.182   1.059                   1.320
4821         p025        1          19       9.202   1.250   1.134   1.204   1.088                   1.250

In [ ]:
# Step 4.10: Create training and validation subsets from Session 1

from sklearn.model_selection import train_test_split

# Split the original training data while preserving participant proportions
X_train_sub, X_val, y_train_sub, y_val = train_test_split(
    X_train,
    y_train_encoded,
    test_size=0.20,
    random_state=42,
    stratify=y_train_encoded
)

print("Training subset shape:", X_train_sub.shape)
print("Validation subset shape:", X_val.shape)

print("\nTraining labels shape:", y_train_sub.shape)
print("Validation labels shape:", y_val.shape)

print("\nNumber of participants in training subset:",
      len(set(y_train_sub)))

print("Number of participants in validation subset:",
      len(set(y_val)))

Training subset shape: (7900, 46)
Validation subset shape: (1976, 46)

Training labels shape: (7900,)
Validation labels shape: (1976,)

Number of participants in training subset: 99
Number of participants in validation subset: 99

In [ ]:
# Step 4.11: Train the final MLP model

from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier

# Scale the complete Session 1 training data
final_scaler = StandardScaler()

X_train_final_scaled = final_scaler.fit_transform(X_train)
X_test_final_scaled = final_scaler.transform(X_test)

# Create the final MLP model
final_mlp_model = MLPClassifier(
    hidden_layer_sizes=(128, 64),
    activation="relu",
    solver="adam",
    batch_size=256,
    learning_rate_init=0.001,
    max_iter=100,
    random_state=42
)

# Train the model
print("Training the final MLP model...")

final_mlp_model.fit(
    X_train_final_scaled,
    y_train_encoded
)

print("\nFinal MLP model training completed!")
print("Training samples:", X_train_final_scaled.shape[0])
print("Number of features:", X_train_final_scaled.shape[1])
print("Number of participants:", len(final_mlp_model.classes_))
print("Training iterations:", final_mlp_model.n_iter_)

Training the final MLP model...

Final MLP model training completed!
Training samples: 9876
Number of features: 46
Number of participants: 99
Training iterations: 100

c:\Users\LOQ\OneDrive\Desktop\Komal_clg\5th sem\DL Lab\Project\DeepKey_DL_Project\venv_new\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

In [ ]:
# Step 4.12: Evaluate the final MLP model

from sklearn.metrics import accuracy_score, balanced_accuracy_score

# Predict participants in the training data
y_train_final_pred = final_mlp_model.predict(X_train_final_scaled)

# Predict participants in the test data
y_test_final_pred = final_mlp_model.predict(X_test_final_scaled)

# Calculate accuracy
final_train_accuracy = accuracy_score(
    y_train_encoded,
    y_train_final_pred
)

final_test_accuracy = accuracy_score(
    y_test_encoded,
    y_test_final_pred
)

# Calculate balanced accuracy
final_balanced_accuracy = balanced_accuracy_score(
    y_test_encoded,
    y_test_final_pred
)

# Count correct and incorrect predictions
correct_predictions = (
    y_test_encoded == y_test_final_pred
).sum()

incorrect_predictions = (
    y_test_encoded != y_test_final_pred
).sum()

# Display results
print("========== FINAL MLP MODEL RESULTS ==========")

print(f"Training Accuracy: {final_train_accuracy * 100:.2f}%")
print(f"Testing Accuracy: {final_test_accuracy * 100:.2f}%")
print(f"Balanced Testing Accuracy: {final_balanced_accuracy * 100:.2f}%")

print("\nTotal Test Samples:", len(y_test_encoded))
print("Correct Predictions:", correct_predictions)
print("Incorrect Predictions:", incorrect_predictions)

========== FINAL MLP MODEL RESULTS ==========
Training Accuracy: 91.70%
Testing Accuracy: 44.59%
Balanced Testing Accuracy: 44.58%

Total Test Samples: 9893
Correct Predictions: 4411
Incorrect Predictions: 5482

In [ ]:
# Step 4.13: Save the trained model and scaler

import joblib
from pathlib import Path

# Find the project root directory
project_root = Path.cwd().parent

# Create the models directory if it doesn't exist
models_dir = project_root / "models"
models_dir.mkdir(parents=True, exist_ok=True)

# Save the trained MLP model
joblib.dump(
    final_mlp_model,
    models_dir / "deepkey_mlp_model.pkl"
)

# Save the fitted scaler
joblib.dump(
    final_scaler,
    models_dir / "deepkey_scaler.pkl"
)

print("Model and scaler saved successfully!")

print("Model path:", models_dir / "deepkey_mlp_model.pkl")
print("Scaler path:", models_dir / "deepkey_scaler.pkl")

Model and scaler saved successfully!
Model path: c:\Users\LOQ\OneDrive\Desktop\Komal_clg\5th sem\DL Lab\Project\DeepKey_DL_Project\models\deepkey_mlp_model.pkl
Scaler path: c:\Users\LOQ\OneDrive\Desktop\Komal_clg\5th sem\DL Lab\Project\DeepKey_DL_Project\models\deepkey_scaler.pkl

In [ ]:
# Step 4.14: Verify the saved model and scaler

import joblib
from pathlib import Path

# Locate the saved files
model_path = models_dir / "deepkey_mlp_model.pkl"
scaler_path = models_dir / "deepkey_scaler.pkl"

# Load the saved model and scaler
loaded_model = joblib.load(model_path)
loaded_scaler = joblib.load(scaler_path)

# Verify that they loaded correctly
print("Model loaded successfully:", loaded_model is not None)
print("Scaler loaded successfully:", loaded_scaler is not None)

print("Number of model input features:",
      loaded_model.n_features_in_)

print("Number of participants:",
      len(loaded_model.classes_))

Model loaded successfully: True
Scaler loaded successfully: True
Number of model input features: 46
Number of participants: 99

In [ ]:
# Step 4.15: Check whether Streamlit is installed

import importlib.util

if importlib.util.find_spec("streamlit") is not None:
    print("Streamlit is installed.")
else:
    print("Streamlit is not installed.")
    print("We need to install it before building the dashboard.")

Streamlit is not installed.
We need to install it before building the dashboard.